### PR TITLE
Move LLVMGPURemoveTrivialLoops to Common/ and use it for SPIR-V

### PR DESCRIPTION
**Pull request by antiagainst**
This removes the ad-hoc trip one loop removal pass in the SPIR-V
backend; so better unification and less code to maintain! :)

### CODE REVIEW

**Comment by benvanik** [comment]
(I'll probably use this for vmvx too! thanks for factoring it out)

**Comment by antiagainst** [comment]
> (I'll probably use this for vmvx too! thanks for factoring it out)

Yup! It's general enough so should be able to share there!

**Review by MaheshRavishankar — APPROVED** [review]
Have forgotten the details of how the single iteration loop pass works, but apart from that this looks fine to me. THanks!

**Review by ThomasRaoux — APPROVED** [review]
Thanks for cleaning this up!

**Pull request merged**
