### PR TITLE
Always pass `--output-format=vm-c` in iree_c_module.

### PR DESCRIPTION
**Pull request by ScottTodd**
This matches how iree_bytecode_module always passes `--output-format=vm-bytecode`.

Follow-up to https://github.com/google/iree/pull/9431

### CODE REVIEW

**Comment by benvanik** [comment]
do we want to do the compile mode too? vm-c implies targeting the vm

**Comment by ScottTodd** [comment]
> do we want to do the compile mode too? vm-c implies targeting the vm

Ah... maybe... I think compile mode talks about what the input is, and we could still go from our standard mix of input dialects down to vm-c output?

https://github.com/google/iree/blob/e029d0f787203544777a5fccab6955fa5d5bb7a0/compiler/src/iree/compiler/Tools/iree_compile_lib.cc#L146-L156

this also reminds me that I can remove the `--iree-hal-target-backends=vmvx` flags for a bunch of these targets.

**Comment by benvanik** [comment]
oh you're right, TIL - ignore me :P

**Review by jpienaar — APPROVED** [review]
Thanks!

**Pull request merged**
