### PR TITLE
Updating tracy version.

### PR DESCRIPTION
**Pull request by benvanik**

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]
@antiagainst can you also update the capture tool used as part of the benchmarking pipeline? https://github.com/google/iree/blob/bcb6199e19d5a6320397258a8028fc5ec3459d0d/build_tools/buildkite/cmake/android/arm64-v8a/benchmark2.yml#L31-L34

**Comment by antiagainst** [comment]
Yes, time to update the capture tool. Let me do that.

**Review by antiagainst — CHANGES_REQUESTED** [review]
Blocking until I upload a tracy capture binary.

**Comment by benvanik** [comment]
thanks!

**Comment by benvanik** [comment]
(and no rush!)

**Comment by antiagainst** [comment]
Okay uploaded a new tracy `capture` tool. Let's see how it goes.

**Comment by benvanik** [comment]
Worked on the moto, at least.
Now have GPU stats though we still have the issue with the zones not deduplicating ;(
image
Really wish we knew why that happened.

**Comment by benvanik** [comment]
Sampling and all worked on the moto, so at least android works - just something about the pixel phones
image

**Comment by antiagainst** [comment]
Hmm, mysterious "segmentation fault" coming from both Pixel phones. On both phones, captures succeeded before `adb shell cd /data/local/tmp/iree-benchmarks/TFLite/MobileNetV2-fp32,imagenet/iree-dylib-sync__CPU-ARM64-v8A__little-core,full-inference,experimental-flags && TRACY_NO_EXIT=1 taskset 0f /data/local/tmp/iree-benchmarks/traced-tools/iree-benchmark-module --flagfile=flagfile`. There might be something weird specific to this case?

**Comment by antiagainst** [comment]
Actually searching found [other](https://buildkite.com/iree/iree-benchmark/builds/2351#71c1910c-abc7-49ac-9b8f-8ce4bb279b6d/6-559) "segmentation fault" but doesn't affect things??

**Comment by bjacob** [comment]
The segfault might be happening during Tracy's complex (involving thread exit hooks), somewhat suspect (e.g. TSan failures) shutdown sequence?  It would be interesting for sure to see that captured in a debugger.

As far as I'm concerned, this update is a necessary step anyway to playing with Tracy on recent Android devices, so 👍 to merging this as soon as CI is green.

**Review by bjacob — APPROVED** [review]
Wait, are we not likewise bumping third_party/tracy ?

**Pull request closed without merging**
