### PR TITLE
Merge google -> main

### PR DESCRIPTION
**Pull request by ThomasRaoux**
* 667a75065 Synchronize submodules with LLVM at llvm/llvm-project@638dcea010cf
* 099dce5da Integrate LLVM at llvm/llvm-project@638dcea010cf
* d5ce351d6 Merge pull request #6718 from ThomasRaoux:main-to-google
* a9543faec Integrate LLVM at llvm/llvm-project@f63b1bf7f49e
* b9988d9d1 Integrate LLVM at llvm/llvm-project@9d982c67ba01

### CODE REVIEW

**Review by ScottTodd — CHANGES_REQUESTED** [review]
The `llvm-projects/` files should be `llvm-external-projects` (no changes on this branch merge). Needs another Copybara tweak maybe?

**Comment by ScottTodd** [comment]
> The `llvm-projects/` files should be `llvm-external-projects` (no changes on this branch merge). Needs another Copybara tweak maybe?

Ah, the `google` branch has both:

image

https://github.com/google/iree/tree/google

**Comment by ThomasRaoux** [comment]
> > The `llvm-projects/` files should be `llvm-external-projects` (no changes on this branch merge). Needs another Copybara tweak maybe?
> 
> Ah, the `google` branch has both:
> 
> image
> 
> https://github.com/google/iree/tree/google

Thanks for catching this! Fixed it.

**Review by ScottTodd — APPROVED** [review]
phew, much better :D

**Pull request closed without merging**
