### PR TITLE
Add and/or reduce support to VMLA

### PR DESCRIPTION
**Pull request by rsuderman**
Handles the tf.math.reduce_any and tf.math.reduce_all operations.
Added a reduce_test.py file to check all reductions.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
@phoenix-meadowlark is there a pithier way to write TF tests now?

**Review by GMNGeoffrey — APPROVED** [review]

**Comment by phoenix-meadowlark** [comment]
Yes, though all of these tests are auto-generated by https://github.com/google/iree/pull/3826 and I'll delete these tests in a merge commit as soon as they land, so there's probably not much point in changing them 😅 

It does make writing tests like these a lot less tedious though. See:
- [docs](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/README.md#via-tf_test_utilstf_function_unittest)
- [concrete example](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/conv_test.py)

**Comment by rsuderman** [comment]
> Yes, though all of these tests are auto-generated by #3826 and I'll delete them in a merge commit as soon as they land, so there's probably not much point in changing them 
> 
> It does make writing tests like these a lot less tedious though. See:
> 
> * [docs](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/README.md#via-tf_test_utilstf_function_unittest)
> * [concrete example](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/conv_test.py)

I assume you feed random data as an input? For min/max/sum I can see this working but guaranteeing coverage on binary operation seems a little trickier.

**Comment by phoenix-meadowlark** [comment]
> > Yes, though all of these tests are auto-generated by #3826 and I'll delete them in a merge commit as soon as they land, so there's probably not much point in changing them
> > It does make writing tests like these a lot less tedious though. See:
> > 
> > * [docs](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/README.md#via-tf_test_utilstf_function_unittest)
> > * [concrete example](https://github.com/google/iree/blob/main/integrations/tensorflow/e2e/conv_test.py)
> 
> I assume you feed random data as an input? For min/max/sum I can see this working but guaranteeing coverage on binary operation seems a little trickier.

Good point! You can specify input_args as well, so for `any` and `all` I'll add tests of all true and all false respectively.

**Review by phoenix-meadowlark — APPROVED** [review]

**Pull request merged**
