### PR TITLE
Disable CPU workgroup padding

### PR DESCRIPTION
**Pull request by antiagainst**
This causes segfault on Android devices:
https://buildkite.com/iree/iree-android-arm64-v8a/builds/4235

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by benvanik** [comment]
Thanks!

**Comment by antiagainst** [comment]
Kicked off https://buildkite.com/iree/iree-android-arm64-v8a/builds/4241 to try this out.

**Comment by antiagainst** [comment]
https://buildkite.com/iree/iree-android-arm64-v8a/builds/4241 passes. I think the failure (https://source.cloud.google.com/results/invocations/36bd6c09-e10d-42d4-b67b-910a6589ebb7/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-swiftshader%2Fpresubmit/log) is not related to this.

**Comment by antiagainst** [comment]
@GMNGeoffrey could you help me to land this?

**Comment by GMNGeoffrey** [comment]
Newly-added test turns out to be flakey. https://github.com/google/iree/issues/5885

Overriding required checks, having confirmed that's the only thing that is failing

**Pull request merged**
