### PR TITLE
[CUDA] Enable tiling for pooling and re-enable execution test

### PR DESCRIPTION
**Pull request by ThomasRaoux**

### CODE REVIEW

**Review by antiagainst — APPROVED** [review]
LGTM. But I generally feel we lack LIT tests for CUDA side; failures typically reveal via integration tests. It would be nice to improve on that front. :)

**Comment by ThomasRaoux** [comment]
>  failures typically reveal via integration tests. 
Please, feel free to report such cases to me, that hasn't been my experience. If this is the case I'd like to know :)

**Comment by antiagainst** [comment]
> > failures typically reveal via integration tests.
> 
> Please, feel free to report such cases to me, that hasn't been my experience. If this is the case I'd like to know :)

The pooling ops here are examples right? It's revealed by e2e xla runtime tests. ("Integration test" might be a bit confusing; I didn't mean integrating across GitHub and Google internal repo. But generally runtime tests would require special development environment that may not enabled everywhere and presubmit.) It might worth having a case in [distribute_to_thread.mlir](https://github.com/google/iree/blob/main/iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir) for pooling ops so in the future if we touch how pooling ops are handled they will be caught there. :) But I do see we have much more tests in [LLVMGPU/test](https://github.com/google/iree/tree/main/iree/compiler/Codegen/LLVMGPU/test) than before. So my impression was outdated. Sorry about that! I'm just hitting a special corner case here. :)

**Comment by ThomasRaoux** [comment]
> > > failures typically reveal via integration tests.
> > 
> > 
> > Please, feel free to report such cases to me, that hasn't been my experience. If this is the case I'd like to know :)
> 
> The pooling ops here are examples right? It's revealed by e2e xla runtime tests. ("Integration test" might be a bit confusing; I didn't mean integrating across GitHub and Google internal repo. But generally runtime tests would require special development environment that may not enabled everywhere and presubmit.) It might worth having a case in [distribute_to_thread.mlir](https://github.com/google/iree/blob/main/iree/compiler/Codegen/LLVMGPU/test/distribute_to_thread.mlir) for pooling ops so in the future if we touch how pooling ops are handled they will be caught there. :) But I do see we have much more tests in [LLVMGPU/test](https://github.com/google/iree/tree/main/iree/compiler/Codegen/LLVMGPU/test) than before. So my impression was outdated. Sorry about that! I'm just hitting a special corner case here. :)

Well the pooling case was a legit bug existing independently of your change, not sure why the integration test was passing in a first place, it should have been failing. Bugs will always be there unfortunately, this is annoying when they are exposed by other changes, sorry you had to deal with that. I'm honestly curious about the impression that it is lacking unit testing, feel free to just send me an informal ping me when you run into this kind of cases.

**Pull request merged**
