### PR TITLE
Print time along with command in kokoro

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
This is useful information to have for looking at approximate runtime for each command and such.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
> Want to include anything else (like the date or milliseconds)?

Yeah I thought about it. I figured since we probably knew the date of execution in general it would be a bit redundant (just extra noise) and that milliseconds are probably providing false precision and aren't that useful. I'm happy to add either if you disagree though.

**Comment by ScottTodd** [comment]
Oh wait, there's already an option in the UI on GitHub to view timestamps. Let's just use that, and keep our scripts simpler?

**Comment by GMNGeoffrey** [comment]
Only for github actions. The bazel build script is only used in kokoro and we're probably going to have to switch cmake to kokoro to get the status-posting APIs to match for feedback upstream and to leverage an external service (goma) to make the build not take an eternity.

Also these scripts are used locally.

**Comment by GMNGeoffrey** [comment]
I can try sticking it in kokoro/gcp_ubuntu/bazel_build.sh and see if it propagates (should do with export, I think). I put it here because I figured it was intimately tied to `set -x`, which we're already setting here. I think you reasoning makes sense though. We could also drop `set -x` from here if it propagates from the main script. I think it's much less important when running locally. Thoughts?

**Comment by ScottTodd** [comment]
Yeah, I think you should be able to put the `PS4=` in `kokoro/gcp_ubuntu/bazel_build.sh` and have it propagate. If we can directly configure the VMs, we could also put setup in something system-wide like `~/.bashrc`? It'll be easier to configure in a checked in script though, so try that first?

**Comment by GMNGeoffrey** [comment]
Changed to only set PS4 in the kokoro build script. We can investigate setting it in the VM env, although I'm not sure that's really better since it requires UI-based configuration right now and is a bit more opaque

**Comment by GMNGeoffrey** [comment]
Please tag this for pull if you think it LG now

**Comment by GMNGeoffrey** [comment]
I guess you basically already approved with this change.

**Pull request closed without merging**
