### PR TITLE
Refactor dependecy handling

### PR DESCRIPTION
**Pull request by marbre**
* Variables defining (conditional) dependencies are moved from the Bazel `BUILD` files to `build_defs.oss.bzl` files.
* Adds the CMake module `iree_build_defs`, that imitates the *new* behavior and defines variables holding dependencies.

Please consider this only as a proposal, which might make it easier to extend `bazel_to_cmake.py`. I am open minded for other suggestions.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Sorry it's taken a bit to look at this. I think this is a reasonable suggestion for making the bazel->cmake translation easier. I think we may have to do some work internally to merge this since there are additional files for our upstream shims that don't get open sourced here. So there may be a delay in merging this and making sure it works with our internal build also

**Comment by marbre** [comment]
Sure, no need to hurry. In fact, I already assumed that this might also affect upstream.

**Comment by GMNGeoffrey** [comment]
Sorry I never got to this. I think some refactoring would still be useful and I have some ideas, but haven't gotten to it. Since bazel to cmake now works with the hardcoded values I think that should be fine.

There's an effort internally to get people to stop using variables in dependencies and that might also incentivize me to take another look at this. I think we could do most of these as just cc_library that groups its deps.

**Comment by marbre** [comment]
Oh I think I accidentally deleted this branch during clean up, it was not intended to close the PR. No need to apologize :)
As things have changed in the meantime, I agree that it should be fine for now. If not, I will just send a new PR as this oneisn't mergeable without additional effort anyway.

**Pull request closed without merging**
