### PR TITLE
Install libxml2-dev on RBE executors

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
This is needed to build lld (at least as currently configured).

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
I again suspect you think we shouldn't merge this on Friday afternoon, although it should be fully exercised by presubmit. Could you merge while I'm away next week?

**Comment by GMNGeoffrey** [comment]
Android build is broken at HEAD and not possible affected by this change

**Comment by benvanik** [comment]
Will be fixed with https://github.com/google/iree/pull/6679 (that build is the only one that runs benchmarks and shows breakages there)

**Comment by GMNGeoffrey** [comment]
> Will be fixed with #6679 (that build is the only one that runs benchmarks and shows breakages there)

Sure but this only affects Bazel builds and that build only uses CMake

**Review by ScottTodd — APPROVED** [review]

**Pull request merged**
