### PR TITLE
[snapshot release] Fix push command for the latest-snapshot branch

### PR DESCRIPTION
**Pull request by hcindyl**
Fix https://github.com/google/iree/runs/3480016077?check_suite_focus=true

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]
Sure, let's try this 😄
If it fails, we can debug outside of this action

**Comment by ScottTodd** [comment]
Success! https://github.com/google/iree/tree/latest-snapshot
https://github.com/google/iree/actions/runs/1190685236
Let's keep an eye on it to make sure the next run updates the branch too.

**Comment by GMNGeoffrey** [comment]
I'd bet that this was only necessary for the first run because the branch didn't already exist. Just providing `latest-snapshot` should work now (note that the error logs ask if you're trying to create a new branch)

**Comment by hcindyl** [comment]
I agree with you. The PR was based on that error log. However, leave the `refs/heads/latest-snapshot` as the branch name shouldn't hurt, since it is called with the syntax of https://github.com/ad-m/github-push-action/blob/master/start.sh#L28

**Comment by ScottTodd** [comment]
> oh no.... another failure.
> https://github.com/google/iree/runs/3491586526?check_suite_focus=true
> 
> This one doesn't make sense though. There's should be no merge conflict. Maybe we need to add the force push?

Maybe fetch the branch we're going to push to?

https://github.com/google/iree/blob/64e52252fed14db75f0f8f9c15ce5faf1ec590fa/.github/workflows/publish_website.yml#L28-L30

https://github.com/google/iree/blob/64e52252fed14db75f0f8f9c15ce5faf1ec590fa/.github/workflows/lint.yml#L29-L34

**Comment by hcindyl** [comment]
In an offline flow, it should be

git checkout <ref> -b new-snapshot
git fetch origin latest-snapshot:latest-snapshot
git merge new-snapshot
git push origin HEAD:refs/heads/latest-snapshot

I will see how it should play with the workflow.

**Comment by hcindyl** [comment]
I think this is the problem, in https://github.com/actions/checkout
```
# Number of commits to fetch. 0 indicates all history for all branches and tags.
# Default: 1
fetch-depth: ''
```

The depth is too shallow to update the branch. Something like 50 should be more than enough for twice-a-day update if we don't want to set it to 0.

**Comment by hcindyl** [comment]
https://github.com/google/iree/pull/6945. I tested offline with the exact commands listed in the action log. fetch-depth=1 failed and fetch-depth=200 was okay

**Pull request merged**
