### PR TITLE
Upgrade TF pip to 2.7.0

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
Fixes https://github.com/google/iree/issues/6595

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Ok so now that we have timeouts instead of just hanging forever, we can see that this causes a bunch of the KWS tests to time out: https://source.cloud.google.com/results/invocations/bf261cd4-8978-466f-bc10-570ddd8ad7b8/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-swiftshader%2Fpresubmit/log. Likely they would have deadlocked before

**Comment by GMNGeoffrey** [comment]
The diff of the logs between the successful and failing tests is not very helpful. Both print out some TF warning spam, complain about the lack of cuda, and then say how they're optimized with oneDNN. Then with 2.6 everything passes and with 2.7 it hangs forever. We actually even have less warning spam with 2.7.

**Comment by GMNGeoffrey** [comment]
> Ok so now that we have timeouts instead of just hanging forever, we can see that this causes a bunch of the KWS tests to time out: [source.cloud.google.com/results/invocations/bf261cd4-8978-466f-bc10-570ddd8ad7b8/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-swiftshader%2Fpresubmit/log](https://source.cloud.google.com/results/invocations/bf261cd4-8978-466f-bc10-570ddd8ad7b8/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-swiftshader%2Fpresubmit/log). Likely they would have deadlocked before

Fixed by upgrading kws as well (duh :-P)

**Comment by GMNGeoffrey** [comment]
Note: I manually triggered the TF integration tests on real GPUs since this changes the docker image used there

**Comment by GMNGeoffrey** [comment]
Ugh real GPU tests fail...

**Comment by GMNGeoffrey** [comment]
@ScottTodd I'm assuming you think we shouldn't merge this on Friday afternoon :-P I'll be out next week and it would be nice to get this in since it's all tested and new things could go wrong otherwise. Would you mind merging on Monday when folks will be around to debug or rollback as necessary?

**Review by ScottTodd — APPROVED** [review]

**Pull request merged**
