### PR TITLE
Bump LLVM and TensorFlow project submodule

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Comment by ScottTodd** [comment]
Automated bump in https://github.com/google/iree/pull/1866 looks to be recent enough, if you want to approve that

**Comment by antiagainst** [comment]
There are two new LLVM integrate commits landed. #1866 does not include them?

**Comment by ScottTodd** [comment]
> There are two new LLVM integrate commits landed. #1866 does not include them?

Ah, looks like you're right. Let's go with this one also?

**Comment by antiagainst** [comment]
+1. Refreshed.

**Pull request closed without merging**
