### PR TITLE
Submodule Update

### PR DESCRIPTION
**Pull request by rsuderman**
Updated manually due to auto-generated module update being at a broken bazel build revision.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
FYI you don't need to set "kokoro:run" since you're a collaborator

**Comment by ScottTodd** [comment]
What's the difference between this and https://github.com/google/iree/pull/1254 ? Does this include a build fix or something? The PR / commit message could be more useful here.

**Comment by rsuderman** [comment]
> What's the difference between this and #1254 ? Does this include a build fix or something? The PR / commit message could be more useful here.

This one is more recent. That one has a bad bazel build :(

**Comment by GMNGeoffrey** [comment]
> > What's the difference between this and #1254 ? Does this include a build fix or something? The PR / commit message could be more useful here.
> 
> This one is more recent. That one has a bad bazel build :(

Please phrase your response in the form of a PR description :-P

**Comment by rsuderman** [comment]
> > > What's the difference between this and #1254 ? Does this include a build fix or something? The PR / commit message could be more useful here.
> > 
> > 
> > This one is more recent. That one has a bad bazel build :(
> 
> Please phrase your response in the form of a PR description :-P

Done.

**Pull request closed without merging**
