### PR TITLE
Add torch.bincount op lowering in linalg_ext

### PR DESCRIPTION
**Pull request by vivekkhandelwal1**
This patch adds code to lower the op using the
`generateScalarImplementation` method.

Op description is given at
https://pytorch.org/docs/stable/generated/torch.bincount.html.

### CODE REVIEW

**Comment by vivekkhandelwal1** [comment]
@MaheshRavishankar, @harsh-nod, please review this PR.

**Comment by MaheshRavishankar** [comment]
This operation is way too specific. If we want such an operation (and I hope we think long and hard about whether this operation is really needed), then it needs to generalize to a class of operations from front end dialect. We want to have a small footprint of operations in the `linalg_ext` dialect. I did mention that we need to discuss what class of operations we need to support before we go down the path for implementing this. I'd like to pause this work to take a deeper look at whether there are a class of operations that need to be supported and if they can be supported using existing operations.

Just putting "changes requested" for now since this requires more discussion.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Marking "request changes" cause this approach needs a deeper look.

**Comment by vivekkhandelwal1** [comment]
> This operation is way too specific. If we want such an operation (and I hope we think long and hard about whether this operation is really needed), then it needs to generalize to a class of operations from front end dialect. We want to have a small footprint of operations in the `linalg_ext` dialect. I did mention that we need to discuss what class of operations we need to support before we go down the path for implementing this. I'd like to pause this work to take a deeper look at whether there are a class of operations that need to be supported and if they can be supported using existing operations.
> 
> Just putting "changes requested" for now since this requires more discussion.

Thanks, @MaheshRavishankar, for the feedback. I am closing this PR; we can use the scatter op in place of bincount to get the same functionality.

**Comment by hanhanW** [comment]
We probably can't use scatter op in this case because of races (at least in IREE). We definitely need a deeper discussion before adding the op.

**Comment by vivekkhandelwal1** [comment]
Hi @MaheshRavishankar, after discussing with @cathyzhyi, we concluded that we could implement a `scatter-like op` that will be generalized and satisfy our requirements. It will have two fundamental differences from the original `scatter op`:
1.) In the original scatter op, the indices are constrained to be a 2-d tensor, while in this case, it would be constrained to a 1-d tensor.
2.) In the original scatter op, all the loop iterators are parallel, while in our case, one will be reduction type, and the remaining ones will be parallel.

Can we go ahead with this op? If yes, what would be the appropriate name for this op?

**Pull request closed without merging**
