### PR TITLE
Bump Bazel version to 2.1.0.

### PR DESCRIPTION
**Pull request by ScottTodd**
TensorFlow bumped to 2.0.0 in https://github.com/tensorflow/tensorflow/commit/daec6e0af0dfe39aada697275a76570da7f04608. In order to sync our TensorFlow submodule, we also need to update (https://github.com/google/iree/issues/834).

I ran into errors building with 2.0.0 (the same as in https://github.com/google/iree/issues/174), so I went with a newer version (2.1.0) that seems to work for this repository.

### CODE REVIEW

**Comment by ScottTodd** [comment]
Let's wait for the CI to be stable again before trying to merge this.

**Comment by GMNGeoffrey** [comment]
The CI doesn't use bazelisk, so you're going to need to update it separately there (or set up bazelisk)

**Comment by ScottTodd** [comment]
As far as I can tell, Bazel itself only partly respects `.bazelversion`.

If you run `bazel` (no args) or `bazel --version` when a `.bazelversion` is present, it will warn if the version differs:
```
scotttodd:~/code/iree$ bazel --version
ERROR: The project you're trying to build requires Bazel 2.0.0 (specified in .../code/iree/.bazelversion), but it wasn't found in /usr/bin.

You can install the required Bazel version via apt:
  sudo apt update && sudo apt install bazel-2.0.0

If this doesn't work, check Bazel's installation instructions for help:
  https://docs.bazel.build/versions/master/install-ubuntu.html
```

if you run `bazel build path/to/dir:target` and the version doesn't match, it will proceed as usual. So the CI *could* (and probably *should*) be updated, but it doesn't appear to be strictly required. We could set up `bazelisk` on the CI to make the version management more automated.

**Comment by GMNGeoffrey** [comment]
I mean it's required in the sense that if we're telling users we support some version then that's the version we should test. We could set up bazelisk on the CI, although it comes with some non-trivial issues, like it will download the binary if it doesn't have it already, which we probably don't want on the CI because we should stick the right version on the VM.

**Comment by ScottTodd** [comment]
Okay, I'll update the CI along with this change (next week or later, I'm in no rush).

Also saw this in [patch notes for Bazel 2.0](https://blog.bazel.build/2019/12/19/bazel-2.0.html):
> Bazel's Debian package and the binary installer now include an improved wrapper that understands <WORKSPACE>/.bazelversion files and the $USE_BAZEL_VERSION environment variable. This is similar to what Bazelisk offers, except that it works offline and integrates with apt-get.

**Comment by ScottTodd** [comment]
Also seeing this on Windows:

```
DEBUG: C:/users/scotttodd/_bazel_scotttodd/eop7y4q7/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
```

lines to change: https://github.com/google/iree/blob/dacda264b40e76429c0adfba109174364304d431/WORKSPACE#L46-L58

Will probably require some testing on Windows and Linux (with/without RBE) to make sure builds still work.

**Comment by ScottTodd** [comment]
Kokoro VMs have been updated to Bazel 2.1.0 as well:

```
[20:11:42 UTC] bazel --version
bazel 2.1.0
```

**Pull request closed without merging**
