### PR TITLE
Fix set dynamic dim from MakeRankedShapeOp.

### PR DESCRIPTION
**Pull request by shanshanpt**
Fix set dynamic dim from MakeRankedShapeOp.

### CODE REVIEW

**Comment by asaadaldien** [comment]
LGTM! Thanks @shanshanpt. Can you add a test in iree/compiler/Conversion/LinalgToLLVM/test/convert_to_llvm.mlir

**Review by asaadaldien — APPROVED** [review]

**Comment by shanshanpt** [comment]
> LGTM! Thanks @shanshanpt. Can you add a test in iree/compiler/Conversion/LinalgToLLVM/test/convert_to_llvm.mlir

ok

**Review by stellaraccident — APPROVED** [review]

**Comment by stellaraccident** [comment]
> > LGTM! Thanks @shanshanpt. Can you add a test in iree/compiler/Conversion/LinalgToLLVM/test/convert_to_llvm.mlir
> 
> ok

Went ahead and merged this before seeing the request for a test case up thread. If you could, can you send a test case separately?

**Comment by shanshanpt** [comment]
> > > LGTM! Thanks @shanshanpt. Can you add a test in iree/compiler/Conversion/LinalgToLLVM/test/convert_to_llvm.mlir
> > 
> > 
> > ok
> 
> Went ahead and merged this before seeing the request for a test case up thread. If you could, can you send a test case separately?

yes, send a new request, https://github.com/google/iree/pull/3096

**Pull request merged**
