### PR TITLE
Remove alwayslink from localfile

### PR DESCRIPTION
**Pull request by marbre**
Progress on #1637

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Unfortunately, this is necessary internally. Localfile ends up connecting to an alwayslink target. We may have to rework how this functions (maybe by just using our custom implementation everywhere).

**Comment by ScottTodd** [comment]
> Unfortunately, this is necessary internally. Localfile ends up connecting to an alwayslink target. We may have to rework how this functions (maybe by just using our custom implementation everywhere).

The underlying library is `alwayslink`, but does this wrapper library need it as well?

**Comment by GMNGeoffrey** [comment]
> > Unfortunately, this is necessary internally. Localfile ends up connecting to an alwayslink target. We may have to rework how this functions (maybe by just using our custom implementation everywhere).
> 
> The underlying library is `alwayslink`, but does this wrapper library need it as well?

Maybe I don't understand how alwayslink works :-D I thought that it needed to be used in all parts of the dependency path. I will investigate.

**Comment by ScottTodd** [comment]
> > > Unfortunately, this is necessary internally. Localfile ends up connecting to an alwayslink target. We may have to rework how this functions (maybe by just using our custom implementation everywhere).
> > 
> > 
> > The underlying library is `alwayslink`, but does this wrapper library need it as well?
> 
> Maybe I don't understand how alwayslink works :-D I thought that it needed to be used in all parts of the dependency path. I will investigate.

https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.alwayslink

> If 1, any binary that depends (directly or indirectly) on this C++ library will link in all the object files for the files listed in srcs, even if some contain no symbols referenced by the binary. 

worth confirming though.

**Comment by GMNGeoffrey** [comment]
> https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.alwayslink
> 
> > If 1, any binary that depends (directly or indirectly) on this C++ library will link in all the object files for the files listed in srcs, even if some contain no symbols referenced by the binary.
> 
> worth confirming though.

Oh nice! I'll do some testing to confirm, but that looks pretty clear. There are likely some other places in the repo where my misunderstanding of alwayslink has caused it to be used unnecessarily :-)

**Comment by GMNGeoffrey** [comment]
Yup this works fine, I'm wrong :-)

**Pull request closed without merging**
