### PR TITLE
Include relevant MLIR dialects direclty when used

### PR DESCRIPTION
**Pull request by ftynse**
https://github.com/llvm/llvm-project/commit/eda6f907d2581a956aec511ae1d13adc3f97d3ad
removes several #includes from dialect headers, in particular for the
Arithmetic and Affine dialects. These dialects now must be included
explicitly in files where they were hitherto included transitively.

### CODE REVIEW

**Comment by ftynse** [comment]
This may require bazel changes to add header visibility...

**Comment by stellaraccident** [comment]
Thank you for the cleanup! It looks like there are some bazel strict deps missing, so we should add those and then run bazel_to_cmake.

One of us in the US timezone can push a patch to your branch and land this if you don't get to it before signing off.

**Review by stellaraccident — APPROVED** [review]

**Comment by stellaraccident** [comment]
Thanks! Landed.

**Comment by GMNGeoffrey** [comment]
Thanks for this fix Alex!

**Pull request merged**
