### PR TITLE
Add lint action for PR title length

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
This enforces some basic restrictions on PR titles as good commit titles.

Tested: https://github.com/google/iree/pull/2481/checks?check_run_id=859804845 gave a nice failure

### CODE REVIEW

**Comment by benvanik** [comment]
Hmm yeah, this will be annoying if it's blocking. Too much tooling can be a bad thing.

**Comment by ScottTodd** [comment]
> Hmm yeah, this will be annoying if it's blocking. Too much tooling can be a bad thing.

I think none of our checks are blocking on GitHub [yet]. It will show up as a red error on the PR/commit though.

**Comment by GMNGeoffrey** [comment]
> > Hmm yeah, this will be annoying if it's blocking. Too much tooling can be a bad thing.
> 
> I think none of our checks are blocking on GitHub [yet]. It will show up as a red error on the PR/commit though.

The only thing that's blocking is the CLA check.

**Comment by benvanik** [comment]
Yeah, this is super annoying. Going to revert.

**Comment by GMNGeoffrey** [comment]
> Yeah, this is super annoying. Going to revert.

Can you go into a bit more detail rather than just pushing a revert directly to `main` without a PR or review? Given that this is a non-blocking check, I don't think there's really anything that would warrant that level of urgency.

So to have that discussion:

The goal of this check is to encourage (in a non-blocking way) commit titles that follow established conventions (e.g. https://chris.beams.io/posts/git-commit/) which are also followed by our sister projects (https://mlir.llvm.org/getting_started/DeveloperGuide/#style-guide). Limited-length commit titles make it easier to scan history and a lot of tooling (ours and others') will automatically truncate messages and those longer than a certain cutoff will just get split: e.g. https://github.com/google/iree/commit/3c8954c6358ff0ac848cda42e1f1266c7268e53e looks crap in the GitHub history, or in https://github.com/google/iree/pull/2504, one of these things is not like the others. Like obviously this is not the most important thing in the world, but have you considered just trying to write shorter summaries?

**Comment by GMNGeoffrey** [comment]
> We should have ASAN, and a Windows bot, and clang-tidy, etc. Not this.

Yeah I'm working on those too. Except for the Windows bot since I don't have a Windows computer to test on and doing that without local verification is hard. We have a goal for getting a windows bot, but no one who actually develops on Windows has volunteered to create it. You are welcome to. It's not like somehow adding this prevented adding an asan bot. I did it in a few minutes because I was bored on the weekend and tired of seeing shit in our history.

> (the time for discussion was on the PR, which you didn't respond to my comment and just merged, so...)

I literally did. You said it would be annoying if it's blocking. I said it's not blocking. And then I still waited to merge till the end of the day to see if you had more comments, but you didn't respond any further. Since the only concern you had expressed would be that this was blocking, I proceeded.

**Comment by benvanik** [comment]
Hmm I think you're projecting; I was referring to _useful_ checks, not who would implement said checks.

Regardless, as an example the amount of time spent writing these words between us and me dealing with this last night has exceeded any hypothetical time savings such a check would have ever had. That's the sign of something that is noise and a net neutral to negative to project health.

**Pull request merged**
