### PR TITLE
bump tracy

### PR DESCRIPTION
**Pull request by bjacob**
- Tracy has received substantial Android-facing changes. It's good to be in sync with upstream on this as we're about to use Tracy a lot on Android.
- The Tracy revision that we were on had an issue that manifested itself as an assert failure [here](https://github.com/wolfpld/tracy/blob/058e89011fceca912d43638ebb6b85992147fcfe/server/TracyWorker.cpp#L5961). It sounded potentially bad for profile accuracy, as a timestamp was off by a large amount. The [current Tracy code](https://github.com/wolfpld/tracy/blob/6b340b37004eb49fc3649914efb0357ecbb657a4/server/TracyWorker.cpp#L6402-L6441) looks very different and there isn't any assertion failure anymore.
- We hadn't updated in 6 months and there are visible improvements. At least here on linux, the sampling asm-annotation view displays more useful information and has fixed a graphical glitch where the branch/jump indicators used to be painted over instructions mnemonics.

### CODE REVIEW

**Comment by ScottTodd** [comment]
Do we want this to supersede https://github.com/google/iree/pull/8544?

**Comment by bjacob** [comment]
Ah I didn't realize that I needed to also regenerate prebuild `capture` binaries and update this yaml file.

I think that we should first land the present PR (#8629). Then update #8544 to drop the submodule bump part and keep only the yaml file update, and make it use this new revision.

A segfault is mentioned in the discussion on #8544. I just [fixed](https://github.com/wolfpld/tracy/pull/347) a segfault in newer revisions of Tracy, so that might be the same / that issue might be gone in the new Tracy revision being referenced here.

**Comment by antiagainst** [comment]
So the segfault in #8544 is potentially fixed? That's cool! Let me help to regenerate an `capture` binary for this specific commit then.

> EDIT: oh wait, we have to do both updates in one shot because the Tracy wire format got a breaking change.

Yes it needs to match.

**Comment by bjacob** [comment]
Potentially fixed, yes. The logs really don't seem to say anything more than "there was a segfault", but what I know is that when I locally bumped the tracy version, I ran into a segfault at first, and that fix mentioned in the previous comment fixes it and it now runs well for me (on linux).

**Comment by antiagainst** [comment]
Updated and triggered a benchmark run. Let's see whether it's good now.

**Review by antiagainst — APPROVED** [review]

**Comment by bjacob** [comment]
Woohoo, thanks @antiagainst for finishing the PR and triggering the benchmarks. Teamwork! I can see the buildkit runs are all green, whereas they weren't in #8544, so I assume that means OK to merge.

**Pull request merged**
