### PR TITLE
Switching from mhlo::ConvertOp to ZeroExtendI for i1->i8 conversion.

### PR DESCRIPTION
**Pull request by benvanik**

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]
Seems like this was needed. Let me try to fix this upstream. Hopefully a quick fix. Ill approve this for now, but if you can wait a day or so, ill fix it upstream.

**Comment by benvanik** [comment]
> Seems like this was needed. Let me try to fix this upstream. Hopefully a quick fix. Ill approve this for now, but if you can wait a day or so, ill fix it upstream.

Fix what in particular upstream? This is currently used on both old and new paths (so for VMLA for example too), and the behavior (widening i1 to i8) may be IREE-specific.

Of course, I'd love to fix our i1 handling in general - but that is larger work I don't want to tackle until we eject the old path :)

**Comment by MaheshRavishankar** [comment]
Related to this https://github.com/google/iree/issues/5115

**Comment by benvanik** [comment]
> Related to this #5115

ah - gotcha - yes this as-is will create additional dispatch regions. I can wait to submit.

**Comment by MaheshRavishankar** [comment]
> > Related to this #5115
> 
> ah - gotcha - yes this as-is will create additional dispatch regions. I can wait to submit.

If fixing fusion automatically will avoid creating the dispatch region, then there is no need to wait. Once it is fixed upstream it should just get enabled by default.

**Pull request merged**
