### PR TITLE
base:internal:math: Fix f32 to f16 overflow/underflow 

### PR DESCRIPTION
**Pull request by hcindyl**

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by hcindyl** [comment]
actually, I noticed we don't have a test for this function (why we never catch the dead path). I will add the test as well.

**Comment by hcindyl** [comment]
> actually, I noticed we don't have a test for this function (why we never catch the dead path). I will add the test as well.

Don't realize how broken it can be until we have the tests :p

**Comment by hcindyl** [comment]
@benvanik Could you please take a look at the unit tests?

**Review by benvanik — APPROVED** [review]

**Comment by hcindyl** [comment]
Thanks!

**Pull request merged**
