### PR TITLE
[Cleanup] Delete uneeded restriction on EntryPoints in CPU pipeline.

### PR DESCRIPTION
**Pull request by hanhanW**
One executable should contain exactly one entry point.

### CODE REVIEW

**Comment by benvanik** [comment]
no no it shouldn't contain only one - it's a bug that it only can

**Comment by benvanik** [comment]
(if it could contain only one then there would be no need for the executable at all - the intent is that it can have any number of them)

**Comment by hanhanW** [comment]
I probably used wrong term. So one `ExecutableVariantOp` can have multiple ExecutableEntryPointOp ops?

**Comment by benvanik** [comment]
Yep - executables are containers for any number of entry points - we perform linking very late today because of this issue - if codegen supported executables with multiple entry points we'd link before it (right after flow dispatch region outlining)

**Comment by hanhanW** [comment]
I see, thanks for the explanation!

**Pull request closed without merging**
