### PR TITLE
Changes to make iree build with cmake with vm2 and llvm mono-repo -- Fork

### LINKED ISSUE #365: CMake build issues with 3.12: target already exists
The GitHub cmake action uses cmake 3.12, which is having some strange issues that are not present with 3.13

Some earlier discussion in https://github.com/google/iree/pull/354

```
CMake Error at third_party/benchmark/src/CMakeLists.txt:20 (add_library):
  add_library cannot create target "benchmark" because another target with
  the same name already exists.  The existing target is a static library
  created in source directory
  "/usr/local/google/home/gcmn/git/iree-fork/third_party/llvm-project/llvm/utils/benchmark/src".
  See documentation for policy CMP0002 for more details.


CMake Error at third_party/benchmark/src/CMakeLists.txt:31 (target_link_libraries):
  Attempt to add link library "-pthread" to target "benchmark" which is not
  built in this directory.


CMake Error at third_party/benchmark/src/CMakeLists.txt:34 (target_link_libraries):
  Attempt to add link library "/usr/lib/x86_64-linux-gnu/librt.so" to target
  "benchmark" which is not built in this directory.


CMake Error at third_party/benchmark/src/CMakeLists.txt:56 (add_library):
  add_library cannot create target "benchmark_main" because another target
  with the same name already exists.  The existing target is a static library
  created in source directory
  "/usr/local/google/home/gcmn/git/iree-fork/third_party/llvm-project/llvm/utils/benchmark/src".
  See documentation for policy CMP0002 for more details.
```

### PR DESCRIPTION
**Pull request by marbre**
Closes #365.

### CODE REVIEW

**Comment by marbre** [comment]
As mentioned in #354, it seems that some variables were not propagated correctly to LLVM. Forcing CMake to set the values solves the problem. With my first success on `LLVM_ENABLE_PROJECTS`, I decided to just set force all other LLVM related values. In consequence tests and benchmarks are now really disabled and thus the duplicate targets disappeared. The build pipeline is still running, but at minimum the CMake configure step succeeded.

**Comment by marbre** [comment]
@GMNGeoffrey Got it working! :-D

**Comment by GMNGeoffrey** [comment]
Awesome! Thank you for figuring this out. I was really focused on why this was different between versions and didn't look closely enough at solving for the actual error message

**Comment by GMNGeoffrey** [comment]
We're going to need to make the submodule changes in a different PR (@stellaraccident has figured out a way to simplify this process in the future, but not there yet), but other than that, this LGTM.

Out of curiosity, do you know why this behavior changes between versions? I'm still not seeing anything in the release notes that looks right. CMP0077 is something about changing the caching behavior of options, which could maybe it (I have read the docs entry for it 10 times and still don't understand what it means), but I tried setting it to OLD behavior and the build still doesn't hit that error with cmake 3.13

**Comment by GMNGeoffrey** [comment]
My vote would be to do this in 3 PRs:
1. Update the LLVM and TF submodules.
2. Everything else.
3. Delete the MLIR submodule.

**Comment by GMNGeoffrey** [comment]
Send https://github.com/google/iree/pull/376 for step 1

**Comment by stellaraccident** [comment]
Ok, I think I landed this into master. I did a test build with the compiler off and it succeeded (I also noticed in one run some non-determinism that may signal a missing flatbuffer dep). Can look more in detail later.

**Pull request closed without merging**
