### PR TITLE
Integrate llvm-project and bump dependencies.

### PR DESCRIPTION
**Pull request by ThomasRaoux**
* llvm-project: 7c65d2288bfd03ca3c3e829c7746b5e4e495357f
* mlir-hlo: a2c37922d79b4204e690c4815f92363de1ae0739
* tensorflow: e4c2068ee960f1f3a886af89a17c74b9b2c477c8

Update StandardToSPIRV uses

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by ThomasRaoux** [comment]
@antiagainst can you take a look since most of the updates are around convert to SPIRV, just want to make sure I did it right

**Comment by MaheshRavishankar** [comment]
I was keeping track of this change. Changes here is what I would expect.

**Comment by ThomasRaoux** [comment]
> I was keeping track of this change. Changes here is what I would expect.

Thanks Mahesh!

**Comment by ThomasRaoux** [comment]
I'll merge if it is green but just want to make sure it stays on Lei's radar in case there are opportunities for cleanup

**Review by hanhanW — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
@hanhanW do you want to look at the changes to `linalg_ext` tests. The FFT changes look interesting. They look fine to me, but I am surprised by it. So would be good to get some eyes on it.

**Comment by ThomasRaoux** [comment]
> @hanhanW do you want to look at the changes to `linalg_ext` tests. The FFT changes look interesting. They look fine to me, but I am surprised by it. So would be good to get some eyes on it.

it seems like it is just some new folding that requires tests updates

**Comment by hanhanW** [comment]
> @hanhanW do you want to look at the changes to `linalg_ext` tests. The FFT changes look interesting. They look fine to me, but I am surprised by it. So would be good to get some eyes on it.

I guess there are some canonicalization patterns kicked in which folds some constant computation into `coeff` and move it out of the loop. Overall looks good to me.

**Comment by MaheshRavishankar** [comment]
> > @hanhanW do you want to look at the changes to `linalg_ext` tests. The FFT changes look interesting. They look fine to me, but I am surprised by it. So would be good to get some eyes on it.
> 
> it seems like it is just some new folding that requires tests updates

Yes I think so, but it is doing it across loops, which is fancy! Does seem right to me though.

**Review by antiagainst — APPROVED** [review]

**Comment by antiagainst** [comment]
Another round, you are so productive, Thomas. :D Thanks for it!

**Pull request merged**
