### PR TITLE
[NFC] Adopt SymbolOpInterface set[Public/Private/Nested] methods

### PR DESCRIPTION
**Pull request by jurahul**

### CODE REVIEW

**Comment by jurahul** [comment]
@ThomasRaoux @GMNGeoffrey, please review and approve.

**Comment by GMNGeoffrey** [comment]
This PR is against the google branch. What is your intent here? Does this need to be merged into google3? Or are you trying to merge this into upstream IREE?

**Comment by GMNGeoffrey** [comment]
Oh wait. No it's against the `test_342344398` branch. My question remains :-D

**Comment by GMNGeoffrey** [comment]
The actual commit LGTM though. I'm guessing you want this merged into the IREE main branch? I can do that for you

**Review by GMNGeoffrey — CHANGES_REQUESTED** [review]
Please clarify where you want this merged.

**Comment by jurahul** [comment]
Yes, I think I want it merged in the "main" branch.  If you can do that, it would be great.

**Comment by jurahul** [comment]
The same place my previous changes have gone to...

**Review by GMNGeoffrey — APPROVED** [review]

**Comment by jurahul** [comment]
Thanks!

**Comment by GMNGeoffrey** [comment]
FYI, for future reference, I think it selected the other branch because the names matched.

**Pull request merged**
