### PR TITLE
Rename main source files used directly in cc binaries

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
These naming diffs are frequently confusing, I find. This consistently
names the file after the primary binary in which it is used (if
applicable) suffixed with `main.cc` separated with a dash or an
underscore depending on what is used in that binary.

This is also motivated by absl flags behavior. Absl uses the name of
the binary to determine which flags to include in `--help` by default:
those from source files whose basename match the binary name with an
optional (`-main` or `_main` suffix) get included.

We do have the option of customizing the absl behavior instead if we 
have strong feelings about alternative naming schemes.

Part of https://github.com/google/iree/issues/3247

### CODE REVIEW

**Comment by benvanik** [comment]
I'm ok with this, but this is not the same behavior as in google3, where most main files are `foo_main.cc`. Do you suspect there's different behavior in abseil than vs internal, or that there's other magic happening that's masking it?

**Comment by GMNGeoffrey** [comment]
> I'm ok with this, but this is not the same behavior as in google3, where most main files are `foo_main.cc`. Do you suspect there's different behavior in abseil than vs internal, or that there's other magic happening that's masking it?

The naming was an informed guess, but I've now actually tracked down the code and it does have [some normalization](https://github.com/abseil/abseil-cpp/blob/master/absl/flags/usage_config.cc#L51), so we can use dashes or underscores and probably have an optional main suffix, but dropping the "iree" prefix is what's messing things up. Want to leave the main suffix and underscores, e.g. `iree_run_module_main.cc`?

**Comment by benvanik** [comment]
iree_run_module_main SGTM (at least, that feels warm and fuzzy and familiar :)

**Comment by GMNGeoffrey** [comment]
> iree_run_module_main SGTM (at least, that feels warm and fuzzy and familiar :)

Familiar is a pretty strong argument for this sort of thing IMO :-D I'll switch to that

**Comment by benvanik** [comment]
image

**Review by benvanik — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
Oh wait, I misread slightly. The dashes vs underscores do matter. Our options are:

`<program>.cc`
`<program>-main.cc`
`<program>_main.cc`

**Comment by benvanik** [comment]
ugh, lame! Well, the advantage of _main is that it's easy to search for and easy to distinguish from library files, but since all our binaries have dashes and iree- as a prefix that's pretty easy to find as well. So I'm fine with either iree-run-foo.cc or iree-run-foo-main.cc.

**Comment by GMNGeoffrey** [comment]
> ugh, lame! Well, the advantage of _main is that it's easy to search for and easy to distinguish from library files, but since all our binaries have dashes and iree- as a prefix that's pretty easy to find as well. So I'm fine with either iree-run-foo.cc or iree-run-foo-main.cc.

Oooh I just did `iree-run-foo_main.cc`. OK too?

**Comment by GMNGeoffrey** [comment]
I still feel like it's always too hard to execute "rename these files and also all references too them..."

**Comment by benvanik** [comment]
> Oooh I just did `iree-run-foo_main.cc`. OK too?

image

**Comment by benvanik** [comment]
> Oooh I just did `iree-run-foo_main.cc`. OK too?

(I already die inside at all-our_mixed-weird_things, let's not add more ;)

**Comment by GMNGeoffrey** [comment]
> > Oooh I just did `iree-run-foo_main.cc`. OK too?
> 
> (I already die inside at all-our_mixed-weird_things, let's not add more ;)

Yeah :-/ The thing is we also have `gtest_main.cc` and such. So should those now be `gtest-main.cc`? I was just going with "all files with a main function are `_main.cc`". What is our convention here? :-D

**Comment by GMNGeoffrey** [comment]
Ok now we don't mix underscore and dash and source file names use underscore or dash depending on what is used in the binary name.

**Review by benvanik — APPROVED** [review]
image


(jk jk - this is a nice cleanup as well as making the help useful thanks for doing it -- having this consistent throughout the codebase will mean that the next person going to add one of these won't have to guess :)

**Comment by GMNGeoffrey** [comment]
pingu

:-D

It gets way worse once we also involve the benchmark library's flag parsing too :-/

**Pull request merged**
