### PR TITLE
Switch : to / in more CMake tests names.

### PR DESCRIPTION
**Pull request by ScottTodd**
Follow-up to https://github.com/google/iree/commit/2e9aaa4dc0f44a18e739dba7a26f6366382a308f

### CODE REVIEW

**Review by GMNGeoffrey — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
Also fix these? https://github.com/google/iree/blob/a808f68fa95be7439f3c14a699a790f80e82098a/build_tools/cmake/iree_multipy.cmake#L307

**Review by benvanik — APPROVED** [review]

**Comment by ScottTodd** [comment]
> Also fix these?
> 
> https://github.com/google/iree/blob/a808f68fa95be7439f3c14a699a790f80e82098a/build_tools/cmake/iree_multipy.cmake#L307

Oh good catch. I had `-DIREE_BUILD_PYTHON_BINDINGS=OFF`. Uhh.. a simple `:` -> `/` replacement there crashes CMake. I'll fix tomorrow :P

**Comment by GMNGeoffrey** [comment]
> Oh good catch. I had `-DIREE_BUILD_PYTHON_BINDINGS=OFF`. Uhh.. a simple `:` -> `/` replacement there crashes CMake. I'll fix tomorrow :P

FTR I think merging this now and fixing those later is totally reasonable

**Comment by ScottTodd** [comment]
> > Oh good catch. I had `-DIREE_BUILD_PYTHON_BINDINGS=OFF`. Uhh.. a simple `:` -> `/` replacement there crashes CMake. I'll fix tomorrow :P
> 
> FTR I think merging this now and fixing those later is totally reasonable

Ok, so `-DIREE_BUILD_PYTHON_BINDINGS=ON` crashes CMake during configuration if
```
        "-DIREE_TARGET_BACKENDS_TO_BUILD=vmla;vulkan-spirv",
        "-DIREE_HAL_DRIVERS_TO_BUILD=vmla;vulkan",
```
is set, at least on my Windows machine (before and after this tweak).

Error logs:

```
[cmake] CMake Error at build_tools/cmake/iree_multipy.cmake:121 (add_library):
[rollbar] Unhandled exception: Unhandled exception: Processing "data" event from proc stderr TypeError: message must be set {"data":{"type":"Buffer","data":[67,77,97,107,101,32,69,114,114,111,114,32,97,116,32,98,117,105,108,100,95,116,111,111,108,115,47,99,109,97,107,101,47,105,114,101,101,95,109,117,108,116,105,112,121,46,99,109,97,107,101,58,49,50,49,32,40,97,100,100,95,108,105,98,114,97,114,121,41,58,10,32,32,84,97,114,103,101,116,32,34,98,105,110,100,105,110,103,115,95,112,121,116,104,111,110,95,112,121,105,114,101,101,95,99,111,109,112,105,108,101,114,95,80,121,69,120,116,67,111,109,112,105,108,101,114,95,95,68,69,70,65,85,76,84,34,32,108,105,110,107,115,32,116,111,10,32,32,116,97,114,103,101,116,32,34,105,114,101,101,58,58,99,111,109,112,105,108,101,114,58,58,68,105,97,108,101,99,116,58,58,72,65,76,58,58,84,97,114,103,101,116,58,58,76,76,86,77,58,58,65,79,84,58,58,76,76,86,77,65,79,84,34,32,98,117,116,32,116,104,101,10,32,32,116,97,114,103,101,116,32,119,97,115,32,110,111,116,32,102,111,117,110,100,46,32,32,80,101,114,104,97,112,115,32,97,32,102,105,110,100,95,112,97,99,107,97,103,101,40,41,32,99,97,108,108,32,105,115,32,109,105,115,115,105,110,103,32,102,111,114,32,97,110,10,32,32,73,77,80,79,82,84,69,68,32,116,97,114,103,101,116,44,32,111,114,32,97,110,32,65,76,73,65,83,32,116,97,114,103,101,116,32,105,115,32,109,105,115,115,105,110,103,63,10,67,97,108,108,32,83,116,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,102,105,114,115,116,41,58,10,32,32,98,105,110,100,105,110,103,115,47,112,121,116,104,111,110,47,112,121,105,114,101,101,47,99,111,109,112,105,108,101,114,47,67,77,97,107,101,76,105,115,116,115,46,116,120,116,58,50,52,32,40,105,114,101,101,95,112,121,101,120,116,95,109,111,100,117,108,101,41,10,10,10]},"command":"C:\\Program Files\\CMake\\bin\\cmake.exe","args":["--no-warn-unused-cli","-DIREE_TARGET_BACKENDS_TO_BUILD=vmla;vulkan-spirv","-DIREE_HAL_DRIVERS_TO_BUILD=vmla;vulkan","-DIREE_BUILD_PYTHON_BINDINGS=ON","-DIREE_BUILD_SAMPLES=ON","-DIREE_ENABLE_RUNTIME_TRACING=ON","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-DCMAKE_BUILD_TYPE:STRING=Debug","-Hd:/dev/projects/iree","-Bd:/dev/projects/iree-build","-G","Ninja"]}
[cmake] CMake Error at build_tools/cmake/iree_multipy.cmake:121 (add_library):CMake Error at build_tools/cmake/iree_multipy.cmake:121 (add_library):
[rollbar] Unhandled exception: Unhandled exception: Processing "data" event from proc stderr TypeError: message must be set {"data":{"type":"Buffer","data":[67,77,97,107,101,32,69,114,114,111,114,32,97,116,32,98,117,105,108,100,95,116,111,111,108,115,47,99,109,97,107,101,47,105,114,101,101,95,109,117,108,116,105,112,121,46,99,109,97,107,101,58,49,50,49,32,40,97,100,100,95,108,105,98,114,97,114,121,41,58,10,32,32,84,97,114,103,101,116,32,34,98,105,110,100,105,110,103,115,95,112,121,116,104,111,110,95,112,121,105,114,101,101,95,99,111,109,112,105,108,101,114,95,80,121,69,120,116,67,111,109,112,105,108,101,114,95,95,68,69,70,65,85,76,84,34,32,108,105,110,107,115,32,116,111,10,32,32,116,97,114,103,101,116,32,34,105,114,101,101,58,58,99,111,109,112,105,108,101,114,58,58,68,105,97,108,101,99,116,58,58,72,65,76,58,58,84,97,114,103,101,116,58,58,76,76,86,77,58,58,73,82,58,58,76,76,86,77,73,82,34,32,98,117,116,32,116,104,101,10,32,32,116,97,114,103,101,116,32,119,97,115,32,110,111,116,32,102,111,117,110,100,46,32,32,80,101,114,104,97,112,115,32,97,32,102,105,110,100,95,112,97,99,107,97,103,101,40,41,32,99,97,108,108,32,105,115,32,109,105,115,115,105,110,103,32,102,111,114,32,97,110,10,32,32,73,77,80,79,82,84,69,68,32,116,97,114,103,101,116,44,32,111,114,32,97,110,32,65,76,73,65,83,32,116,97,114,103,101,116,32,105,115,32,109,105,115,115,105,110,103,63,10,67,97,108,108,32,83,116,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,102,105,114,115,116,41,58,10,32,32,98,105,110,100,105,110,103,115,47,112,121,116,104,111,110,47,112,121,105,114,101,101,47,99,111,109,112,105,108,101,114,47,67,77,97,107,101,76,105,115,116,115,46,116,120,116,58,50,52,32,40,105,114,101,101,95,112,121,101,120,116,95,109,111,100,117,108,101,41,10,10,10,67,77,97,107,101,32,69,114,114,111,114,32,97,116,32,98,117,105,108,100,95,116,111,111,108,115,47,99,109,97,107,101,47,105,114,101,101,95,109,117,108,116,105,112,121,46,99,109,97,107,101,58,49,56,57,32,40,97,100,100,95,108,105,98,114,97,114,121,41,58,10,32,32,84,97,114,103,101,116,32,34,98,105,110,100,105,110,103,115,95,112,121,116,104,111,110,95,112,121,105,114,101,101,95,99,111,109,112,105,108,101,114,95,80,121,69,120,116,67,111,109,112,105,108,101,114,76,105,98,95,95,68,69,70,65,85,76,84,34,32,108,105,110,107,115,32,116,111,10,32,32,116,97,114,103,101,116,32,34,105,114,101,101,58,58,99,111,109,112,105,108,101,114,58,58,68,105,97,108,101,99,116,58,58,72,65,76,58,58,84,97,114,103,101,116,58,58,76,76,86,77,58,58,65,79,84,58,58,76,76,86,77,65,79,84,34,32,98,117,116,32,116,104,101,10,32,32,116,97,114,103,101,116,32,119,97,115,32,110,111,116,32,102,111,117,110,100,46,32,32,80,101,114,104,97,112,115,32,97,32,102,105,110,100,95,112,97,99,107,97,103,101,40,41,32,99,97,108,108,32,105,115,32,109,105,115,115,105,110,103,32,102,111,114,32,97,110,10,32,32,73,77,80,79,82,84,69,68,32,116,97,114,103,101,116,44,32,111,114,32,97,110,32,65,76,73,65,83,32,116,97,114,103,101,116,32,105,115,32,109,105,115,115,105,110,103,63,10,67,97,108,108,32,83,116,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,102,105,114,115,116,41,58,10,32,32,98,105,110,100,105,110,103,115,47,112,121,116,104,111,110,47,112,121,105,114,101,101,47,99,111,109,112,105,108,101,114,47,67,77,97,107,101,76,105,115,116,115,46,116,120,116,58,51,56,32,40,105,114,101,101,95,112,121,101,120,116,95,108,105,98,114,97,114,121,41,10,10,10,67,77,97,107,101,32,69,114,114,111,114,32,97,116,32,98,117,105,108,100,95,116,111,111,108,115,47,99,109,97,107,101,47,105,114,101,101,95,109,117,108,116,105,112,121,46,99,109,97,107,101,58,49,56,57,32,40,97,100,100,95,108,105,98,114,97,114,121,41,58,10,32,32,84,97,114,103,101,116,32,34,98,105,110,100,105,110,103,115,95,112,121,116,104,111,110,95,112,121,105,114,101,101,95,99,111,109,112,105,108,101,114,95,80,121,69,120,116,67,111,109,112,105,108,101,114,76,105,98,95,95,68,69,70,65,85,76,84,34,32,108,105,110,107,115,32,116,111,10,32,32,116,97,114,103,101,116,32,34,105,114,101,101,58,58,99,111,109,112,105,108,101,114,58,58,68,105,97,108,101,99,116,58,58,72,65,76,58,58,84,97,114,103,101,116,58,58,76,76,86,77,58,58,73,82,58,58,76,76,86,77,73,82,34,32,98,117,116,32,116,104,101,10,32,32,116,97,114,103,101,116,32,119,97,115,32,110,111,116,32,102,111,117,110,100,46,32,32,80,101,114,104,97,112,115,32,97,32,102,105,110,100,95,112,97,99,107,97,103,101,40,41,32,99,97,108,108,32,105,115,32,109,105,115,115,105,110,103,32,102,111,114,32,97,110,10,32,32,73,77,80,79,82,84,69,68,32,116,97,114,103,101,116,44,32,111,114,32,97,110,32,65,76,73,65,83,32,116,97,114,103,101,116,32,105,115,32,109,105,115,115,105,110,103,63,10,67,97,108,108,32,83,116,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,102,105,114,115,116,41,58,10,32,32,98,105,110,100,105,110,103,115,47,112,121,116,104,111,110,47,112,121,105,114,101,101,47,99,111,109,112,105,108,101,114,47,67,77,97,107,101,76,105,115,116,115,46,116,120,116,58,51,56,32,40,105,114,101,101,95,112,121,101,120,116,95,108,105,98,114,97,114,121,41,10,10,10]},"command":"C:\\Program Files\\CMake\\bin\\cmake.exe","args":["--no-warn-unused-cli","-DIREE_TARGET_BACKENDS_TO_BUILD=vmla;vulkan-spirv","-DIREE_HAL_DRIVERS_TO_BUILD=vmla;vulkan","-DIREE_BUILD_PYTHON_BINDINGS=ON","-DIREE_BUILD_SAMPLES=ON","-DIREE_ENABLE_RUNTIME_TRACING=ON","-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE","-DCMAKE_BUILD_TYPE:STRING=Debug","-Hd:/dev/projects/iree","-Bd:/dev/projects/iree-build","-G","Ninja"]}
```

It still works if I use

```
        "-DIREE_TARGET_BACKENDS_TO_BUILD=all",
        "-DIREE_HAL_DRIVERS_TO_BUILD=all",
```

**Pull request merged**
