### PR TITLE
Adapt iree/compiler to the reordered mmt4d dimensions

### PR DESCRIPTION
**Pull request by bjacob**

### CODE REVIEW

**Comment by bjacob** [comment]
I added @GMNGeoffrey because there's an infra aspect here: this is adapting to a breaking change in `third_party/llvm-project`. For now I've pushed my local branch as-is including my commit updating the `third_party/llvm-project` repo reference bump. Once the LLVM commit is merged upstream ( https://reviews.llvm.org/D109692 ), we should be able to drop that aspect and land this PR on the "integrate" branch, right ?

**Comment by GMNGeoffrey** [comment]
Will IREE break if LLVM is updated without this? In that case you need to send a patch internally to be included as part of LLVM being updated. I can send you the details directly

**Comment by MaheshRavishankar** [comment]
> I added @GMNGeoffrey because there's an infra aspect here: this is adapting to a breaking change in `third_party/llvm-project`. For now I've pushed my local branch as-is including my commit updating the `third_party/llvm-project` repo reference bump. Once the LLVM commit is merged upstream ( [reviews.llvm.org/D109692](https://reviews.llvm.org/D109692) ), we should be able to drop that aspect and land this PR on the "integrate" branch, right ?

That is not the workflow. You need to land your LLVM patch. That will make it into Googles code base when the entire LLVM changes are pulled in. At that point this change is available on the `google` branch of IREE. Then there is a merge from `google` -> `main` that will be done by the IREE build cop. At that point the change is available in `main` and you can land this change.

**Comment by bjacob** [comment]
Thanks for your comments! @GMNGeoffrey help me 1:1.
I have put the present changes in cl/396406856 .
My understanding is I'm waiting on you to grant review on https://reviews.llvm.org/D109692 , then it will appear on  the integrate dashboard, and I'll be able to reference the above CL there?

**Pull request closed without merging**
