### PR TITLE
Add MLIRLoopOpsTransforms dep to bindings::python::pyiree::compilter::compiler_library

### PR DESCRIPTION
**Pull request by marbre**
Take over from dacda264b

### CODE REVIEW

**Comment by marbre** [comment]
@GMNGeoffrey Follow up to our discussion on C4ML, it seems I am no longer able to add/request a reviewer.

**Comment by ScottTodd** [comment]
https://github.blog/changelog/2020-02-19-repository-access-management-beta/ looks like there are some new settings relating to repository management and permissions. See also https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review .

**Comment by GMNGeoffrey** [comment]
Huh that's annoying. From Scott's links it looks like we might also be able to add the ability to request you as a reviewer by giving you explicit read access to the repository (seems a bit weird since everyone has read access already AFAIU). But it looks like you now have to have Triage access to request a review "Organization members with triage permissions to a repository can assign a pull request review." You were previously able to request review, right?

**Comment by marbre** [comment]
It actually seems I would required write access:

```
Note: Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.
```

**Pull request closed without merging**
