### PR TITLE
Consistently use two dashes for long command line options.

### PR DESCRIPTION
**Pull request by ScottTodd**
This updates our usage of command line flags we control (MLIR flags and IREE flags) to use two dashes for long options. Short options (e.g. `-o module.vmfb`) and options for tools outside our control (e.g. `-fsanitize=address`) remain unchanged.

This is part of addressing a source of confusion explained in https://github.com/google/iree/issues/5931. Several of our tools have bad failure modes when receiving malformed flags (typos, extra spaces, overlooking implicit stdin, etc.). We can reduce the risk of user errors by being consistent across the project in how we use command line flags.

---

⚠ Bikeshedding ahead ⚠

### Rationale

In general (across tools, languages, and platforms), command line tools use a mix of _positional_ arguments and _keyword_ arguments. Positional arguments use no prefix like `-` or `--` and are parsed in the order they appear. Keyword arguments use some prefix (typically `-` or `--`) followed by the flag name then a separator (typically `=` or ` `) and then the value.

Within keyword arguments, there are also "short" and "long" options. Short options are usually one letter versions of long options, and sometimes multiple short options can be mixed together. For example, see https://man7.org/linux/man-pages/man1/tar.1.html and equivalent commands like
* `tar --create --verbose --file etc.tar /etc`
* `tar -c -v -f etc.tar /etc`
* `tar -cvf etc.tar /etc`

Not all tools follow that convention, and parsing can be made to be more forgiving, but internal consistency within a project is worth aiming for.

Other discussions:

* [What's the difference betwen the single dash and double dash flags on shell commands?](https://serverfault.com/questions/387935/whats-the-difference-betwen-the-single-dash-and-double-dash-flags-on-shell-comm)
* [What's the difference between one-dash and two-dashes for command prompt parameters?](https://superuser.com/questions/372203/whats-the-difference-between-one-dash-and-two-dashes-for-command-prompt-paramet)

---

This change was generated via a mix of regex find/replaces and manual review. See each commit for more details.

### CODE REVIEW

**Comment by ScottTodd** [comment]
Not sure what to do about the code owners reviewer recommendations here :)

How about if anyone has a particularly strong opinion one way or another, they make that known? I could also prune this change to only touch documentation files, exclude .mlir files, etc.

**Comment by MaheshRavishankar** [comment]
I don't have a strong opinion here. If you want me to stamp, I am happy to 😀

**Comment by hanhanW** [comment]
> I don't have a strong opinion here. If you want me to stamp, I am happy to 😀

+1

**Comment by powderluv** [comment]
just want to say thank you for this. you have no idea how many times I had to try `-` `--` and positional args to get the right mix.

**Review by GMNGeoffrey — APPROVED** [review]
Well trying to review this crashes Chrome, but I'm +1 overall. I think this is the right balance: make all our usage in the repo consistently do what I would describe as "the right thing" and use two dashes for long options. Personally, I wouldn't get into the inevitable flame war caused by proposing that this change in LLVM upstream. I also wouldn't try to enforce this in IREE compiler tools because then we would error on flags coming directly from LLVM/MLIR documentation. It would probably be worth it to make IREE's own (runtime) flag parsing be strict about single vs double dashes in keeping with everything except LLVM.

**Comment by GMNGeoffrey** [comment]
> It would probably be worth it to make IREE's own (runtime) flag parsing be strict about single vs double dashes in keeping with everything except LLVM.

(I mean in a separate PR, that is)

**Comment by ScottTodd** [comment]
> Well trying to review this crashes Chrome

Reviewing one commit at a time may be easier. Each commit is basically one regex find/replace for patterns like:
* ` -some-flag=value `
* ` -some-flag `
* ` -someflag `
* `"-some-flag"`

> Personally, I wouldn't get into the inevitable flame war caused by proposing that this change in LLVM upstream.

Same :P

> It would probably be worth it to make IREE's own (runtime) flag parsing be strict about single vs double dashes in keeping with everything except LLVM.

Agreed. https://github.com/google/iree/pull/6334 was a good (related) start there.

**Comment by GMNGeoffrey** [comment]
> Reviewing one commit at a time may be easier. Each commit is basically one regex find/replace for patterns like:

The first commit crashed chrome for me :crying_cat_face: I can pull and review locally maybe if you actually want a human eyeball on this

**Comment by ScottTodd** [comment]
> > Reviewing one commit at a time may be easier. Each commit is basically one regex find/replace for patterns like:
> 
> The first commit crashed chrome for me 😿 I can pull and review locally maybe if you actually want a human eyeball on this

Ah 😆. The first commit is the most mechanical/trivial but touches tons of generated test files. Up to you - I reviewed most of the diffs as I was making the changes (to avoid false positives), so a general LGTM on the intent of the PR and a sanity check through some of the diffs should be good enough IMO.

**Review by GMNGeoffrey — APPROVED** [review]
Ok I scanned through all but the first commit. LGTM, thank you!

**Comment by ScottTodd** [comment]
Great, thanks :D

Just synced past conflicts again and then I'll plan on merging once presubmits pass (except pylint)

**Pull request merged**
