### PR TITLE
NFC: rename benchmark related directories/files/functions

### PR DESCRIPTION
**Pull request by antiagainst**
* `build_tools/android` -> `build_tools/benchmark`: the directory
  contains some Android related definitions and utilities but the
  majority of its contents are general.
* `run_benchmarks.py` -> `run_benchmarks_on_android.py`: this
  script is for Android. Make it clear.
* `get_output` -> `execute_cmd_and_get_output`: this better
  reflects the usage.

### CODE REVIEW

**Review by ScottTodd — COMMENTED** [review]
two other ideas for directory structure:

* `build_tools/benchmarks` (s to match https://github.com/google/iree/tree/main/benchmarks)
* `benchmarks/scripts/` (keeping more benchmark-related code in the one top level directory)

WDYT? Any other opinions? Maybe @GMNGeoffrey

**Comment by GMNGeoffrey** [comment]
I like `build_tools/benchmarks` to consistently use the plural and because I think keeping "utility" stuff that isn't really part of IREE itself, but rather infra for building/testing/deploying/benchmarking IREE together is appealing. I've been thinking for a bit that maybe this directory should have a slightly more expansive name (`devtools`? `infrastructure`?) and then we could also move things like the top-level `scripts/` underneath it

**Comment by antiagainst** [comment]
SGTM to use `build_tools/benchmarks` for consistency. I'd also +1 to unifying all these infrastructure-y stuff under the same umbrella. Though we should handle that together (like one pull request containing multiple related commits) to avoid in a separated (so even confusing) state.

> I like build_tools/benchmarks to consistently use the plural and because I think keeping "utility" stuff that isn't really part of IREE itself, but rather infra for building/testing/deploying/benchmarking IREE together is appealing. I've been thinking for a bit that maybe this directory should have a slightly more expansive name (devtools? infrastructure?) and then we could also move things like the top-level scripts/ underneath it

If to choose from these two, I'd +1 to devtools. :) infrastructure is so generic and different people will interpret it quite differently. 

Some more choices: `devinfra`? `devflow`? ..

**Comment by ScottTodd** [comment]
I like the sound of `devtools` 🤔 

I've also had similar thoughts around linking these together better:
* https://github.com/google/iree/tree/main/iree/samples
* https://github.com/google/iree/tree/main/colab
* https://github.com/google/iree-samples

**Review by ScottTodd — APPROVED** [review]

**Pull request merged**
