### PR TITLE
Fix memory leaks under `vm/test`

### PR DESCRIPTION
**Pull request by simon-camp**

### CODE REVIEW

**Review by GMNGeoffrey — APPROVED** [review]
Huh I wonder why these weren't caught by the asan build and listed in https://github.com/google/iree/issues/5715

**Comment by simon-camp** [comment]
These must have been introduced fairly recently, in the last two weeks or so.

**Comment by GMNGeoffrey** [comment]
Yeah but we have an asan presubmit that should be catching such things. How did you detect them?

**Comment by simon-camp** [comment]
These failed with my local asan build, but I was also surprised the bot didn't fail.

**Comment by simon-camp** [comment]
I'm using the VSCode CMake extension so this might be overly verbose :man_shrugging: 

Configure
`/usr/local/bin/cmake --no-warn-unused-cli -DIREE_HAL_DRIVERS_TO_BUILD=all -DIREE_TARGET_BACKENDS_TO_BUILD=all -DCMAKE_C_COMPILER:STRING=clang-10 -DCMAKE_CXX_COMPILER:STRING=clang++-10 -DIREE_USE_LINKER:STRING=lld-10 -DIREE_ENABLE_ASAN:STRING=ON -DIREE_ENABLE_EMITC:STRING=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -H/home/user/repos/iree -B/home/user/repos/iree/build/ASAN-NoEmitC -G Ninja`

Build
`/usr/local/bin/cmake --build /home/user/repos/iree/build/ASAN-NoEmitC --config Debug --target all -j 50 --`

**Pull request merged**
