### PR TITLE
Enable testing via CMake

### PR DESCRIPTION
**Pull request by marbre**
This forces to disable testing for the submodules

* benchmark
* flatbuffers
* glslang

Testing for the iree subdirectory is enabled in the main CMake configuration.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
This LGTM. Note that before we start actually running tests I want to examine how long this presubmit is starting to take. We usually try to keep presubmits under 10 minutes (ideally under 5) and the CMake build is now taking 20 :-/ I was thinking about checking out goma to speed things up.

**Comment by marbre** [comment]
Yeah, hopefully we can reduce build times in near future. Anyway, these changes should not increase it. `enable_testing()` just adds the ability to run `make tests` and/or to use `ctest`.

**Comment by GMNGeoffrey** [comment]
For sure. I just figured that the follow-up to this would probably be running the tests as part of the CI :-)

**Comment by marbre** [comment]
I intend to add some further tests first, but indeed, that would be the final goal :-)

**Pull request closed without merging**
