### PR TITLE
Exclude third_party/ from clang-format presubmit.

### PR DESCRIPTION
**Pull request by ScottTodd**
Should make the style check pass on https://github.com/google/iree/pull/696.

Reference: https://clang.llvm.org/docs/ClangFormatStyleOptions.html

### CODE REVIEW

**Comment by ScottTodd** [comment]
Check the reference I linked. It doesn't clearly say what the default is, but it does explain the different options. We may want to iterate on this since our style is split between LLVM and Google.

**Comment by GMNGeoffrey** [comment]
Yeah I read the reference; I was just confused because it doesn't say what the default is, but I'm pretty sure it must currently be using google style, since otherwise we would be have way more disagreements between it and the internal clang-format. Did you find that the argument was necessary to make it stop complaining? I guess it's fine to make the argument explicit. We already have a [.clang-format file](https://github.com/google/iree/blob/master/.clang-format) in the repo root that I think it's using. As noted in that file, we just use Google formatting everywhere as making it use a non-google style would be a pain because internally we don't read .clang-format files at all

**Comment by GMNGeoffrey** [comment]
Also note that despite the comment in this action, it is only formatting things that differ between the working directory and master, so the fact that the presubmit passes isn't actually an indication that something else won't complain on some future presubmit.

**Comment by ScottTodd** [comment]
Yeah, `git-clang-format` ignored the `.clang-format` file until I added `--style=file`.

If this is actually only running on files that were changed, then this could have some unintended effects on future changes, yeah. I'll keep an eye on it.

**Comment by GMNGeoffrey** [comment]
Huh then I have no idea what it's doing now... Maybe google style is just the default configured in the git repository... somehow? git-clang-format reads from the git-config, so I guess it could be coming from there?

**Pull request merged**
