### PR TITLE
Add a pass to check for expected IR before lowering to LLVM.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
So far we havent had a "real" way of checking if the IR being lowered
to LLVM is as expected. We have been relying on ad-hoc signals for
this. For example, we dont expect any stack allocations on the CPU
backend, but have been relying on VMVX not handling allocations as a
way to check this.
Adding an explicit pass that checks the IR for such things allows us
to catch performance load-bearing requirements (like there shouldnt be
any stack allocations). Note that even if these checks dont hold true
the backend still should generate correct code, so the pass is guarded
by a flag.
For now this pass only checks for non-existence of stack allocations
so it is turned on by default.

### CODE REVIEW

**Comment by benvanik** [comment]
maybe add a word to the pass name that helps to indicate when this is expected to be run in the pipeline - "check IR" doesn't make it clear if this could be run between every pass, before vectorization, after conversion to the LLVM dialect, etc. Given that it's checking memref.alloca it looks like it's an input validation thing so maybe `iree-codegen-llvm-check-input-ir`?

**Review by benvanik — APPROVED** [review]
lgtm besides maybe an extra word in the name :)

**Comment by MaheshRavishankar** [comment]
> lgtm besides maybe an extra word in the name :)

You are asking me to name things better. The only way I know to do that is to make things more verbose, so thats what I did.

**Comment by benvanik** [comment]
haha I love it, thanks! would rather have a few extra chars than ambiguity :P

**Comment by benvanik** [comment]
🤞 as long as it doesn't hit the windows max path ;P

**Pull request merged**
