### PR TITLE
CMake: Improve support to build python bindings

### PR DESCRIPTION
**Pull request by marbre**
* Refactors `iree_pybind_cc_library()`
* Adds `iree_py_extension()`
* Updates and CMake targets for python bindings

The bindings are still not complete and currently only implements support for Linux.

Depends on #693 and #694. I will drop these commits and rebase if these patches get merged separately into master.

### CODE REVIEW

**Comment by marbre** [comment]
I am gladly awaiting your feedback :) We might need an iteration before this can be merged, but I hope it is the right step to enable building the python bindings with CMake.

**Comment by stellaraccident** [comment]
Looking now...

**Comment by GMNGeoffrey** [comment]
This broke the cmake build. To run kokoro on PRs and ensure we avoid a breakage, a repository collaborator needs to tag the PR with "kokoro:run"

**Comment by stellaraccident** [comment]
TIL

Ok - sorry about that. I assumed the presubmits were authoritative...

**Comment by GMNGeoffrey** [comment]
Yeah it's not a great situation :-/ They are somewhat authoritative, but we have to give them permission to run for contributions from outside the organization and nothing blocks on them on import. That's why I wanted to use GitHub required checks because it gives you a nice UI that indicates "hey this isn't ready to merge", but unfortunately it breaks copybara's ability to push directly to master.

**Comment by ScottTodd** [comment]
CI build fix is at https://github.com/google/iree/pull/700. We also discussed ways to make "this hasn't run presubmits yet" blocking or more obvious, but don't yet have a concrete plan.

**Comment by marbre** [comment]
My apologies. I probably have missed to do a full rebuild and only checked if the incremental build succeeds. Will send a patch to fix the bindings.

**Pull request closed without merging**
