### PR TITLE
Restore Vulkan graphics sample, now using VM2 APIs.

### PR DESCRIPTION
**Pull request by ScottTodd**
Contributes to work tracked in https://github.com/google/iree/issues/325.
The CMake build is blocked on https://github.com/google/iree/issues/496.
Only runs on Linux, though it shouldn't take much to get it running on Windows also.

### CODE REVIEW

**Comment by benvanik** [comment]
I kind of liked samples/vulkan/ as a folder for the various samples. agree that integration is pretty ambiguous though; maybe vulkan_inference_gui.cc? (I hope many of the other examples won't be GUI based so we can run them headlessly, so I feel it's worth calling out this one has a pretty UI/is interactive)

**Comment by ScottTodd** [comment]
SGTM. Renamed to `samples/vulkan/vulkan_inference_gui.cc`.

**Comment by ScottTodd** [comment]
Tested on Windows (fails there at the moment, can fix in this PR or later) and updated the PR description.

**Comment by ScottTodd** [comment]
Moving error logs from the PR description to a comment:

Currently logs some Vulkan errors at runtime (I might be using buffers incorrectly?):

> `E iree/hal/vulkan/debug_reporter.cc:40] vkCmdPipelineBarrier(): pMemBarriers[0].dstAccessMask (0x20) is not supported by dstStageMask (0x1). The Vulkan spec states: Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)`

Windows errors:
```
I iree/samples/vulkan/vulkan_inference_gui.cc:548] Module loaded and context is ready for use
E .\iree/base/api_util.h:30] INVALID_ARGUMENT: VK_ERROR_VALIDATION_FAILED_EXT
E .\iree/base/api_util.h:30] INVALID_ARGUMENT: while executing hal.allocator.allocate.shaped
F iree/samples/vulkan/vulkan_inference_gui.cc:675] Check failed: IREE_STATUS_OK == (iree_vm_invoke(iree_context, main_function, nullptr, input_list, output_list, { 0, iree_allocator_system_allocate, iree_allocator_system_free })) (0 vs. 3)
```

**Pull request closed without merging**
