### PR TITLE
Update LLVM and TensorFlow submodules

### PR DESCRIPTION
**Pull request by antiagainst**
./scripts/git/update_tf_llvm_submodules.py --update_build_files=true

### CODE REVIEW

**Comment by ScottTodd** [comment]
Duplicate of https://github.com/google/iree/pull/1133

**Comment by marbre** [comment]
Seems that at least the tensorflow submodule points to different commits

**Comment by antiagainst** [comment]
Yup. I updated later than Scott. So it's picking up more commits from TF.

**Comment by antiagainst** [comment]
Let me close this one in favor of #1133.

**Pull request closed without merging**
