### PR TITLE
Dropping the unused sequence dialect.

### PR DESCRIPTION
**Pull request by benvanik**
This should be done upstream, if someone desires it.

### CODE REVIEW

**Review by stellaraccident — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
What's the reference to upstream?

**Comment by benvanik** [comment]
That a frontend dialect like this should be done upstream such that we consume it vs living in the main IREE compiler - like scf or some new dialect.

**Comment by GMNGeoffrey** [comment]
Ah gotcha. I read "this" as referring to deleting it.

**Comment by benvanik** [comment]
(for anyone who sees this in the future: I do think a dialect like this would be cool upstream but here it was unfinished and unmaintained so I removed it as part of gardening :)

**Pull request merged**
