### PR TITLE
Make experimental benchmarking configurations use MMT4D

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
This allows us to monitor the progress of the MMT4D work.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Interesting. The existing setup makes things quite a bit slower on big core, but way faster on little core.

**Comment by GMNGeoffrey** [comment]
(although this is in comparison to the previous with loop unrolling, so not sure where that was)

**Review by bjacob — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
Turned on loop unrolling by default in #8408, so now we should just see the benchmark differences from MMT4D (which presumably is just the massive speedups on little core)

**Comment by GMNGeoffrey** [comment]
Interesting. This actually improves quite a lot of benchmarks quite significantly, while causing regressions in 3 multi-threaded big core benchmarks. There are also reported regressions and improvements (~5%) in a few configs that aren't changed at all. My theory is that the savings from creating a MMT is causing huge improvements in everything except the things that we've already optimized the crap out of (fp32 multi-threaded big-core). That's pretty good :-D

**Pull request merged**
