### PR TITLE
Merge google -> main

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
* 58d25ee8 Synchronize submodules                                                          
* 6919f322 Update TF and CMake files for mlir-hlo move                                     
* a708d97e Move XLA-independent transforms to the new MLIR-HLO directory                   
* 8b6621e1 Merge pull request #2400 from iml130:tensorflow-cmake                           
* ec41a0a3 Cleanup and fix file ordering in TF CMakeLists                                  
* 87eaa3c6 Refactor TensorFlow CMakeLists                                                  
* 1dc5fa09 Synchronize submodules                                                          
* d7745277 Update TF submodule and LLVM BUILD files                                        
* f478074f Synchronize submodules                                                          
* 87455ee8 Integrate LLVM at https://github.com/llvm/llvm-project/commit/0607c8df7faf      
* 6c41ee6d Synchronize submodules                                                          
* 8a8a89fc Integrate LLVM at https://github.com/llvm/llvm-project/commit/cd209f1a3790      
* 7643d59d Synchronize submodules                                                          
* 59f35a14 Integrate LLVM at https://github.com/llvm/llvm-project/commit/edba2864a7a8      
* a624b25a Synchronize submodules                                                          
* c36ba20a Integrate LLVM at https://github.com/llvm/llvm-project/commit/91c320e9d852      
* d1fc80be Synchronize submodules                                                          
* a9baf19b Integrate LLVM at https://github.com/llvm/llvm-project/commit/01c4574a129e      
* 3b51a99b Synchronize submodules                                                          
* 8b1b7edd Integrate LLVM at https://github.com/llvm/llvm-project/commit/d6343e607ac8      
* c2ec2bd9 Synchronize submodules                                                          
* ed47aac9 Integrate LLVM at https://github.com/llvm/llvm-project/commit/68498ce8af37      
* 506be9e1 Synchronize submodules                                                          
* c5dcf953 Integrate LLVM at https://github.com/llvm/llvm-project/commit/0f9d623b63e8      
* 896de17d Move the HLO/LHLO dialects to a new directory: tensorflow/compiler/mlir/hlo

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
All commits have already been contributed to the repo

**Comment by GMNGeoffrey** [comment]
So... should we trim the commit history? Some potential thoughts:

1. Reverse the history so it's chronological top->bottom instead of bottom->top (earliest commit first).
2. Strip all "synchronize submodules" commits
3. Strip all but the most recent LLVM integrate commits
4. Strip merge commits

With all of those, this would look like:

* 896de17d Move the HLO/LHLO dialects to a new directory: tensorflow/compiler/mlir/hlo
* 87455ee8 Integrate LLVM at https://github.com/llvm/llvm-project/commit/0607c8df7faf
* d7745277 Update TF submodule and LLVM BUILD files     
* 87eaa3c6 Refactor TensorFlow CMakeLists     
* ec41a0a3 Cleanup and fix file ordering in TF CMakeLists
* 8b6621e1 Merge pull request #2400 from iml130:tensorflow-cmake
* a708d97e Move XLA-independent transforms to the new MLIR-HLO directory
* 6919f322 Update TF and CMake files for mlir-hlo move

**Comment by marbre** [comment]
I think earliest commit first already is chronological or not and should be fine? Regarding point 2, 3 and 4, this defensively leaves the history much cleaner.

**Comment by ScottTodd** [comment]
Are you talking about editing the actual commits included, or just updating the message used in the merge commit?

* I'm skeptical of any processing on the commits as part of the merge. While those proposed changes (except the ordering) do make the diff slimmer, we should be able to merge branches with as little effort as possible (that means no scripts, just a few git commands :P).
* The merge commit message isn't that important IMO - all the information in it is already contained in the commits it includes.

**Comment by GMNGeoffrey** [comment]
I'm just talking about the message. Rewriting the commit history would screw up the merging process. I agree the message information is already contained in the history, but that history isn't bisectable. I think making `git log --first-parent` usable is a good goal, since it's easier to look at and captures the bisectable history. You can then explore merge commit history in addition if you want

**Comment by GMNGeoffrey** [comment]
Going to merge this as-is for now, as it is approved. We can discuss further description cleanup.

**Pull request merged**
