### PR TITLE
Changing default stream alignment to 64B.

### PR DESCRIPTION
**Pull request by benvanik**
This is not a real fix for the issue but will let us test how critical this value is.

### CODE REVIEW

**Comment by antiagainst** [comment]
Might also want to revert https://github.com/google/iree/commit/74cab16fa7fafa0c92d41c3d86105ac73d5c4af3 to show the effects.

**Comment by benvanik** [comment]
Good idea! Will push that after this benchmark finishes because I've been waiting for 45mins already :P

**Comment by benvanik** [comment]
Benchmarks didn't update, but full run rebased onto the latest mahesh changes looks good: https://gist.github.com/c29d328dd4369e8504f62c085498a209

**Review by antiagainst — APPROVED** [review]
Nice, thanks for the fix!!

**Comment by hanhanW** [comment]
I think this breaks MiniLM Bert. It crashes during the runtime.

I'm able to compile and run the model at commit 7e1322e4477412b7a26c6bb9b6747bd06e7e2f1b. I'm not able to run the model at this commit.

To repro:

```
$ iree-translate --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=dylib-llvm-aot --iree-input-type=mhlo ~/input.mlir --iree-llvm-target-triple=x86_64-pc-linux-gnu --iree-llvm-target-cpu-features=host -o /tmp/a.vmfb --iree-llvm-loop-unrolling=true

$ iree-benchmark-module --module_file=/tmp/a.vmfb --driver=dylib --task_topology_group_count=0 --function_input=1x128xi32=0 --function_input=1x128xi32=0 --function_input=1x128xi32=0 --entry_function=predict
```

The input file can be found at https://storage.googleapis.com/iree-shared-files/nod-perf/hanchung/ir.zip

**Comment by benvanik** [comment]
Define crash - segfault in codegen?
If bumping the alignment up to the next power of two makes things crash that's pretty scary. I'll try a diff and see if anything stands out.

**Comment by hanhanW** [comment]
I'm not pretty sure, I didn't see the stack trace. The last command I found in Tracy is `iree_hal_device_submit_and_wait`.

image

**Comment by benvanik** [comment]
The only difference in the output between before/after on the host is an attribute (I'll verify it's being respected) and a single constant integer inside of the generated LLVM IR (indicating alignment):
image
image

it does result in some very different x86 though once LLVM gets ahold of it:
image

I'll verify the buffer base address really is at 64 bytes in the binary and in memory.

**Comment by benvanik** [comment]
Looks like constants may not be aligned right! It does run just fine for me, though.
```
[module.predict+000007EC]    vm.call.varadic @hal.command_buffer.push_descriptor_set(%r17(!hal.command_buffer/0x0000022D0AAB15D0), %r4(!hal.executable_layout/0x0000022D0B5A3010), %i15(0), %i15(0), %r3(!hal.buffer/0x0000022D7FE61AC0), %i15(0), %i14(133405184), %i2(1), %r0(!hal.buffer/0x0000022D0B5BB720), %i15(0), %i3(512), %i13(2), %r2(!hal.buffer/0x0000022D0B5BBC40), %i15(0), %i3(512), %i12(3), %r16(!hal.buffer/0x0000022D064A1040), %i15(0), %i9(2557440))
[module.predict+00000826]    vm.call @hal.command_buffer.dispatch(%r17(!hal.command_buffer/0x0000022D0AAB15D0), %r5(!hal.executable/0x0000022D0B43A860), %i2(1), %i16(6), %i13(2), %i2(1))
dispatch
  binding[0]: 0000022D0BB6AEA0 / 32
  binding[1]: 0000022D0B5BB7A0 / 32
  binding[2]: 0000022D0B5BBCC0 / 0
  binding[3]: 0000022D064A10C0 / 0
```

I'll figure out why alignment isn't propagating right.

**Comment by benvanik** [comment]
🤦  everything is right in the file, but the ancient debug c++ that loads files into memory doesn't align things

**Comment by benvanik** [comment]
(and can't 'cause it's following the silly abseil pattern of using std::string to allocate memory for binary buffers - time to nuke this all)

**Comment by benvanik** [comment]
I've fixed file alignment for constants but it turns out the allocated heap buffers have only ever been aligned to 16B. This means that the 32B alignment value was also wrong before but just happened to line up most of the time. For me the only time I get issues is using `-iree-llvm-target-cpu-features=host`; I think because AVX is only kicking in with that flag _and_ 64B alignment:
image

I'll get the file changes in that fix alignment for constants but it was chance that it ever worked with transient buffers and I'll need to find a good solution for that.

**Comment by benvanik** [comment]
(file fix https://github.com/google/iree/pull/8505, issue for tracking alignment of heap buffers https://github.com/google/iree/issues/8506)

**Comment by hanhanW** [comment]
Thanks for looking into this tricky issue! :D

**Pull request merged**
