### PR TITLE
Adding a skeleton librt to provide libc/libm/etc during embedded linking.

### PR DESCRIPTION
**Pull request by benvanik**
The code should be factored out as we start to add things like placeholder
functions for querying runtime state/etc but starting simple here to get
us bootstrapped.

See librt/src/librt.h for some notes.
Run librt/build.sh to update the .bc file and then rebuild iree-* so the new version is pulled in.

Example of the bitcode we are currently generating:
https://gist.github.com/benvanik/68f50381345ef4b3271293568f3302e2

Enables burndown on #4717.

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
Looks mostly fine to me. I wish there was a better solution than `sed`. Would that work for our builds?

**Comment by benvanik** [comment]
> Looks mostly fine to me. I wish there was a better solution than `sed`. Would that work for our builds?

What do you mean? (like, do machines have sed?)

**Comment by MaheshRavishankar** [comment]
> > Looks mostly fine to me. I wish there was a better solution than `sed`. Would that work for our builds?
> 
> What do you mean? (like, do machines have sed?)

Ah, sorry, forgot that the `build.sh` is not invoked during build process. Just to update the `.bc` if needed.

**Comment by benvanik** [comment]
> Ah, sorry, forgot that the `build.sh` is not invoked during build process. Just to update the `.bc` if needed.

yep! you'll need clang/llvm tools on your path (for clang and llvm-as). I wanted to avoid llvm-* but clang insists on putting host information in the files and piping the file through stdin was the only way I could find to make it stop :(

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by lundong** [comment]
@benvanik Hi Ben, is this work under active developments? Would it make sense for me to add the implementation of floorf at this point? Adding floorf would enable compilation of many models of interest (e.g., mobilenet).

**Comment by MaheshRavishankar** [comment]
@lundong that would be really welcome! Happy to review any PRs on those.

**Pull request merged**
