### PR TITLE
correct comment spelling

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**
correct comment spelling

### CODE REVIEW

**Comment by RuffaloLavoisier** [comment]
@benvanik @MaheshRavishankar 
Sorry, is there a process I forgot before submitting the PR? Can you tell me why you closed it?

**Review by MaheshRavishankar — COMMENTED** [review]
Not sure why this was closed. It looks good to me. Thanks!

**Comment by RuffaloLavoisier** [comment]
Thanks !

**Comment by RuffaloLavoisier** [comment]
@ScottTodd @MaheshRavishankar @benvanik
Thank you for your interest. I checked the `remote`/`local` github log today and found that the reason `PR` was closed was because I deleted my fork. sorry confused.I apologize.

**Comment by ScottTodd** [comment]
Ah, not a problem @RuffaloLavoisier , thanks for checking and reporting back. Good to know, I was confused about how it was closed too 😅

**Pull request merged**
