### PR TITLE
Link CMAKE_DL_LIBS where needed instead of adding -ldl to linker flags (#5702)

### PR DESCRIPTION
**Pull request by kintel**
Instead of adding a check for "Linux", I opted for using CMAKE_DL_LIBS (https://cmake.org/cmake/help/latest/variable/CMAKE_DL_LIBS.html) and trust CMake to correctly populate this flag per platform.

Tested on gLinux using clang.

Before:
```
/usr/bin/c++ -O2 -g -DNDEBUG -lm -dl -lpthread
[...] 
iree/base/internal/libiree_base_internal_synchronization.a
[...]
```
After:
```
/usr/bin/c++ -O2 -g -DNDEBUG -lm -lpthread
[...] 
iree/base/internal/libiree_base_internal_synchronization.a  -ldl
[...]
```

### CODE REVIEW

**Comment by benvanik** [comment]
@ScottTodd / @GMNGeoffrey what's the right approach for bazel to cmake here? turn `//build_tools:default_linkopts` into `//build_tools:dl` or something that we can then remap to this variable?

**Comment by kintel** [comment]
Sorry for not realizing that there's a build system conversion. I'll take a crack at getting blaze to work and look into the conversion scripts. Any hints are welcome :)

**Comment by ScottTodd** [comment]
> @ScottTodd / @GMNGeoffrey what's the right approach for bazel to cmake here? turn `//build_tools:default_linkopts` into `//build_tools:dl` or something that we can then remap to this variable?

Yep, that general approach SGTM.

We have some libraries that need `-ldl` and/or `-lpthread`.

We specify that on the Bazel side with a `//build_tools:default_linkopts` target, defined here and explicitly included on targets that need it:
https://github.com/google/iree/blob/96ecf77c29263d6800e66df504fb7be13547fa4a/build_tools/BUILD#L13-L29

As you've encountered, we define that on the _CMake_ side here:
https://github.com/google/iree/blob/96ecf77c29263d6800e66df504fb7be13547fa4a/build_tools/cmake/iree_copts.cmake#L292-L299

https://github.com/google/iree/blob/96ecf77c29263d6800e66df504fb7be13547fa4a/build_tools/cmake/iree_copts.cmake#L309-L316

The CMake settings are unconditional, but they don't need to be. We don't currently map between them at all: 
https://github.com/google/iree/blob/96ecf77c29263d6800e66df504fb7be13547fa4a/build_tools/bazel_to_cmake/bazel_to_cmake_targets.py#L10-L12

---

so I'd suggest something like
* Split the Bazel `//build_tools:default_linkopts` into `//build_tools:dl` and `//build_tools:pthread`
* Edit that `EXPLICIT_TARGET_MAPPING` in our conversion script to map `//build_tools:dl` to `${CMAKE_DL_LIBS}`
* Either ignore pthread and keep it unconditional with no remapping, or
  A) Try something like https://cmake.org/cmake/help/v3.2/module/FindThreads.html ->`Threads::Threads`
  B) Remap to a new library target that includes a `CLANG_OR_GCC` `"-lpthread"` dep

**Review by ScottTodd — APPROVED** [review]
Resolved a merge conflict. I'm happy if the CI is happy :D

**Pull request merged**
