### PR TITLE
Run synchronize submodules action on main branch

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
This will be a new persistent branch

Part of https://github.com/google/iree/issues/2279

### CODE REVIEW

**Comment by benvanik** [comment]
Is this needed? We shouldn't need a SUBMODULES_VERSION or any such machinery, and instead only bump the submodules when required (either when merging google into main or when someone wants to bump a submodule for a specific revision).

**Comment by ScottTodd** [comment]
> Is this needed? We shouldn't need a SUBMODULES_VERSION or any such machinery, and instead only bump the submodules when required (either when merging google into main or when someone wants to bump a submodule for a specific revision).

This depends on how much of the existing automation we want to keep using. My preference is to keep the automation and checks for the initial migration then re-evaluate each piece of infrastructure later.

At one extreme, we could have no checks or automated commits to the `google` branch and handle any relevant issues when merging `google` <-> `main`.
At the other, we keep automated tests, submodule update actions, etc. running on *both* branches. This will help us spot issues earlier, but will be noisier.

This action and the `SUBMODULE_VERSIONS` file is particularly useful in interfacing with the treatment of LLVM in the Google repo, since it pins the code on the `google` branch here to the LLVM commit represented there (and tested in the code). We might be able to keep that isolated to just the `google` branch, but let's figure out specifically how later (maybe add `SUBMODULE_VERSIONS` to `.gitignore` on `main`?)

**Comment by benvanik** [comment]
Hmm not sure I agree with the approach of trying to remove automation - I'd rather start with what we know is simple/easy (which is none of the automation, because if we weren't doing google stuff we wouldn't have any of it) and then only add things when they are really worth it. Keeping them in the google branch is fine, but part of the goal here is to avoid depot_tools-like magic infrastructure and just using canonical git/github workflows.

**Comment by GMNGeoffrey** [comment]
We still need SUBMODULE_VERSIONS and the sync action in the google branch to allow LLVM integrates to update the submodules. It's likely we won't need the sync submodules action to ever run in the `main` branch because it shouldn't be getting anything coming from google3. However, the diff between the submodule state and SUBMODULE_VERSIONS still represents and invalid state that we'll need to resolve. Currently all our CI uses SUBMODULE_VERSIONS and our documentation says that's the source of truth. Once we're all-github on `main`, we can enforce the check submodules on presubmit.

However, I would like to defer any more complicated merging strategies until we've got this stable. The merging workflows are already complex, but I've tested them out. Having files that are only in one branch just makes our job harder and means leaping right into an untested scenario that I suspect will fall down.

> maybe add SUBMODULE_VERSIONS to .gitignore on main?

Yeah I thought of that, but wouldn't the .gitignore itself also get merged?

In the happy path, people look at the presubmits before merging and this action never gets run. I don't care too much if we don't add it to `main`.

**Comment by ScottTodd** [comment]
We're definitely aiming for the `main` branch to look normal, with any of the existing quirks isolated to the `google` branch. Small (and large) steps to get there without some of this infrastructure exploding though :D

**Comment by benvanik** [comment]
Ok, so hopefully we'll be able to remove our dependence on SUBMODULE_VERSIONS and instead just use git's revisions - if SUBMODULE_VERSIONS is only used to talk to google via copybara that's fine, but that could happen as a copybara import/export step.

Happy to leave SUBMODULE_VERSIONS in main for now, but if there's not a need to enable the action I'd rather keep it off so we don't end up still having it in 6mo with a TODO to remove it :)

**Comment by GMNGeoffrey** [comment]
> but that could happen as a copybara import/export step.

Unfortunately it can't. The whole problem is that Copybara doesn't expose support for reading/writing submodules. I've got an outstanding feature request that the team has agreed is a good way to implement it, but it hasn't been prioritized. If we care enough, I could probably look into implementing it, but it hasn't seemed like a high enough priority.

**Comment by GMNGeoffrey** [comment]
Going to close this. Hopefully it doesn't become necessary.

**Pull request closed without merging**
