### PR TITLE
Add a test on dot_general to vulkan-specific tests.

### PR DESCRIPTION
**Pull request by hanhanW**
This is part of https://github.com/google/iree/pull/3010

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by hanhanW** [comment]
It seems the bug was not fixed, the results are mismatched.

```
[[415.996 415.996 415.996 415.996 415.596 415.596 415.596 415.596 410.796 410.796 410.796 410.796 410.796 410.796 410.796 4
10.796 414.796 414.796 414.796 414.796 414.396 414.396 414.396 414.396 422.796 422.796 422.796 422.796 422.796 422.796 422.796 422.796 429.996
429.996 429.996 429.996 429.996 429.996 429.996 429.996 433.596 433.596 433.596 433.596 433.196 433.196 433.196 433.196 435.996 435.996 435.996
 435.996 436.396 436.396 436.396 436.396 441.596 441.596 441.596 441.596 441.196 441.196 441.196 441.196][415.996 415.996 415.996 415.996 415.5
96 415.596 415.596 415.596 410.796 410.796 410.796 410.796 410.796 410.796 410.796 410.796 414.796 414.796 414.796 414.796 413.996 413.996 413.
996 413.996 422.796 422.796 422.796 422.796 422.396 422.396 422.396 422.396 429.996 429.996 429.996 429.996 429.996 429.996 429.996 429.996 433
.596 433.596 433.596
```

Expected all values to be `409.596`.

**Comment by MaheshRavishankar** [comment]
How come this happening only on cmake builds?

**Comment by MaheshRavishankar** [comment]
Seems to be fixed after PR #3095 . Will add this test to that PR while commiting unless @hanhanW  you want to add the test after that PR lands.

**Comment by hanhanW** [comment]
> Seems to be fixed after PR #3095 . Will add this test to that PR while commiting unless @hanhanW you want to add the test after that PR lands.

Sure, let's do it in that PR.

**Comment by GMNGeoffrey** [comment]
Hey I'm looking to switch over our Kokoro builds now that Swiftshader is supported everywhere. It's pretty much just a rename. This will cause failures on PRs that don't contain https://github.com/google/iree/commit/f941efb95dafb3ef4ba5cf6fbff0e247318b39de which defines the new build configs. After I do so, this PR will see infra failures on the new builds. Since you'll need to rebase anyway for conflicting files, I'm guessing that's ok?

**Comment by MaheshRavishankar** [comment]
Actually this PR has been superceeded by PR #3150 . So closing this.

**Pull request closed without merging**
