### PR TITLE
Migrate to use upstream bufferization for all the backends.

### PR DESCRIPTION
**Pull request by hanhanW**
This commit also removes IREE bufferization pass.

### CODE REVIEW

**Comment by hanhanW** [comment]
I verified that the regression issue in MobileNetV2 is addressed by https://reviews.llvm.org/D126320. We can benchmark other models after landing the commit.

**Comment by hanhanW** [comment]
I'm not sure if there are regressions on CUDA side. @ThomasRaoux can you help verify it?

**Comment by hanhanW** [comment]
I don't know why, but it looks like the correctness issue is gone after integrates.

**Review by antiagainst — APPROVED** [review]
Great work, thanks Hanhan!

**Comment by MaheshRavishankar** [comment]
Hey Hanhan,

Thanks for pushing this. Would be good to keep the tests though.... Do you need help migrating the test over to use the comprehensive bufferization path?

**Comment by hanhanW** [comment]
> Hey Hanhan,
> 
> Thanks for pushing this. Would be good to keep the tests though.... Do you need help migrating the test over to use the comprehensive bufferization path?

Good point, I'll take a stab at migrating the test. If I run into issues, I'll let you know.

**Comment by hanhanW** [comment]
>  some alloc ops are created which can be avoided.

I found that it's intended. We do have a test with similar form and we check that if there are alloc ops. The main reason is that the matmul op takes a readonly tensor in outs. I think `*_inplace` covers the needs of tests, and the allocation behavior is already tested. In this context, I deleted those tests.

https://github.com/google/iree/blob/be167a62f8872597eac1b72e26b4c62e291bfd5c/compiler/src/iree/compiler/Codegen/Common/test/iree_comprehensive_bufferize.mlir#L3-L71

**Comment by hanhanW** [comment]
File issues for reshape_read_only test (https://github.com/google/iree/issues/9359) and redundant subview.memref op issue (https://github.com/google/iree/issues/9360).

**Review by MaheshRavishankar — APPROVED** [review]
Awesome! Thanks for all the work!

**Pull request merged**
