### PR TITLE
Make IREE thread/synchronization compile on macOS

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Comment by antiagainst** [comment]
@benvanik: I'm not sure `NULL` is the proper attribute for initializing mutex and condition. Let me know what value should be. And this just enables it compiling on macOS. I'm seeing a test failure for `ThreadTest.PriorityOverride`.

**Comment by benvanik** [comment]
NULL is fine for those!

What's the failure like?

**Review by benvanik — APPROVED** [review]

**Comment by antiagainst** [comment]
```
+ /Users/antiagainst/iree/build-debug/iree/base/iree_base_threading_test
[==========] Running 5 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from ThreadTest
[ RUN      ] ThreadTest.Lifetime
[       OK ] ThreadTest.Lifetime (0 ms)
[ RUN      ] ThreadTest.CreateSuspended
[       OK ] ThreadTest.CreateSuspended (151 ms)
[ RUN      ] ThreadTest.PriorityOverride
../iree/base/threading_test.cc:153: Failure
Expected: (nullptr) != (override0), actual: (nullptr) vs NULL
../iree/base/threading_test.cc:156: Failure
Expected: (nullptr) != (override1), actual: (nullptr) vs NULL
../iree/base/threading_test.cc:159: Failure
Expected: (nullptr) != (override2), actual: (nullptr) vs NULL
/Users/antiagainst/iree/build_tools/cmake/run_test.sh: line 33: 73578 Segmentation fault: 11  "$@"
+ cleanup
+ echo 'Cleaning up test environment'
Cleaning up test environment
+ rm -rf /Users/antiagainst/iree/build-debug/iree_base_threading_test_test_tmpdir
```

I haven't looked into the thread/synchronization magic you've landed recently so I'm not sure how to properly decipher this. :)

**Comment by benvanik** [comment]
Weird that it would fail like that - according to the docs (https://opensource.apple.com/source/libpthread/libpthread-105.1.4/pthread/qos.h.auto.html) I'm calling it right. Maybe it is allowed to return NULL in cases when the arguments are valid. We could make the test gracefully fail (SKIP() or whatever the gtest macro is) if it returns null and only run the rest of the test (actually accessing the values) if it's valid.

**Comment by antiagainst** [comment]
SGTM. I can try to `SKIP` it later.

**Pull request merged**
