### PR TITLE
Re-land moving tensor->flow passes.

### PR DESCRIPTION
**Pull request by ScottTodd**
Reverts https://github.com/google/iree/pull/6648, rolling-forward https://github.com/google/iree/pull/6586.

First commit is the pure revert, second is a set of proposed fixes for the performance regression. The single pass (with a true/false option) is now split further:
* `createConvertTensorOpsPass`
* `createConvertLinalgTensorOpsPass(true)`
* `createConvertLinalgTensorOpsPass(false)`

---

This gets the original change closer to an NFC (but it is still not an NFC).

Before this change:

| stage | patterns |
| --- | --- |
| `buildCommonInputConversionPassPipeline` | `tensor::CastOp`, `tensor::FromElementsOp` |
| Flow, before DispatchRegionFormation | `tensor::InsertSliceOp`, `tensor::ExtractSliceOp`, <br> `linalg::TensorCollapseShapeOp`, `linalg::TensorExpandShapeOp` |
| Flow, after DispatchRegionFormation | `linalg::FillOp` |

After this change:

| stage | patterns |
| --- | --- |
| `buildCommonInputConversionPassPipeline` | (deleted) |
| Flow, before DispatchRegionFormation | `tensor::CastOp`, `tensor::FromElementsOp`, <br>`tensor::InsertSliceOp`,  `tensor::ExtractSliceOp`, <br>`linalg::TensorCollapseShapeOp`, `linalg::TensorExpandShapeOp` |
| Flow, after DispatchRegionFormation | `linalg::FillOp` |

Passes on `linalg` ops are the same, but two `tensor` ops are now converted after linalg fusion, rather than at input conversion time. The first version of this change had those `linalg` ops converted during the "common input conversion pipeline".

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
> buildCommonInputConversionPassPipeline | tensor::CastOp, tensor::FromElementsOp,tensor::InsertSliceOp, tensor::ExtractSliceOp
> -- | --

Of the top of my head I dont know if the move of `tensor.insert_slice` and `tensor.extract_slice` early on is going to have an impact. If this is  being done from detensoring, you could just use `tensor::CastOp` and `tensor::FromElementsOp` in the `buildCommonInputConversionPassPipeline` and use the `ConvertToFlowTensorOpsPass(/*before =*/true)` before you run the detonsorization passes?

**Comment by ScottTodd** [comment]
> > buildCommonInputConversionPassPipeline
> > tensor::CastOp, tensor::FromElementsOp,tensor::InsertSliceOp, tensor::ExtractSliceOp
> 
> Of the top of my head I dont know if the move of `tensor.insert_slice` and `tensor.extract_slice` early on is going to have an impact. If this is being done from detensoring, you could just use `tensor::CastOp` and `tensor::FromElementsOp` in the `buildCommonInputConversionPassPipeline` and use the `ConvertToFlowTensorOpsPass(/*before =*/true)` before you run the detonsorization passes?

The specific need I have for detensoring is for the `tensor::FromElementsOp` pattern after detensoring, before dispatch region formation. Beyond that, I'd like to keep the patterns/passes organized and grouped together where possible. Requiring certain patterns run (or not) at specific times for performance (and not correctness) is tricky to maintain without first converting that tribal knowledge into documentation or tests...

**Comment by ScottTodd** [comment]
Benchmark results look inline with prior commits to me - no regression from this :)

**Comment by MaheshRavishankar** [comment]
> > > buildCommonInputConversionPassPipeline
> > > tensor::CastOp, tensor::FromElementsOp,tensor::InsertSliceOp, tensor::ExtractSliceOp
> > 
> > 
> > Of the top of my head I dont know if the move of `tensor.insert_slice` and `tensor.extract_slice` early on is going to have an impact. If this is being done from detensoring, you could just use `tensor::CastOp` and `tensor::FromElementsOp` in the `buildCommonInputConversionPassPipeline` and use the `ConvertToFlowTensorOpsPass(/*before =*/true)` before you run the detonsorization passes?
> 
> The specific need I have for detensoring is for the `tensor::FromElementsOp` pattern after detensoring, before dispatch region formation. Beyond that, I'd like to keep the patterns/passes organized and grouped together where possible. Requiring certain patterns run (or not) at specific times for performance (and not correctness) is tricky to maintain without first converting that tribal knowledge into documentation or tests...

Agreed it is tricky to maintain, but is also tricky to write tests. Only realistic way to test these is to use the number of dispatches created as a proxy for this. I cant think of good lit tests you can write for this. These are whole program optimizations.
Documentation is something we can do, but those can get stale quickly. These arent correctness issues. These are performance issues. Tracking via perf regressions is the best test IMO.
In any case, thats orthogonal to what you are trying to do right. I am not against the refactoring here, but putting all patterns in one place is not always beneficial. You want to be deliberate in which patterns apply where. Each of those passes and patterns are for a specific purpose.

**Comment by MaheshRavishankar** [comment]
> Benchmark results look inline with prior commits to me - no regression from this :)

Still would be better to not do `tensor.*_slice` -> `flow.tensor.*` that early. In general lowering directly to Flow is problematic. I dont think long term that is going to be the case. So why put more of such conversions on that path.

**Comment by ScottTodd** [comment]
> > Benchmark results look inline with prior commits to me - no regression from this :)
> 
> Still would be better to not do `tensor.*_slice` -> `flow.tensor.*` that early. In general lowering directly to Flow is problematic. I dont think long term that is going to be the case. So why put more of such conversions on that path.

Okay. I'm not totally following the rationale here and in https://github.com/google/iree/issues/6368, but could we just drop the 2-4 patterns from `buildCommonInputConversionPassPipeline` and handle all 4 entirely during the flow transformation pipeline? Or is there some factoring that you'd propose for pass naming / options?

**Comment by MaheshRavishankar** [comment]
> Okay. I'm not totally following the rationale here and in #6368, but could we just drop the 2-4 patterns from `buildCommonInputConversionPassPipeline` and handle all 4 entirely during the flow transformation pipeline? Or is there some factoring that you'd propose for pass naming / options?

I think that would be ideal, but its going to be non-trivial. If I understand correctly you can move the `tensor.cast` to `flow.tensor.cast` conversion after dispatch region formation (you just need to make sure that the `tensor.cast` is not within a dispatch region.

The `tensor.from_elements` is tricky. That, if memory serves me right, is related to how mhlo rerpesents operations related to control flow.

@stellaraccident might help more on that.

I am just saying in the table above make the before and after this change the same. The demarcation of what "tensor" ops are and what "linalg on tensors" ops are is blur. So they dont bucket neatly by dialect.

**Comment by MaheshRavishankar** [comment]
Looked through this again. I am more convinced that the `tensor.insert_slice` and `tensor.extract_slice` conversion to `flow.tensor.*` ops. needs to happen after all the Linalg fusion passes. One of the things that happens in Linalg fusion is that unit-extent dimensions are dropped. One way that is done is by using the rank-reducing versions of these ops. Converting them to `flow.` means that this is not going to happen.
The impact might not show up on our benchmarks, but its one of the pieces of the puzzle that helps elementwise fusion. 
Ideally no op should be converted to flow ops before linalg fusion, giving it full opportunity to fuse. `tensor.from_elements` is different in the sense that there is nothing much you can do in terms of fusion there. So if possible all the conversion to flow should be done after linalg fusion.

**Comment by ScottTodd** [comment]
I removed the common input conversion pass entirely, moving those `tensor` conversion patterns to after linalg fusion. I also added a test for `tensor.cast` e2e to verify that https://github.com/google/iree/issues/6368 is still fixed (though without a more complex test model I'm not sure if this overly simplifies the problem).

**Review by MaheshRavishankar — APPROVED** [review]
Ok, this looks good to me. Hopefully doesnt cause any other issues. If there is, I think we should try to preserve this flow anyway.

**Pull request merged**
