### PR TITLE
Faster mobilenet compilation flags

### PR DESCRIPTION
**Pull request by asaadaldien**
Operand padding should be enabled so all 1x1 conv are vectorized

### CODE REVIEW

**Comment by benvanik** [comment]
Can we enable these by default instead? We really don't want benchmarks using different flags than what normal development/profiling/etc is using.

**Comment by asaadaldien** [comment]
Operand padding should be enabled for CPU by default (otherwise matmuls with sizes not a multiple of the vector size aren't going to be vectorized), not sure if we want to have it have it on be default for GPU g@antiagainst @ThomasRaoux ?

**Comment by antiagainst** [comment]
Should be fine to compile; but I'm a bit worried about the copying resulted from pad_tensor. But could give it a try to see how that works. Though the pass requires a parameter; even it's default I'm not sure we can really pick on the same one for CPU and GPU and entirely elide it. So probably we need to stick with this divergence a bit longer.. (Also on the GPU side I'll spend most of my time next trying to improve the basic pipeline; so won't have time to tweak it much too.)

**Comment by antiagainst** [comment]
Also a bit context: this is for pulling some recent up-to-date numbers for Stella/Julia. It would be nice to reflect the current status as we have the divergence for some time already; at least for the CPU side let's make it proper. So I'm fine with this go in. :)

**Comment by benvanik** [comment]
If you need local numbers then you don't need to check this in ;)
@MaheshRavishankar has been working hard to eliminate these kind of flags - if he's fine with it then 🤷

**Comment by benvanik** [comment]
(super happy to have faster models and stress the feature - just want to make sure we don't end up making everyone trying to do performance analysis/reproducing compile issues/etc life harder by having the bots use different flags than local execution would give you)

**Comment by MaheshRavishankar** [comment]
> If you need local numbers then you don't need to check this in ;)
> @MaheshRavishankar has been working hard to eliminate these kind of flags - if he's fine with it then

+1 for not checking this in to the buildkite performance tracking. As a one of "this is what we can get" measurement, just running this locally is what I'd prefer too.

**Comment by antiagainst** [comment]
Yup, sounds good to me!

**Comment by asaadaldien** [comment]
I think we have the question here "what the automated benchmarks are for?". IMO we should have a way to track "best performance" not only "default compilation performance" otherwise very easy to miss regressions.

**Comment by benvanik** [comment]
We should have both if we want it on (which could be useful) - "current default" + "experimental flags"

**Comment by asaadaldien** [comment]
@benvanik This is another example in addition to the `mmt4d` also related where we need the apply graph level rewrite patterns at flow level with symbols or as in the mmt4d case as we discussed turn some dims into dynamic then build multi static versions in HAL (the target dependent dispatches), if we did that we won't need these kind of flags.

**Comment by MaheshRavishankar** [comment]
> I think the question here "what the automated benchmarks are for?". IMO we should have a way to track > "best performance" not only "default compilation performance" otherwise very easy to miss regressions.

The default compilation must be the best or close to the best. We can have a few tricks that give you an extra, but these tricks shouldnt be so load bearing that you need to track them in CI.

> @benvanik This is another example in addition to the mmt4d also related where we need th> e apply graph level rewrite patterns at flow level with lazy symbols to be subsisted later in one backend is selected or as in the mmt4d case as we discussed turn some dims into dynamic then build multi static versions in HAL (the target dependent dispatches), if we did that we won't need these kind of flags.

Lets not get into this long discussion here :) . This is unrelated to the change here. I dont see why this needs to be tracked in CI. This is just doing "pre-padding". CI can track the performance of "matmul" that is vectorized. The trick to get all matmul "padded" to get them vectorized is kind of an orthogonal thing.

**Comment by asaadaldien** [comment]
> > I think the question here "what the automated benchmarks are for?". IMO we should have a way to track > "best performance" not only "default compilation performance" otherwise very easy to miss regressions.
> 
> The default compilation must be the best or close to the best. We can have a few tricks that give you an extra, but these tricks shouldnt be so load bearing that you need to track them in CI.
For matmul code generation the best we can do is to pad the entire operand where padding parameter target specific (even for the same target different architectures requires different padding). thats why I was raising this here 

> > @benvanik This is another example in addition to the mmt4d also related where we need th> e apply graph level rewrite patterns at flow level with lazy symbols to be subsisted later in one backend is selected or as in the mmt4d case as we discussed turn some dims into dynamic then build multi static versions in HAL (the target dependent dispatches), if we did that we won't need these kind of flags.
> 
> Lets not get into this long discussion here :) . This is unrelated to the change here. I dont see why this needs to be tracked in CI. This is just doing "pre-padding". CI can track the performance of "matmul" that is vectorized. The trick to get all matmul "padded" to get them vectorized is kind of an orthogonal thing.
Sorry, Not sure I understand what do you mean by ` tracked in CI. `

**Pull request closed without merging**
