### PR TITLE
Flipping `-iree-experimental-streams` flag to default true.

### PR DESCRIPTION
**Pull request by benvanik**

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]
May want to update the commit title before merging :)

Let's also keep an eye on the benchmarks (both before and after merging).

**Comment by ScottTodd** [comment]
> Looking through traces between main and this there's either noise (because we are only running single iterations of 90% of these benchmarks 🤦) or wins (like mobilessd cpu time going 1.6->1s) - we're still not testing on big cores though and our little core perf is terrible (1s+ for single tiles of matmuls in some models!) and not indicative of much of anything.

The top regressions and improvements in https://gist.github.com/iree-github-actions-bot/91273e7d0a6b3c9dcb2135af9bf3fb52 look outside of usual noise ranges. Most of the new "default-flags" benchmarks are similar though, so maybe the "experimental flags" we've been benchmarking with need new tuning on top of this?

**Comment by benvanik** [comment]
Unfortunately those are still not useful ;( the mobilebertsquad vulkan one for example runs only a single iteration in the new trace so it's impossible to know if that was a bad first iteration or indicative of a regression. It's also not clear what would cause any slowdown there as all the time is on the device - the host time drops from 4ms to 2.5ms (as I'd expect), but once you get into measuring many seconds of work with a single iteration it's not useful :/

**Comment by benvanik** [comment]
On mali things are a bit more sensible - even with the timestamp queries `MobileBertSquad-[fp32]-(TensorFlow)-full-inference,experimental-flags-with-IREE-Vulkan-@-SM-G980F-(GPU-Mali-G77).tracy` drops 200ms->167ms per iteration (which is what I'd expect).

**Comment by benvanik** [comment]
even mali though is weird, seeing 2x deltas in each iteration within a benchmark run both before/after - these numbers really aren't very useful: 
image

If games can hit solid reliable framerates we should be able to as well - something is wrong about our setup/device/tickling of the driver.

**Comment by benvanik** [comment]
Yeah I think these Android numbers aren't directly actionable. If we see real regressions in workloads where we trust the numbers we can dig into those, otherwise I think letting the bot statistically normalize the values is the only way to move forward.

**Comment by ScottTodd** [comment]
> Yeah I think these Android numbers aren't directly actionable. If we see real regressions in workloads where we trust the numbers we can dig into those, otherwise I think letting the bot statistically normalize the values is the only way to move forward.

Works for me. Can we hold off on removing the old code + flag until things settle a bit (1 week maybe)? It will be easier to compare code paths at the same commit by toggling the flag.

**Comment by antiagainst** [comment]
Sorry about all the confusion, Ben! I just hope somebody can fix this device stability issue before I become desperate and fly to Seattle. ;-P For GPU side we aren't focusing on Adreno at the moment; having them there mostly as a status tracking right now. So we can ignore regressions for Adreno (and I can look at why they are so bad afterwards). Mali numbers looks okay to me; basically within range. So if you'd like to land this, you have my +2 from mobile GPU side. :)

**Comment by benvanik** [comment]
> Works for me. Can we hold off on removing the old code + flag until things settle a bit (1 week maybe)? It will be easier to compare code paths at the same commit by toggling the flag.

We'll see - there's very little that cause me to unflip the flag instead of fixing forward beyond major correctness bugs (well, bigger ones than we had before anyway lol).

No worries lei - such is the world of mobile benchmarking and lacking/poor tooling ;(

**Pull request merged**
