### PR TITLE
Remove assumption of partitioned loops from Flow

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
This PR removes the last remnants of distribution behavior from Flow.
- The workload for a dispatch is now the entire iteration space of the operation.
- This allows moving `PartitionableLoopsInterface` into `Codegen`. Consequently, no assumption is made about which loops are partitioned at the Flow level.
- The `TileAndDistributeToWorkgroups` uses the `PartitionableLoopsInterface` to generate the region for number of workgroups to be consistent with the new way the `workload` is specified at Flow level.

### CODE REVIEW

**Comment by okkwon** [comment]
I am working on fusing a reduction and an elementwise op into a single dispatch. In this case, the reduction and the elementwise ops have different loop range, e.g., [128, 12, 1] and [128, 128, 12]. So when this happens, I expect to see [128, 12, 1] as the workgroup counts.

In your code change (and also in the previous code), the workload is computed solely based on the root Operation. How can this be extended?

**Comment by okkwon** [comment]
As discussed in the reduction fusion document, if we can treat the reduction workgroup count as the number of elements to reduce instead of 1, we may be able to keep using the root op to calculate the workgroup count. This seems to make more sense to me because it reflects the actual number of elements to handle.

**Comment by okkwon** [comment]
Yeah, it is confusing to me when I interpret the meaning of "workload". If it does not deliver an important semantic at the flow IR level, can we simply remove it? Is it planned as a part of the cleaning?

**Review by okkwon — APPROVED** [review]

**Comment by benvanik** [comment]
Correct Mahesh! Conceptually the workload is a set of inputs to a function that is used to compute the workgroup count, and that function is `extern` at the flow level, actually defined per target device, and may not resolve to concrete values until far in the future at runtime.

This is because the final workgroup count is based on the workload, workgroup size, and other device properties (like shared memory size) - at the flow level we don't know workgroup size or those device properties and thus can't throw away any information we'd eventually need to compute the workgroup count based on them. We may also not be able to know those at compile time at all and have to emit the runtime code to factor in things - we'll be asking Vulkan for its maxComputeSharedMemorySize and subgroupSize and CUDA for cudaDevAttrMaxSharedMemoryPerBlock and cudaDevAttrMultiProcessorCount, etc. It's a bug today (for expediency/bringup/etc) that we aren't using this information and not a feature we want to build more assumptions around. We also need to deduplicate our dispatches more and it's also a bug today that the shapes of things are as static as they are - when things are working right even in cases where static shape information is available we'll instead want it to be dynamic per dispatch site even if any individual dispatch site has fully static information. The additional static information should provide optimization opportunities but isn't a requirement ("this dispatch is called with workload %foo, that is one of values [1, 8, 16]" or "this dispatch is called with workload %bar, that is always aligned to 128", etc).

Changes like this one help us move closer to that by decoupling the implicit assumptions and letting us specialize more dynamically later in the compilation pipeline. It's exciting watching these changes land and thanks for tackling this Mahesh :)

**Comment by GMNGeoffrey** [comment]
This appears to have broken the [cuda build](https://source.cloud.google.com/results/invocations/21a8905c-82d1-40c0-b8ff-818b9e4f922d/targets/iree%2Fgcp_ubuntu%2Fcmake%2Flinux%2Fx86-turing%2Fmain/log)

<details>
<summary>test logs</summary>

```
 265/1094 Test  #258: iree/tests/e2e/xla_ops/check_cuda_graph_fft.mlir ...............................................................***Failed    1.59 sec
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from module
[ RUN      ] module.rfft_1d
/tmpfs/src/github/iree/runtime/src/iree/modules/check/module.cc:352: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    17xf32=649.4 0.980785 -577.865 2.91014 591.893 -0.55557 -572.297 0.682816 630.4 0.0585271 -579.667 -1.11114 592.388 -0.249441 -586.364 0 647.4
  rhs:
    17xf32=666.846 0 -590.169 0 593.448 0 -579.529 0 629.954 0 -567.113 0 591.751 0 -583.189 0 630.846
/tmpfs/src/github/iree/runtime/src/iree/modules/check/module.cc:352: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    17xf32=0 -0.19509 -16.8405 -1.9445 -10.2929 0.83147 19.7304 -3.43275 0.3 0.294236 -19.5466 -1.66294 10.7879 -0.166671 10.236 0 0
  rhs:
    17xf32=0 0 -23.9564 0 -10.2543 0 -6.14437 0 -10 0 3.86551 0 0.637674 0 52.4535 0 0
[  FAILED  ] module.rfft_1d, where GetParam() = 0 (811 ms)
[ RUN      ] module.rfft_2d
/tmpfs/src/github/iree/runtime/src/iree/modules/check/module.cc:352: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    1x17xf32=[649.4 0.980785 -577.865 2.91014 591.893 -0.55557 -572.297 0.682816 630.4 0.0585271 -579.667 -1.11114 592.388 -0.249441 -586.364 0 647.4]
  rhs:
    1x17xf32=[666.846 0 -590.169 0 593.448 0 -579.529 0 629.954 0 -567.113 0 591.751 0 -583.189 0 630.846]
/tmpfs/src/github/iree/runtime/src/iree/modules/check/module.cc:352: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    1x17xf32=[0 -0.19509 -16.8405 -1.9445 -10.2929 0.83147 19.7304 -3.43275 0.3 0.294236 -19.5466 -1.66294 10.7879 -0.166671 10.236 0 0]
  rhs:
    1x17xf32=[0 0 -23.9564 0 -10.2543 0 -6.14437 0 -10 0 3.86551 0 0.637674 0 52.4535 0 0]
[  FAILED  ] module.rfft_2d, where GetParam() = 1 (13 ms)
[----------] 2 tests from module (824 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (824 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] module.rfft_1d, where GetParam() = 0
[  FAILED  ] module.rfft_2d, where GetParam() = 1


313/1094 Test  #314: iree/tests/e2e/xla_ops/check_cuda_streams_fft.mlir .............................................................***Failed    0.94 sec
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from module
[ RUN      ] module.rfft_1d
/tmpfs/src/github/iree/runtime/src/iree/modules/check/module.cc:352: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    17xf32=649.4 0.980785 -577.865 2.91014 591.893 -0.55557 -572.297 0.682816 630.4 0.0585271 -579.667 -1.11114 592.388 -0.249441 -586.364 0 647.4
  rhs:
    17xf32=666.846 0 -590.169 0 593.448 0 -579.529 0 629.954 0 -567.113 0 591.751 0 -583.189 0 630.846
/tmpfs/src/github/iree/runtime/src/iree/modules/check/module.cc:352: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    17xf32=0 -0.19509 -16.8405 -1.9445 -10.2929 0.83147 19.7304 -3.43275 0.3 0.294236 -19.5466 -1.66294 10.7879 -0.166671 10.236 0 0
  rhs:
    17xf32=0 0 -23.9564 0 -10.2543 0 -6.14437 0 -10 0 3.86551 0 0.637674 0 52.4535 0 0
[  FAILED  ] module.rfft_1d, where GetParam() = 0 (53 ms)
[ RUN      ] module.rfft_2d
/tmpfs/src/github/iree/runtime/src/iree/modules/check/module.cc:352: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    1x17xf32=[649.4 0.980785 -577.865 2.91014 591.893 -0.55557 -572.297 0.682816 630.4 0.0585271 -579.667 -1.11114 592.388 -0.249441 -586.364 0 647.4]
  rhs:
    1x17xf32=[666.846 0 -590.169 0 593.448 0 -579.529 0 629.954 0 -567.113 0 591.751 0 -583.189 0 630.846]
/tmpfs/src/github/iree/runtime/src/iree/modules/check/module.cc:352: Failure
Failed
Expected near equality of these values. Contents does not match.
  lhs:
    1x17xf32=[0 -0.19509 -16.8405 -1.9445 -10.2929 0.83147 19.7304 -3.43275 0.3 0.294236 -19.5466 -1.66294 10.7879 -0.166671 10.236 0 0]
  rhs:
    1x17xf32=[0 0 -23.9564 0 -10.2543 0 -6.14437 0 -10 0 3.86551 0 0.637674 0 52.4535 0 0]
[  FAILED  ] module.rfft_2d, where GetParam() = 1 (35 ms)
[----------] 2 tests from module (89 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (89 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] module.rfft_1d, where GetParam() = 0
[  FAILED  ] module.rfft_2d, where GetParam() = 1
```

</details>

**Pull request merged**
