### PR TITLE
Implement main functions for custom dialect tools and drop alwayslink from dialect

### LINKED ISSUE #1636: Dialect in custom_modules samples linked as whole archive
The dialect `iree::samples::custom_modules::dialect` is not explicitly registered. Instead the dialect is marked alwayslink and linked as whole archive into `custom-opt` and `custom-translate.` If possible the dialect should be explicitly registered, but the dialect is only extending an existing dialect and not a whole dialect on its own. Also affects the forked sample https://github.com/iml130/iree-template-cpp/tree/master/custom_modules.

### PR DESCRIPTION
**Pull request by marbre**
* Adds a function to explicitly register the custom dialect.
* Adds own main functions for `custom-translate` and `custom-opt`, in which the registration function is called.
* Drops alwayslink from the custom dialect.

Closes #1636

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
The layering check is upset in a big way on this one. It wants direct deps for everything, not going through `iree_opt_library`

**Comment by marbre** [comment]
I added those deps providing the headers used in the source code with is compiled into the `cc_binary` targets. Hopefully got them all :)

**Comment by marbre** [comment]
Messed up during rebasing and squashing, but should be fine now.

**Comment by GMNGeoffrey** [comment]
Thanks! Normally I would've just fixed the deps on import, but it seemed like it materially altered the intent here :-)

So it's a little unclear now what the purpose of iree_opt_lib is. It's just bundling some deps, but some of them don't seem like the sort of thing that need to be bundled. If we used it to encapsulate most of the work of the main function, so that the custom main didn't need so much copypasta I think that would make sense, but as it stands now it's just bundling deps, which is usually discouraged in bazel for the same reasons I outlined above. I think it makes sense for deps that are alwayslink because there you end up with runtime errors if you forget them, but for "normal" deps it's usually better to just include them directly.

Options here:
1. Inline all the deps of `iree_opt_lib`
2. Change `iree_opt_lib` -> `iree_dependent_dialect_registration`, or somehttps://github.com/tensorflow/tensorflow/commit/9ca9a4f8e9b4d60408a092db4320805711367042thing like that, and only leave in the XLA dialect registrations and similar type deps. Inline the rest of the deps.
3. Leave it as-is, with a TODO to add a source file to `iree_opt_lib` to pull some of the main functionality in there. We can do this to reduce the churn here if it's the next step anyway. I don't like leaving this sort of library around very much though.

**Comment by marbre** [comment]
> So it's a little unclear now what the purpose of iree_opt_lib is. It's just bundling some deps, but some of them don't seem like the sort of thing that need to be bundled.

You're right, the intention somehow got lost during the iteration.

> If we used it to encapsulate most of the work of the main function, so that the custom main didn't need so much copypasta I think that would make sense, but as it stands now it's just bundling deps, which is usually discouraged in bazel for the same reasons I outlined above.

Agreed. However, I think there isn't much it is worth to encapsulate.

> I think it makes sense for deps that are alwayslink because there you end up with runtime errors if you forget them, but for "normal" deps it's usually better to just include them directly.

Well, I think we'll get rid of alwayslink (maybe expect for TF). So no real need to bundle deps in a separate library. The ones that have to be linked as whole archive are documented in the out-of-tree example anyway :)

> Options here:
> 
>     1. Inline all the deps of `iree_opt_lib`
> 
>     2. Change `iree_opt_lib` -> `iree_dependent_dialect_registration`, or something like that, and only leave in the XLA dialect registrations and similar type deps. Inline the rest of the deps.
> 
>     3. Leave it as-is, with a TODO to add a source file to `iree_opt_lib` to pull some of the main functionality in there. We can do this to reduce the churn here if it's the next step anyway. I don't like leaving this sort of library around very much though.

I think the second option would just introduce another not really necessary target. Thus I went for the first option.

**Comment by GMNGeoffrey** [comment]
Now we're getting failures from the tf side because it's still depending on iree_opt_main/iree_translate_main for its main file and such. I think you can revert your changes to iree/tools/BUILD and iree/tools/CMakeLists.txt and everything should be fine form for the custom opt, right?

**Comment by GMNGeoffrey** [comment]
I've confirmed that reverting the changes in tools/BUILD is fine for our internal builds. I can do that as part of import and fixup the description to match, if that's easier for you than pushing new commits here

**Comment by marbre** [comment]
Missed to grep through integrations and that the main entry functions are linked into `iree-tf-opt` and `iree-tf-translate` :/ Sorry. Reverted the changes.

**Comment by GMNGeoffrey** [comment]
> Missed to grep through integrations and that the main entry functions are linked into `iree-tf-opt` and `iree-tf-translate` :/ Sorry. Reverted the changes.

No worries. Sorry for all the back and forth here. If we had OSS presubmits for the TF code this would be much easier :-/ Imported and all the tests pass. Waiting on another Googler to approve.

Meta question: it's easy for me to make arbitrary changes when merging, but I've avoided doing that because I want to make sure to get your input and not rewrite your descriptions. What is your preference on this? Is the current situation OK, or should I be more free with changes during merge?

**Pull request closed without merging**
