### PR TITLE
Add missing deps to iree c modules

### LINKED ISSUE #7677: iree_c_module doesn't add dependencies on vm libraries
The code generated by the CModuleTarget includes the following files:

- iree/vm/api.h
- iree/vm/ops.h
- iree/vm/ops_emitc.h
- iree/vm/shims_emitc.h

### PR DESCRIPTION
**Pull request by marbre**
Fixes #7677.

### CODE REVIEW

**Review by simon-camp — COMMENTED** [review]
Shouldn't we also update the users of ~~`iree_c_module`~~ the generated targets?

**Comment by marbre** [comment]
> Shouldn't we also update the users of ~`iree_c_module`~ the generated targets?

Good point. Done.

**Comment by marbre** [comment]
I'll go over some other deps which are not correct/obsolete as part of a followup.

**Review by simon-camp — APPROVED** [review]
LGTM

**Review by benvanik — APPROVED** [review]

**Pull request merged**
