### PR TITLE
Rename iree-tf-import -> iree-import-tf for consistency

### PR DESCRIPTION
**Pull request by xgupta**
Should fix https://github.com/google/iree/issues/4979

### CODE REVIEW

**Comment by xgupta** [comment]
This PR may not pass the buildbot/CI. On my local system I am getting error : 
```cmake --build ../iree-new1/
[0/2] Re-checking globbed directories...
ninja: error: '/home/xgupta/iree/integrations/tensorflow/bazel-bin/iree_tf_compiler/iree-import-tf', needed by 'bindings/python/iree/tools/tf/CMakeFiles/integrations_tensorflow_bindings_python_iree_tools_tf_tf', missing and no known rule to make it
 ```
I will further investigate the issue and update the PR soon. In the meanwhile someone from the IREE core team understands this issue, please provide a hint.

**Comment by GMNGeoffrey** [comment]
Thanks for the contribution. Sorry that we missed this. The issue for you locally is going to be that building the iree-import-tf has to be done as a separate step and then you tell CMake where it is (see https://google.github.io/iree/building-from-source/optional-features/#building-tensorflow-frontend-bindings). Don't worry, our CI will check this still works.

**Comment by GMNGeoffrey** [comment]
> ERROR: /tmpfs/src/github/iree/integrations/tensorflow/iree_tf_compiler/BUILD:56:10: //iree_tf_compiler:iree-import-tf: missing input file '//iree_tf_compiler:iree-import-tf-main.cpp'

Looks like you need to also rename that file

**Review by GMNGeoffrey — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
Another place that needs updating: https://github.com/google/iree/blob/a93ff6134aab4c47d1d4d46eb7eb6e48cf8a5665/integrations/tensorflow/iree_tf_compiler/BUILD#L26

**Comment by xgupta** [comment]
Thanks Geoffrey for help. Please merge this when all checks passed.

**Comment by GMNGeoffrey** [comment]
Of course! Thanks for cleaning things up :-) Sorry for all the back and forth on the CI... It only triggers automatically if you're in the google org or a repository collaborator. To stop people sending PRs that are bitcoin miners, basically. But it's unfortunately pretty clunky :-( If you're planning to make further contributions, I can add you as a collaborator with "read" permissions, which means Kokoro will trigger automatically for you (and that's about all that changes)

**Comment by xgupta** [comment]
Thanks Geoffrey for offering the collaborator role. It will be a pleasure to have it. 
But fyi I am learning MLIR/LLVM so start contributing IREE. And IREE also seems interesting to learn -:)

**Comment by GMNGeoffrey** [comment]
Ok the next time you send a PR to IREE please @ me and I'll add you to the collaborators :-)

**Pull request merged**
