### PR TITLE
Basic handling of multiple generic ops in dispatch regions on CPU path.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
If there are no root operations within a dispatch region, assume all
generic ops are tiled + distributed the same way, and can therefore
use the same configuration.

### CODE REVIEW

**Comment by bjacob** [comment]
This fixes the issue that I was having. Thanks!

**Review by hanhanW — APPROVED** [review]

**Comment by ThomasRaoux** [comment]
Is the name of the PR correct? It seem unrelated to the change

**Comment by hanhanW** [comment]
> Is the name of the PR correct? It seem unrelated to the change

Good point, I think it should be something like `Basic handling of multiple generic ops in dispatch regions on CPU path.`

Sorry that I only looked into description and file changes.

**Comment by MaheshRavishankar** [comment]
> Is the name of the PR correct? It seem unrelated to the change

Yeah, I had a stale commit in my branch, which led github to pick up the title from the previous commit. Fixed now.

**Comment by bjacob** [comment]
From hearing people talk, I thought that about anything could be descibed as "hoisting tensors" :-P

**Pull request merged**
