### PR TITLE
Don't inline block arguments that can be written

### PR DESCRIPTION
**Pull request by antiagainst**
We cannot just simply inline and replace all users for the
DispatchWorkgroupsOp if it is an argument that can be written;
for example, the region might perform work after loading a initial
constant from the argument and then write back.

### CODE REVIEW

**Comment by benvanik** [comment]
What would cause this case to arise? R/W is an antipattern like this in every case I can think of and we shouldn't be making such arguments R/W - it just introduces additional allocations and copies. I'd like to figure out why this is happening and prevent it before we allow it and lose it to time.

**Comment by antiagainst** [comment]
@benvanik: It's an artifact of multiple patterns applying sequentially. More context below: 

I encountered this when trying to improve handling for padding. Right now it's done as two steps, first `linalg.fill` and then `subtensor_insert`. They will be in two dispatch regions after DispatchLinalgOnTensorsPass, with the second dispatch having a tied argument, like [this test](https://github.com/google/iree/blob/11d3543892a3c55499abc04a0a3f146f03fcb69f/iree/compiler/Dialect/Flow/Transforms/test/dispatch_linalg_on_tensors.mlir#L233-L259) shows. I've a following-up commit that turns the first dispatch into a TensorSplatOp so it causes the first dispatch to be eventually folded into a splat constant. So then we are seeing the second dispatch having a tied argument that captures a constant value. 

Eventually I think we want to inline only the load and untie the operand-result connection. I didn't do it here because that will cause double `linalg.copy` in the same dispatch region and we are sort of back to https://github.com/google/iree/issues/5042. Regardless of performance, this seems a valid correctness fix to me so I send it out separately. But maybe being separate makes it obscure. I can send out following up patches together if that helps.

**Comment by benvanik** [comment]
Yep - this is good for correctness, but that example you post and it sounds like your follow up are the precise antipattern we want to avoid, so I wanted to make sure we talk about it :) let's chat in our 1:1

**Review by benvanik — APPROVED** [review]

**Comment by antiagainst** [comment]
Discussed during 1:1 and agreed to proceed with this for correctness and progressive performance improvement. We really need to nail down the padding handling issue though. :)

**Pull request merged**
