### PR TITLE
Drop TiledOpInterface implementations for tensor.extract_slice/insert_slice

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
These tiled op interface implementation was necessary for these ops
when tile and distribute were happening at the Flow level, so they arent
necessary anymore.

A consequence is that it is now possible to fold
`tensor.extract_slice/tensor.insert_slices` with
`flow.dispatch.tensor.load/flow.dispatch.tensor.store`
operations. Moving these patterns out of Codegen into Flow. These
folders arent made as canonicalizations for now since its unclear (to
me at least) if this involves implicit change to the representation of
parallel semantics. Such concerns have been raised previously. So as
an abundance of caution just using these patterns where they are
relevant, during dispatch region formation.

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by antiagainst** [comment]
FYI: this breaks benchmarking on Pixel 4 and Pixel 6. It looks there is a regression somewhere in vmvx, as it [takes ~1 hour](https://buildkite.com/iree/iree-benchmark/builds/2728#bac406d6-54ca-4faf-8509-e316c2c7e5f6/25-1600) to run "MobileNetV2 [fp32,imagenet] (TFLite) 4-thread,big-core,full-inference,experimental-flags with IREE-VMVX".

**Comment by MaheshRavishankar** [comment]
> FYI: this breaks benchmarking on Pixel 4 and Pixel 6. It looks there is a regression somewhere in vmvx, as it [takes ~1 hour](https://buildkite.com/iree/iree-benchmark/builds/2728#bac406d6-54ca-4faf-8509-e316c2c7e5f6/25-1600) to run "MobileNetV2 [fp32,imagenet] (TFLite) 4-thread,big-core,full-inference,experimental-flags with IREE-VMVX".

Ah, sorry about that. It should be easy to fix forward. I can do it first thing when I get back online. Do you want to revert this change in the meantime? I checked the perf numbers on the change before this one, but didn't expect this to have any effect. I missed the vmvx part.

**Comment by MaheshRavishankar** [comment]
On second thought maybe worth a revert. I can reland it. If you don't get to it before I get to my desk, I'll send the revert out.

**Comment by antiagainst** [comment]
Okay SG; let me revert it then. :)

**Comment by antiagainst** [comment]
Here is the revert pull request: https://github.com/google/iree/pull/8926.

**Pull request merged**
