### PR TITLE
Heuristically pick up tiling sizes to vectorize Linalg operations.

### PR DESCRIPTION
**Pull request by hanhanW**
Configurations: taskset 80 + dylib-sync on local Pixel 4

| Model            | Before  | After   |
| ---------------- | ------- | ------- |
| DeepLabV3        | 711 ms  | 188 ms  |
| MobileBertSquad  | 672 ms  | 673 ms  |
| MobileNetV2      | 103 ms  | 46.4 ms |
| MobileNetV3Small | 24.6 ms | 14.6 ms |
| MobileSSD        | 204 ms  | 166 ms  |
| PoseNet          | 545 ms  | 241 ms  |

Configurations: taskset f0 + dylib on local Pixel 4

| Model            | Before  | After   |
| ---------------- | ------- | ------- |
| DeepLabV3        | 358 ms  | 161 ms  |
| MobileBertSquad  | 376 ms  | 376 ms  |
| MobileNetV2      | 65.6 ms | 29.8 ms |
| MobileNetV3Small | 20.7 ms | 15.7 ms |
| MobileSSD        | 94 ms   | 79.9 ms |
| PoseNet          | 183 ms  | 121 ms  |

### CODE REVIEW

**Comment by benvanik** [comment]
This is freaking awesome! Once the benchmark run completes I'll check the traces and see if I can spot why there's no diff between single- and multi-threaded - I'd expect _some_ improvement, unless we are setting workgroup counts to 1x1x1 (in which case multi- degenerates to single-). That is to say, we probably still have 2x+ to gain on the multi-threaded side for those models that are equal between the two configs.

**Comment by MaheshRavishankar** [comment]
Fantastic! Ship it! There is always going to be some tweaking of these that can keep giving us improvements (I still have a regression I have to triage). But this at least shows we have a path for vectorization of convolution ops!

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by hanhanW** [comment]
> This is freaking awesome! Once the benchmark run completes I'll check the traces and see if I can spot why there's no diff between single- and multi-threaded - I'd expect _some_ improvement, unless we are setting workgroup counts to 1x1x1 (in which case multi- degenerates to single-). That is to say, we probably still have 2x+ to gain on the multi-threaded side for those models that are equal between the two configs.

Thanks Ben, it's nice to have other eyes on it! I plan to take a look at this too! I just can't wait sharing the good numbers with you, so I sent out the PR first. :p

**Comment by benvanik** [comment]
Looking at mobilenetv3small, there are some dispatches that are 1x1x1 or 2x1x1 - like dispatch_66:
image

Going to statistics on iree_task_dispatch_issue in the trace and clicking "group by user text" at the bottom will show the counts:
image

And on the other end of the spectrum we have some dispatching ~1us workgroups: 
image

Lots of bubbles we can fill:
image

The ones that are 2x+ faster when multi-threaded are filling those bubbles more, though even ones that are faster are still pretty bubble-filled (postnet):
image
(each of those dispatch 48's are ~2.3ms)

So nothing related to this PR (I think) - but good to see room for improvement, and improvements like this will only make these issues easier to spot and fix! Great work everyone!

**Comment by MaheshRavishankar** [comment]
> Looking at mobilenetv3small, there are some dispatches that are 1x1x1 or 2x1x1 - like dispatch_66: image
> 
> Going to statistics on iree_task_dispatch_issue in the trace and clicking "group by user text" at the bottom will show the counts: image
> 
> And on the other end of the spectrum we have some dispatching ~1us workgroups: image
> 
> Lots of bubbles we can fill: image
> 
> The ones that are 2x+ faster when multi-threaded are filling those bubbles more, though even ones that are faster are still pretty bubble-filled (postnet): image (each of those dispatch 48's are ~2.3ms)
> 
> So nothing related to this PR (I think) - but good to see room for improvement, and improvements like this will only make these issues easier to spot and fix! Great work everyone!

Pretty surprised by it. Way back when had the distributions worked out to be fairly uniform. I think those might have regressed. Ill try to see whats happening cause such a workgroup count is not expected. Maybe missed something with latest refactoring. Fixing a few other things, so should be able to take a look in a few days.

**Comment by antiagainst** [comment]
Nice work, Hanhan!

**Comment by mariecwhite** [comment]
Woweee! Nice work Hanhan.

**Pull request merged**
