### PR TITLE
Refactor and creates Flow/Utils library

### PR DESCRIPTION
**Pull request by asaadaldien**
This pulls in common code needed at both Flow::dispatch and codegen into a flow library. Its a medium term solution to gather common methods before we use op interfaces.

### CODE REVIEW

**Comment by benvanik** [comment]
hmm this is a lot of boilerplate for a method that's pretty easy to duplicate - long term we should really not have such things in flow at all, and adding things like this is a slippery slope that creates spaghetti dependencies that are hard to kill. Is there anything else you could do (including duplicating the method)?

**Comment by asaadaldien** [comment]
@benvanik This is to avoid duplicating methods (its one method duplicated for now) a follow up to #6609, and an offline discussion with @MaheshRavishankar. The summary of the discussion was (@MaheshRavishankar feel free to correct me :) )
"We will need this to host some c++ methods, they will hold linalg op properties needed at both flow and codegen. The long term solution is to have op interfaces but we don't want to not subscribe early since interfaces feature still under development in core."

**Comment by MaheshRavishankar** [comment]
> hmm this is a lot of boilerplate for a method that's pretty easy to duplicate - long term we should really not have such things in flow at all, and adding things like this is a slippery slope that creates spaghetti dependencies that are hard to kill. Is there anything else you could do (including duplicating the method)?

True, thats why it is duplicated today. But it also means that if you update one, you need to update the other. It does add a dependency from Flow To HAL, (which probably already exists), but I'll leave it to you to decide if you want this or not.

**Comment by asaadaldien** [comment]
IMO lets drop this PR, one duplicated method is fine and not hard to maintain, more than one it gets harder. 
By the time we need to duplicate more than one method we can move to interfaces.

**Comment by benvanik** [comment]
Yeah... :(

Design-wise, flow should really know nothing about linalg (flow is meant to be agnostic to what is lowering into it - it's just an artifact of not having any better place to put the code that the linalg->flow conversion happens mixed in with the other flow transforms) - and codegen should really know nothing about flow (it should only be using hal constructs, but there are some missing ops today). Still work to do to get that all lined up but something we should keep in mind at least to help prevent us from digging deeper - in fact, we _had_ a Flow/Utils/ and deleted it as cleanup, which is why I was sad to see it come back here :P

There's a smell that two completely different parts of the pipeline need this same exact information - is it possible to perform this once and pass down the results via attributes within the IR instead? If this is all just transient and eventually only one place (dispatch formation _or_ config definition) needs it then duplication seems fine for now as deleting one copy is way easier (and more likely to happen) than dismantling a utils library that starts to spider around.

**Comment by benvanik** [comment]
(and maybe if we do need someplace to dump things like this, we name it so it's obvious what the deps are - like LinalgUtil or something - not against having places to dump temporary code, just against ones that can easily turn into dumping grounds that are hard to dismantle :)

**Comment by asaadaldien** [comment]
I don't have a strong opinion in either direction =)
so moving this to `iree/compiler/LinalgUtils/...` ?

**Comment by benvanik** [comment]
iree/compiler/Codegen/Utils/ would be my pick - it already exists

**Comment by asaadaldien** [comment]
@benvanik you don'y mind compiler/Flow to have dependency on compiler/codegen/utils :) ?

**Comment by benvanik** [comment]
I mind - I still think this should just be duplicated ;)
Again, it's a smell that two places in totally different pipelines need this same information - it makes things brittle and couples things that shouldn't be. Sharing the same code just gives the illusion that it's not brittle.

**Comment by MaheshRavishankar** [comment]
> I mind - I still think this should just be duplicated ;)
> Again, it's a smell that two places in totally different pipelines need this same information (about the loop structure formed within the dispatch region) - it makes things brittle and couples things that shouldn't be. Sharing the same code just gives the illusion that it's not brittle.

THen there is nothing to do. Its already duplicated in Flow/HAL.

It is true that two places need the same information. Would be good to address that. Essentially flow is distributing loops "parameterically". Then in HAL the tile sizes used for distribution are set concretely. So it has to know what loops were distributed. There is no way to carry that information right now. Definitely a structural issue to address, but at least pulling information from the same place would make it consistent. Fine with duplicating this for now.

**Comment by benvanik** [comment]
Sorry for being annoying about it - I just really hated the last Flow/Utils/DispatchUtils.h we had (in the MHLO times) - we've been working on this long enough we're starting to repeat :)

**Comment by asaadaldien** [comment]
> > I mind - I still think this should just be duplicated ;)
> > Again, it's a smell that two places in totally different pipelines need this same information (about the loop structure formed within the dispatch region) - it makes things brittle and couples things that shouldn't be. Sharing the same code just gives the illusion that it's not brittle.
> 
> THen there is nothing to do. Its already duplicated in Flow/HAL.
> 
> It is true that two places need the same information. 

The more I think about this the more I realize we just need an interface for it and others iree specific linalg op level information e.g `isRootOp`. Even further tile information can move from injecting information to the IR in a kernel dispatch into a backend specific overloads of these interfaces.

**Comment by benvanik** [comment]
linalg ext may be a good place for the interface - at least keeps linalg-like things together, and is accessible from anywhere you'd want it (and doesn't tie flow/hal to linalg)

**Comment by MaheshRavishankar** [comment]
> linalg ext may be a good place for the interface - at least keeps linalg-like things together, and is accessible from anywhere you'd want it (and doesn't tie flow/hal to linalg)

The `linalg_ext` ops already have an interface for this. (The "partitioned loops" is obtained from the `TiledOpInterface`). Linalg ops dont have that interface. I want to avoid implementing an interface for Linalg ops to bridge this gap right now. I think a bit more data is needed to see how things fit.

**Pull request closed without merging**
