### PR TITLE
Reverting packing added in #6280.

### PR DESCRIPTION
**Pull request by benvanik**
It causes some pretty terrible code on systems with no hardware unaligned
load support and was unrelated to the riscv32 issues we are tracking down.

### CODE REVIEW

**Comment by hcindyl** [comment]
Thanks for following up this! However, we still need to solve the exports.count issue for 32-bit codegen, otherwise we can't reach the exports_ptr. Do we have another way to fix the 32-bit padding alignment?

**Comment by benvanik** [comment]
I believe the issue was the typo here:
https://github.com/google/iree/pull/6280/files#diff-992a81b6daf04ffc54239d6e3b028feb279784a2c6a435776a3de3b14fb7635eL46-R46

On 64-bit systems (with 8-byte alignment) things would have been fine, but on 32-bit systems things would be 4 bytes off like you saw in your debugging. So (hopefully) it should be fixed here.

**Comment by hcindyl** [comment]
Ahh... Got it. I thought this PR is a complete revert. Let me test it quickly on RV32 and see how it looks like.

**Comment by hcindyl** [comment]
> Ahh... Got it. I thought this PR is a complete revert. Let me test it quickly on RV32 and see how it looks like.

exports.count is correct. Fails on segfault :)

**Review by hcindyl — APPROVED** [review]

**Comment by benvanik** [comment]
> exports.count is correct. Fails on segfault :)

Yay! Boo!

**Pull request merged**
