### PR TITLE
[NFC] Make flags more descriptive

### PR DESCRIPTION
**Pull request by hanhanW**
Fixes https://github.com/google/iree/issues/3248

### CODE REVIEW

**Comment by hanhanW** [comment]
We can consider to update flag names in iree-run-mlir. I didn't do it because the style there looks different. Do we want to replace `--input-values` with `--function-inputs` for it?

**Comment by antiagainst** [comment]
Could you also update the flags in iree-run-module-vulkan-gui-main.cc and build_apk.sh? They are newly added files. :) It would be nice to perform a grep to make sure there are no others left. 

iree-run-mlir uses cli parsing from LLVM and it's following LLVM style (using `-` instead of `_`). It would also be nice to unify the words used in options there though. But it can happen as another pull request.

**Review by antiagainst — CHANGES_REQUESTED** [review]
We also need to update flags in iree-run-module-vulkan-gui-main.cc and build_apk.sh.

**Comment by hanhanW** [comment]
I updated iree-run-module-vulkan-gui-main.cc and build_apk.sh, thanks for pointing them out!

New finding:

1) Serialization in tf_test_utils.py, ie, creating flagfile
2) I think `iree-check-module-main.cc` has the same context, so also change the variable naming there, although it doesn't have flags.

**Review by phoenix-meadowlark — COMMENTED** [review]
The modifications to the benchmarking readme and tensorflow integrations LTGM!

**Review by GMNGeoffrey — APPROVED** [review]

**Review by antiagainst — APPROVED** [review]

**Pull request merged**
