### PR TITLE
Tie Linalg ops result storage to operand storage when possible

### PR DESCRIPTION
**Pull request by antiagainst**
This allows us to handle reductions represented as linalg.generic
ops. With it, we can fully compile MobileNet v2 on the new 
tensor path. :)

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]
Awesome!

**Review by hanhanW — APPROVED** [review]
Nice! I just started to look into the issue.

I'm surprised that you didn't hit the issue in ConvertToGPUPass when there is a linalg.copy + linalg.generic. The result of dispatch_linalg_on_tensors looks the same as what I have locally...

**Comment by antiagainst** [comment]
> Nice! I just started to look into the issue.
> 
> I'm surprised that you didn't hit the issue in ConvertToGPUPass when there is a linalg.copy + linalg.generic. 



I hit that issue actually. But this fix addressed it. :) By tying to the same buffer, we don't need the linalg.copy anymore.

> The result of dispatch_linalg_on_tensors looks the same as what I have locally...

They shouldn't be the same. Note that for the second `flow.dispatch.workgroups`, we have `-> %[FILL]]` to mean tying buffers.

**Comment by hanhanW** [comment]
> > Nice! I just started to look into the issue.
> > I'm surprised that you didn't hit the issue in ConvertToGPUPass when there is a linalg.copy + linalg.generic.
> 
> I hit that issue actually. But this fix addressed it. :) By tying to the same buffer, we don't need the linalg.copy anymore.
> 
> > The result of dispatch_linalg_on_tensors looks the same as what I have locally...
> 
> They shouldn't be the same. Note that for the second `flow.dispatch.workgroups`, we have `-> %[FILL]]` to mean tying buffers.

Ah yes, my golden eyes were not working well. I didn't find the difference.

**Pull request merged**
