### PR TITLE
Rename func to func.func in mlir files

### PR DESCRIPTION
**Pull request by ThomasRaoux**
This is in order to adapt to upstream changes regarding FuncOp

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]
Assuming this is mostly manual replace. LGTM if CI passes! Thanks!

**Review by GMNGeoffrey — APPROVED** [review]
> Assuming this is mostly manual replace. LGTM if CI passes! Thanks!

I'm really hoping it wasn't manual :stuck_out_tongue: LGTM assuming this is basically just `s/func/func.func/`. If there's anything non-mechanical, please highlight it in the PR description

**Comment by ThomasRaoux** [comment]
It is mostly grep replace, it is a bit more complicated than `s/func/func.func/` since the printer still prints `func` and not `func.func` so the CHECKs cannot be changed

**Comment by ThomasRaoux** [comment]
but no manual changes

**Review by antiagainst — APPROVED** [review]
Nice, thanks!

**Pull request merged**
