### PR TITLE
Cherry-pick math.ctlz to SPIR-V conversion fix for Adreno GPUs

### PR DESCRIPTION
**Pull request by antiagainst**
This commit cherry-picks the following MLIR commit
* [mlir][spirv] Fix math.ctlz for full zero bit cases

that works around an Adreno driver issue:
https://buildkite.com/iree/iree-test-android/builds/6482#01815f05-3926-466f-822a-1e20299e5461

### CODE REVIEW

**Comment by antiagainst** [comment]
Android buildkite test job: https://buildkite.com/iree/iree-test-android/builds/6503

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by antiagainst** [comment]
Okay https://github.com/google/iree/pull/9490 works but this one fails. They cherry-picked the same fix. Weird..

**Comment by antiagainst** [comment]
Another try: https://buildkite.com/iree/iree-test-android/builds/6504

**Comment by antiagainst** [comment]
This is strange. I'll look at it later. For now I'll disable the test https://github.com/google/iree/pull/9509.

**Pull request closed without merging**
