### PR TITLE
Disable tests and benchmark on S20 phone.

### PR DESCRIPTION
**Pull request by ThomasRaoux**
The phone is currently offline.

### CODE REVIEW

**Review by GMNGeoffrey — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
There's no reason to run Kokoro for this (these yml files don't affect it) and it got upset by the force push

**Comment by ThomasRaoux** [comment]
> There's no reason to run Kokoro for this (these yml files don't affect it) and it got upset by the force push

Thanks, I would have done it but I don’t have the force push permission.

**Comment by GMNGeoffrey** [comment]
Yeah wasn't a criticism of you :-) I just like to leave a note when I exercise my admin powers

**Comment by ThomasRaoux** [comment]
> Yeah wasn't a criticism of you :-) I just like to leave a note when I exercise my admin powers

💪

**Pull request merged**
