### PR TITLE
Bump cmake to 3.16.3.

### PR DESCRIPTION
**Pull request by stellaraccident**
* The thing that tipped it was lack of NumPy configuration in 3.13.
* Picked 3.16.3 because it is deployed with Ubuntu 20.04LTS, which at least gives it a pretty big fanout with respect to use (more as a "hey, this gets used a lot and may be ok" vs "we need to pin to Ubuntu").

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]
👍 LGTM if CI builds pass

**Review by GMNGeoffrey — CHANGES_REQUESTED** [review]
I think if we should wait to see if anyone responds on https://groups.google.com/g/iree-discuss/c/IAOSsqn6hcc. It is a Friday afternoon. And it shouldn't be too bad to continue developing on top of this

**Comment by stellaraccident** [comment]
> I think if we should wait to see if anyone responds on https://groups.google.com/g/iree-discuss/c/IAOSsqn6hcc. It is a Friday afternoon. And it shouldn't be too bad to continue developing on top of this

I do need to get the dependent https://github.com/google/iree/pull/7178 landed first thing Monday so I can get it pulled internally to continue work on the internal-google side. So tonight or first thing Monday. Really non optional either way.

**Comment by benvanik** [comment]
Ship it!

**Pull request merged**
