### PR TITLE
Update GitHub Actions workflows to reference new branch names.

### PR DESCRIPTION
**Pull request by ScottTodd**
https://github.com/google/iree/blob/main/.github/workflows/update_submodules.yml will also need updating.

### CODE REVIEW

**Comment by antiagainst** [comment]
I assume now we don't need to tag it with `ready to pull` and we can click the merge button ?

**Comment by GMNGeoffrey** [comment]
> [/.github/workflows/update_submodules.yml@`main`](https://github.com/google/iree/blob/main/.github/workflows/update_submodules.yml?rgh-link-date=2020-06-26T22%3A50%3A19Z) will also need updating.

I don't think we should change that one. We should probably just rename it to "update_tf.yml", but I think TF integration should stay on the google branch.

**Comment by GMNGeoffrey** [comment]
> I assume now we don't need to tag it with `ready to pull` and we can click the merge button ?

Correct. I think we should generally let the author merge though unless they ask someone else to merge for them. Also it should be "squash and merge" not "merge pull request", which is reserved for merging in something with useful history (like the `google` branch).

**Comment by ScottTodd** [comment]
> > [/.github/workflows/update_submodules.yml@`main`](https://github.com/google/iree/blob/main/.github/workflows/update_submodules.yml?rgh-link-date=2020-06-26T22%3A50%3A19Z) will also need updating.
> 
> I don't think we should change that one. We should probably just rename it to "update_tf.yml", but I think TF integration should stay on the google branch.

Right, it should run on the `google` branch. It looks like it will run on the default branch right now. Looks like we should set `ref` in `actions/checkout`

**Comment by GMNGeoffrey** [comment]
> > > [/.github/workflows/update_submodules.yml@`main`](https://github.com/google/iree/blob/main/.github/workflows/update_submodules.yml?rgh-link-date=2020-06-26T23%3A03%3A17Z) will also need updating.
> > 
> > 
> > I don't think we should change that one. We should probably just rename it to "update_tf.yml", but I think TF integration should stay on the google branch.
> 
> Right, it should run on the `google` branch. It looks like it will run on the default branch right now. Looks like we should set `ref` in `actions/checkout`

Ah right right. Yeah I'll fix that and also rename the file.

**Pull request merged**
