### PR TITLE
Enable MobilerBert test on vulkan.

### PR DESCRIPTION
**Pull request by hanhanW**
There was an issue #3507, and it's fixed in #3517

### CODE REVIEW

**Comment by phoenix-meadowlark** [comment]
Hmm, this is passing at in OSS at head in `main` for you? I just ran this test at 8cc22a3ec41039b8642e35362abd034823dd2116 and it ended in a mangled stack trace with `signal 11`. All other vulkan e2e tests are passing.

**Comment by hanhanW** [comment]
> Hmm, this is passing at in OSS at head in `main` for you? I just ran this test at [8cc22a3](https://github.com/google/iree/commit/8cc22a3ec41039b8642e35362abd034823dd2116) and it ended in a mangled stack trace with `signal 11`. All other vulkan e2e tests are passing.

Weird... this is passing on my machine at [8cc22a3](https://github.com/google/iree/commit/8cc22a3ec41039b8642e35362abd034823dd2116). I checked that I don't see "dirty" in submodule. The issue was resolved with Ben's patch.

The command I ran is: `bazel run -c opt //integrations/tensorflow/e2e:mobile_bert_squad_tests_failing__mobile_bert_squad_test__target_backends__iree_vulkan`

**Comment by phoenix-meadowlark** [comment]
Yeah I tried running and testing it with and without `-c opt` and it still fails. Are you using a real GPU, or swiftshader? Also, could you make a temporary commit that removes the `"nokokoro"` tag from the test suite to see how it behaves in one of the docker containers?

**Comment by hanhanW** [comment]
I'm using a real GPU. Removed the tag for testing.

**Comment by hanhanW** [comment]
I built swiftshader myself and can get the same error. We're focusing on real GPU, and it would be great if we can let others know that it's working on GPU. Since this only fails on SwiftShader and the CI won't test it, I think we can still enable the test and file an issue to track it. What do you think? Will it fail on internal TAP test?

**Comment by GMNGeoffrey** [comment]
Internally we use swiftshader for vulkan testing. Can you check if this also works internally? In that case it's just external swiftshader, which is weird. Could be a version difference. We could update the swiftshader commit we use if that's the case.

**Comment by hanhanW** [comment]
> Internally we use swiftshader for vulkan testing. Can you check if this also works internally? In that case it's just external swiftshader, which is weird. Could be a version difference. We could update the swiftshader commit we use if that's the case.

Tested internally and it works. It's working with a real GPU and internal SwiftShader, but not external SwiftShader. I bumped the SwiftShader to latest and it's passing. I will create a #3561  to update the SwiftShader, and let's land this in the meantime? I'm happy to wait until the submodule is bumped if there are other concerns.

**Comment by GMNGeoffrey** [comment]
> > Internally we use swiftshader for vulkan testing. Can you check if this also works internally? In that case it's just external swiftshader, which is weird. Could be a version difference. We could update the swiftshader commit we use if that's the case.
> 
> Tested internally and it works. It's working with a real GPU and internal SwiftShader, but not external SwiftShader. I bumped the SwiftShader to latest and it's passing. I created #3561 to update the SwiftShader, and let's land this in the meantime? I'm happy to wait until the submodule is bumped if there are other concerns.

My vote is to make it work everywhere first, but I'd also be ok submitting this first as long as it doesn't break CI

**Review by phoenix-meadowlark — APPROVED** [review]
The vulkan test passes on kokoro (it was tf vs tf that failed due to a network error), so I'd say this is good to submit once the nokokoro tag is added back :)

*Edit*: GitHub didn't show me the previous two comments when I went to comment.

**Comment by hanhanW** [comment]
Thanks, I think it's not breaking anything, so it's okay to land this. I'll rebuild the docker images and update it in a follow up.

**Comment by antiagainst** [comment]
@hanhanW: please hold on touching the docker images. I'm on it at the moment: https://github.com/antiagainst/iree/commit/295591382919c1fa9d29b770df2a33b6d2c5ce02

**Comment by hanhanW** [comment]
> @hanhanW: please hold on touching the docker images. I'm on it at the moment: [antiagainst@2955913](https://github.com/antiagainst/iree/commit/295591382919c1fa9d29b770df2a33b6d2c5ce02)

Got you, thanks!

**Pull request merged**
