### PR TITLE
Enable bulding iree::vm via CMake...

### PR DESCRIPTION
**Pull request by marbre**
…, even though IREE_BUILD_COMPILER is set to OFF.

So far, `iree-tblgen` was only build with `IREE_BUILD_COMPILER=ON`. Further, `TableGen.cmake` is part of llvm and therefore was only available with `IREE_BUILD_COMPILER=ON`.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Looks like this causes build failures because of a conflict between `third_party/llvm-project/llvm/utils/benchmark` and `third_party/benchmark`

> CMake Error at third_party/benchmark/src/CMakeLists.txt:20 (add_library):
> add_library cannot create target "benchmark" because another target with the same name already exists.  The existing target is a static library created in source directory
> "/home/runner/work/iree/iree/third_party/llvm-project/llvm/utils/benchmark/src".
> See documentation for policy CMP0002 for more details.

**Comment by marbre** [comment]
Hm, cmake 3.14.6 passed on my machine and as far as I can see LLVM benchmark should not be build (see [iree_copts.cmake](https://github.com/google/iree/blob/master/build_tools/cmake/iree_copts.cmake#L113)). Will take a closer look after fixing some other issues with the CMake build.

**Comment by marbre** [comment]
`iree:vm` was replaced by `iree:vm2` with commit 97a824f. Hence, the former `iree:vm2` is enabled anyway. I assume that these changes can therefore be safely merged. If we still have build failures we should comment out https://github.com/google/iree/blob/master/CMakeLists.txt#L110 any fix that afterwards.

**Comment by GMNGeoffrey** [comment]
I'm not sure I follow. I think we should not merge this until the cmake presubmit is passing. The build current passes at HEAD. The CI builds with CMake 3.12 IIRC, which may be the difference we're seeing.

**Comment by marbre** [comment]
With `iree:vm2` being renamed to `iree:vm`, the build definitely fails. `iree:vm2` requires tablegen, but as it is enabled anyway the build can't pass. That is why i have removed the `add_subdirectory(vm2)`, since it is enabled by replacing the old VM. See for example the build status of PR #354:
```
CMake Error at build_tools/cmake/iree_tablegen_library.cmake:50 (tablegen):
  Unknown CMake command "tablegen".
Call Stack (most recent call first):
  iree/vm/CMakeLists.txt:92 (iree_tablegen_library)
```
Also this might not fix all build failures, this add least makes the `tablegen` command available.

**Comment by GMNGeoffrey** [comment]
I think you're building more than the CI does right now. All I'm looking at is what the GitHub action builds, which is currently `cmake -DIREE_BUILD_COMPILER=OFF -DIREE_BUILD_TESTS=ON -DIREE_BUILD_SAMPLES=OFF -DIREE_BUILD_DEBUGGER=OFF ..` Admittedly, that's not much, but in terms of having a set of things that builds and then expanding it, I'm a proponent of keeping that working so it can continue to check incoming PRs and then expanding the set of things that can build. Speaking of, if at any point you're able to build more than that (e.g. it sounds like you've been building the compiler as well? Please send a PR to add it to the CI so we can do a better job of keeping it green/tracking where it fails).

**Comment by marbre** [comment]
Please see the build status of my other PR https://github.com/google/iree/pull/354/checks?check_run_id=371319998 or even the build status of the most recent commit in the master https://github.com/google/iree/runs/371259330. The build is currently failing, because of commit 97a824f. This moved all the `vm2` code to `vm`. ATM `add_subdirectory(vm)` is in the main `CMakeLists.txt` and thus the build fails.

I totally agree that the build status should always kept green once achieved! However, it is currently not and this PR provides at least a partial fix on the way back to a passing build.

Prior to the changes before the Christmas days, I was able to build without failure with the default CMake configuration (`IREE_BUILD_COMPILER` and `IREE_BUILD_SAMPLES` both set to `ON`). So I really hope that we can restore that state asap, but at the moment I am struggling with the transition of MLIR to LLVM.

**Comment by GMNGeoffrey** [comment]
Yeah I also realized this when the CMake build failed on my own PR. For some reason the action hasn't run on master since https://github.com/google/iree/commit/c19a6ef4a1ea827267dab66516ccba2019336387. My latest push triggered another run. Sorry for the mistake!

We're trying to get on top of the MLIR move as well and should hopefully get everything stable again by the end of the week.

Agreed that since the build is already broken and this gets us in a more stable state, it's reasonable to merge it as-is. And once we've got things working again, let's turn on the compiler and samples as part of the action so we can keep them green :-)

**Comment by benvanik** [comment]
Geoffrey just reminded me I am using tblgen in the runtime to generate the opcode table:
https://github.com/google/iree/blob/master/iree/compiler/Dialect/VM/Tools/VMOpTableGen.cpp#L53-L82

It'd be nice to have this output checked in such that tablegen would not be required for pure runtime builds. For now, to get things green, we can just require the COMPILER=ON and I'll file an issue.

**Comment by benvanik** [comment]
Filed #357 to track making the runtime work without building LLVM.

**Comment by marbre** [comment]
> For now, to get things green, we can just require the COMPILER=ON and I'll file an issue.

Okay, that we can just skip this PR if tablegen should not be an requirement in the future.

**Comment by marbre** [comment]
Closing this. @GMNGeoffrey Could you please set `COMPILER=ON` for the CMake pre-submit build?

**Pull request closed without merging**
