### PR TITLE
Update docs following LLVM AOT linker cleanup.

### PR DESCRIPTION
**Pull request by ScottTodd**
Progress on https://github.com/google/iree/issues/4606

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by ScottTodd** [comment]
@phoenix-meadowlark when you get a chance, can you test pyiree/jax on this branch without the `IREE_LLVMAOT_LINKER_PATH` environment variable?

**Comment by phoenix-meadowlark** [comment]
> @phoenix-meadowlark when you get a chance, can you test pyiree/jax on this branch without the `IREE_LLVMAOT_LINKER_PATH` environment variable?

Building ⚒️

**Comment by phoenix-meadowlark** [comment]
Running the code block as you modified it gives the following compilation error:

```
Diagnostics:
/usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
/usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: error adding symbols: file in wrong format
Linking failed; command line returned exit code 256:

/usr/bin/ld -shared -o /tmp/_stdin__linked_llvm_aot-a1e5fc.so /tmp/_stdin__linked_llvm_aot-a1e5fc.obj

<stdin>:1:1: error: failed to link executable and generate target dylib using linker toolchain /usr/bin/ld
"module"() ( {
^
<stdin>:1:1: error: failed to serialize op to target backend dylib*
"module"() ( {
^
<stdin>:1:1: note: see current operation: "hal.executable.target"() ( {
```

For reference I have `ANDROID_NDK=/usr/local/google/home/meadowlark/android-ndk-r22` in my environment.

**Comment by ScottTodd** [comment]
> Running the code block as you modified it gives the following compilation error:
> 
> ```
> Diagnostics:
> /usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
> /usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
> /usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
> /usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
> /usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
> /usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: Relocations in generic ELF (EM: 183)
> /usr/bin/ld: /tmp/_stdin__linked_llvm_aot-a1e5fc.obj: error adding symbols: file in wrong format
> Linking failed; command line returned exit code 256:
> 
> /usr/bin/ld -shared -o /tmp/_stdin__linked_llvm_aot-a1e5fc.so /tmp/_stdin__linked_llvm_aot-a1e5fc.obj
> 
> <stdin>:1:1: error: failed to link executable and generate target dylib using linker toolchain /usr/bin/ld
> "module"() ( {
> ^
> <stdin>:1:1: error: failed to serialize op to target backend dylib*
> "module"() ( {
> ^
> <stdin>:1:1: note: see current operation: "hal.executable.target"() ( {
> ```
> 
> For reference I have `ANDROID_NDK=/usr/local/google/home/meadowlark/android-ndk-r22` in my environment.

Hmm.. what about with `-iree-llvm-target-triple=aarch64-none-linux-android29`?

**Comment by ScottTodd** [comment]
Also note that this PR is based on https://github.com/google/iree/tree/benvanik-android-linking, which has the real code changes here.

**Comment by phoenix-meadowlark** [comment]
> Also note that this PR is based on https://github.com/google/iree/tree/benvanik-android-linking, which has the real code changes here.

That compiles without an error. let me check execution on a phone.

**Comment by ScottTodd** [comment]
Bleh GitHub. This will need to be re-opened and merged into `main` now :P

**Pull request closed without merging**
