### PR TITLE
Merge google -> main

### PR DESCRIPTION
**Pull request by ThomasRaoux**
* a8c20a5b0 Merge pull request #5622 from ThomasRaoux:main-to-google
* bee1c393c Integrate LLVM at llvm/llvm-project@535df472b042
* 7642426b0 Synchronize submodules with LLVM at llvm/llvm-project@caea37b37e6a
* 44da34b6c Integrate LLVM at llvm/llvm-project@caea37b37e6a

### CODE REVIEW

**Review by GMNGeoffrey — CHANGES_REQUESTED** [review]
This is currently pointing at a commit that is not present on the google branch

**Comment by ThomasRaoux** [comment]
> This is currently pointing at a commit that is not present on the google branch

Yeah sorry for the mess, this is fixed

**Review by GMNGeoffrey — APPROVED** [review]
Do you also want to pull in https://github.com/google/iree/commit/25ba8cbf04317abfe582ba8eb2dee7a1436733c5 ?

**Comment by ThomasRaoux** [comment]
> Do you also want to pull in [25ba8cb](https://github.com/google/iree/commit/25ba8cbf04317abfe582ba8eb2dee7a1436733c5) ?

Yeah, otherwise lint will fail

**Comment by GMNGeoffrey** [comment]
> > Do you also want to pull in [25ba8cb](https://github.com/google/iree/commit/25ba8cbf04317abfe582ba8eb2dee7a1436733c5) ?
> 
> Yeah, otherwise lint will fail

But lint didn't fail :slightly_smiling_face: that's also why I was confused about that change. But currently it's not part of this PR

**Comment by GMNGeoffrey** [comment]
> > > Do you also want to pull in [25ba8cb](https://github.com/google/iree/commit/25ba8cbf04317abfe582ba8eb2dee7a1436733c5) ?
> > 
> > 
> > Yeah, otherwise lint will fail
> 
> But lint didn't fail  that's also why I was confused about that change. But currently it's not part of this PR

Or maybe it is. I didn't see it before, but now I'm confused. Anyway ignore me

**Pull request merged**
