### PR TITLE
Add support to capture Tracy traces when benchmarking

### PR DESCRIPTION
**Pull request by antiagainst**
This commit adds logic to perform Tracy captures after running
each benchmark. It allows us to have more details regarding
the benchmark to investigate performance regressions, etc.

### CODE REVIEW

**Comment by antiagainst** [comment]
@benvanik: What you've asked for. :) If you follow the "Buildkite build" link in the above, the captures are in the "Artifacts" tab for each phone:

buildkite-captures

**Comment by benvanik** [comment]
Whoa neat!!!

Wonder if we can zip them up with a different tool? right now the names get truncated:
image

since the tracy files are already compressed we could also avoid compression (either zip with 0 level or just tar, if we can get the long file names):
image

**Comment by antiagainst** [comment]
> Wonder if we can zip them up with a different tool? right now the names get truncated:

Is this a Windows long filename issue? I don't see them truncated on Linux/macOS. What tools will circumvent that do you know?

**Comment by ScottTodd** [comment]
> > Wonder if we can zip them up with a different tool? right now the names get truncated:
> 
> Is this a Windows long filename issue? I don't see them truncated on Linux/macOS. What tools will circumvent that do you know?

Seems to be an issue with the 7-Zip program ? If I view or extract with 7zip I get file names truncated to 100 characters:
image

If I extract on the command line with `tar -xf`, I get full file names: 
image

**Comment by benvanik** [comment]
weird - it could be 7zip - let me try some other ones!

**Comment by ScottTodd** [comment]
Try WinRAR? :P

**Comment by antiagainst** [comment]
So many choices on Windows. ;-P

**Comment by benvanik** [comment]
Latest 7zip works :P 
image

**Comment by ScottTodd** [comment]
Hah! I was looking forward to writing off a WinRAR license as a business expense :D

**Comment by benvanik** [comment]
Was trying to see if tracy's capture tool had different compression settings but doesn't seem like they are exposed - there's some that could lead to smaller traces but probably not worth it for now.

To clarify for this PR, does this capture traces on all benchmarks now? or does it run benchmarks to get the numbers, then run again to get the traces? (tracing does add overhead that we don't want showing in our bottom line numbers)

**Comment by antiagainst** [comment]
@benvanik:

> To clarify for this PR, does this capture traces on all benchmarks now? or does it run benchmarks to get the numbers, then run again to get the traces? (tracing does add overhead that we don't want showing in our bottom line numbers)

First the normal benchmark run (with an `iree-benchmark-module` w/o tracing compiled in) and then the capture run (with an `iree-benchmark-module` with tracing compiled in). So yeah the normal numbers reported shouldn't be affected.

**Review by benvanik — APPROVED** [review]

**Pull request merged**
