### PR TITLE
Add gpu dialect to the dependency of CUDA target

### PR DESCRIPTION
**Pull request by ThomasRaoux**

### CODE REVIEW

**Comment by ThomasRaoux** [comment]
This solve the build failure when CUDA is enabled but Vulkan is not. When Vulkan is on the gpu dialect gets loaded thanks to this:
https://github.com/google/iree/blob/accc5230038a55a02584239478a2addaf7b462cc/iree/compiler/Dialect/Vulkan/IR/VulkanDialect.cpp#L25

I'm not completely sure this is the right fix, the problem seems to be related to commit https://github.com/google/iree/commit/ebc5eb5f72813138ec454c62d3ac5cc7f043a275 that limit the dialect being loaded so I assume this is the right thing to do as we want gpu dialect to be loaded when the backend is CUDA.

**Review by GMNGeoffrey — CHANGES_REQUESTED** [review]
Hmmm this shouldn't be necessary. It looks like https://github.com/google/iree/commit/ebc5eb5f72813138ec454c62d3ac5cc7f043a275 broke the behavior of recursively registering dialects as part of a nested pipeline in TranslateExecutablesPass. I added that in https://github.com/google/iree/pull/3741. I guess there were issues with memory usage? Even if we don't persist them, I think we still need to create the pipeline and get all of its dependent dialects before running it.

**Comment by ThomasRaoux** [comment]
> Hmmm this shouldn't be necessary. It looks like [ebc5eb5](https://github.com/google/iree/commit/ebc5eb5f72813138ec454c62d3ac5cc7f043a275) broke the behavior of recursively registering dialects as part of a nested pipeline in TranslateExecutablesPass. I added that in #3741. I guess there were issues with memory usage? Even if we don't persist them, I think we still need to create the pipeline and get all of its dependent dialects before running it.

Based on discord discussion I moved the gpu dialect loading away from Vulkan dialect to make such issue easier to catch but looks like we don't have way to make a more robust solution.

**Review by GMNGeoffrey — APPROVED** [review]
Confirmed that there doesn't seem to be any reason that the Vulkan Dialect should depend on the GPU Dialect (no other references to GPU dialect entities in canonicalizers or other dialect-attached things).

I guess registering all possible dialects on target backends is the way we do it now :-/

**Comment by ThomasRaoux** [comment]
> Confirmed that there doesn't seem to be any reason that the Vulkan Dialect should depend on the GPU Dialect (no other references to GPU dialect entities in canonicalizers or other dialect-attached things).
> 
> I guess registering all possible dialects on target backends is the way we do it now :-/

Yes, not the most elegant patch :|, thanks for looking at it

**Pull request merged**
