### PR TITLE
Bump flatcc version

### PR DESCRIPTION
**Pull request by hcindyl**
Resolve fallthrough warning in RISC-V cross-compilation.

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by hcindyl** [comment]
Before:
https://source.cloud.google.com/results/invocations/80cdd80a-eeff-49b1-a04b-903637bfc742/targets/iree%2Fgcp_ubuntu%2Fcmake%2Fbaremetal%2Friscv32%2Fmain/log
(target [107/154])

After:
https://source.cloud.google.com/results/invocations/726f724c-e3f5-4340-9b7d-d2d1b148534a/targets/iree%2Fgcp_ubuntu%2Fcmake%2Fbaremetal%2Friscv32%2Fpresubmit/log

**Comment by benvanik** [comment]
This has been silently bothering me for ages - thanks :)

**Comment by hcindyl** [comment]
Unfortunately, another warning message seems to pop up because of https://github.com/dvidelabs/flatcc/pull/199. A fix for another day.

**Comment by hcindyl** [comment]
> Unfortunately, another warning message seems to pop up because of [dvidelabs/flatcc#199](https://github.com/dvidelabs/flatcc/pull/199). A fix for another day.

The error message here seems to be clang version dependent. When I build with Debian test branch (Debian 11) and Clang 11, it doesn't show the warning. However, the CI robot is on Ubuntu18.04 and Clang 6. Maybe we need to bump the CI OS version?

**Comment by GMNGeoffrey** [comment]
We deliberately use the oldest supported tooling on the CI (although in https://github.com/google/iree/issues/6849 I note that we could use the newest supported in cases where we have additional builds)

**Pull request merged**
