### PR TITLE
Add submodule for Google benchmark

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
We will use this for writing benchmarks of IREE. The dependency should be limited to the benchmarking code.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Hmmm so I'm confused about this error:

```
Run git clone https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE --no-checkout --no-tags
  git clone https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE --no-checkout --no-tags
  git checkout $GITHUB_SHA
  shell: /bin/bash -e {0}
Cloning into '/home/runner/work/iree/iree'...
fatal: reference is not a tree: 878dbb61141a3d91c59f419f5ea5c99d8f75c387
##[error]Process completed with exit code 128.
```

I'm assuming this is because somehow I screwed up the submodule, but that commit hash is not referenced anywhere AFAICT. Running `git submodule update` works fine for me locally. I wonder if this has to do with my use of the populate_reference_repo script?

**Comment by stellaraccident** [comment]
Dup?

**Comment by GMNGeoffrey** [comment]
Yeah this one was failing with a mysterious error about being unable to clone on the CI and I wasn't sure if my repo was corrupted or something so I tried again from a clean repo. That had the same errors though.

**Comment by stellaraccident** [comment]
Can you share the exact git commands you are using?

**Comment by GMNGeoffrey** [comment]
To do what? To create this PR I just used `git add submodule`. The error is in the CI

**Comment by GMNGeoffrey** [comment]
Ah it looks like this failure has been happening for a while, e.g. here's a PR before mine with the same issue https://github.com/google/iree/pull/80/checks?check_run_id=268891759

**Comment by GMNGeoffrey** [comment]
In fact, I don't think this check has ever worked: https://github.com/google/iree/pull/62/checks

**Comment by stellaraccident** [comment]
Sorry, I misunderstood: I thought you were saying that you were having trouble cloning with this patch in place. Yes, that ci check has been broken and should probably be disabled, if not ready to fix. I haven't looked into it but please feel free.

**Comment by ScottTodd** [comment]
Yes, the checks on GitHub aren't fully configured yet.

**Comment by GMNGeoffrey** [comment]
Filed https://github.com/google/iree/issues/85

**Pull request closed without merging**
