### PR TITLE
Add support for saving mid level IR to a file.

### PR DESCRIPTION
**Pull request by hanhanW**
Fixes https://github.com/google/iree/issues/6412

### CODE REVIEW

**Comment by benvanik** [comment]
minor bikeshedding, but could you rename this to mhlo instead of mid? "mid" is very ambiguous in a full pipeline (is linalg after tf/mhlo and before the rest of IREE mid? is the HAL between flow/vm mid? etc) and it'd make it easier to tell people to "get the mhlo output" and find the right flag if there didn't need to be that glossary lookup each time

**Comment by benvanik** [comment]
(if everyone who would use this knows what it means that's fine - but I'll never remember :)

**Comment by hanhanW** [comment]
I'm fine with both. We name it as mid level IR because mhlo is not accurate. Because some things are lowered directly from TF to Linalg/tensors/std dialects. From frontend perspective, it is mid level I think. Most of operations are mhlo ops at this stage, so mhlo level also makes sense to me.

**Comment by benvanik** [comment]
Ah I forgot about the bypassing of mhlo - then maybe mid is fine - just so long as someone remembers :)

**Review by stellaraccident — APPROVED** [review]

**Pull request merged**
