### PR TITLE
Canonicalize OK status on construction

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
This should fix failing lit tests introduced in 5f24fb57990bc4f9da85bbb050ef509654ed501d.

Currently the ok() method just checks if state is nullptr, but some dynamic construction is creating Ok statuses from the version that accepts arguments, which is causing test failures in OSS.

Tested: Kokoro presubmits

### CODE REVIEW

**Comment by ScottTodd** [comment]
Should https://github.com/google/iree/blob/80569fb0af099f89dac8ea4c1d19cd441fa91166/iree/base/internal/status.h#L110 be updated?

**Comment by GMNGeoffrey** [comment]
> Should
> 
> https://github.com/google/iree/blob/80569fb0af099f89dac8ea4c1d19cd441fa91166/iree/base/internal/status.h#L110
> 
> be updated?

Aren't you supposed to be on vacation? :-D Do you think it should be invalid to construct a status with an explicit OK? In that case we could add the logic in the constructor instead.

**Comment by ScottTodd** [comment]
Since ok is the common case, it's storage size should be kept minimal.

Also yeah, I'm on vacation 😋 I get little bursts of internet access though.

**Comment by GMNGeoffrey** [comment]
Fair enough. I've made it canonicalize to nullptr for an ok status. It looks like we're not using CHECK macros here, but I added an assert that you can't construct an OK status with an empty message.

**Comment by GMNGeoffrey** [comment]
> It looks like we're not using CHECK macros here, but I added an assert that you can't construct an OK status with an empty message.

I took another look at the upstream implementation, and it ignores the message on an OK status. I'm just going to do that instead for consistency.

**Pull request closed without merging**
