### PR TITLE
Fix building iree::compiler::Dialect with CMake

### PR DESCRIPTION
**Pull request by marbre**
After several changes in the source structure, I ported the necessary modifications from the Bazel BUILD files to CMake and further fixed some minor issues/typos.

### CODE REVIEW

**Comment by marbre** [comment]
`iree::compiler::Dialect::VM::Target::Bytecode` currently fails, because `bytecode_module_def_generated.h` cannot be found. It should be generated by `iree::schemas::bytecode_module_def_cc_fbs`, but somehow isn't. Couldn't yet figure out what went wrong.

**Comment by ScottTodd** [comment]
Some of @GMNGeoffrey 's work on continuous integration should help us catch these differences between Bazel and CMake faster, and one of these days someone will get around to writing a script to help with the mirroring...

Thanks for the PRs!

**Comment by marbre** [comment]
Ah by the way, fixed the typo that prohibited the generation of `bytecode_module_def_generated.h`. Just forget to comment again..

**Comment by marbre** [comment]
Fixed conflicts that prevented merging.

**Pull request closed without merging**
