### PR TITLE
Swap Stage 6 and Stage 7 in Codegen Driver

### PR DESCRIPTION
**Pull request by dcaballe**
Shape cast operations are usually no-ops that canonicalize away at some
point in the pipeline. However, if they are not, the codegen driver lowers
them to an inefficient sequence of insert/extract ops. This lowering is
enabled at stage 5 *and later ones* by default. Unfortunately, the AVX2 lowering
for transpose operations (stage 6) generates shape cast operations that
could be canonicalized away but they are immediately lowered to the insert/extract
sequence before canonicalization can happen (the shape cast lowering patterns are
also loaded at stage 6).

This patch introduces a flag to enable/disable the lowering of shape
cast ops. I implemented this mostly to provide context but I think this
is not a good solution. I think we should move the shape cast stage after
the transpose one. Do you see any problem with that?

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
> Shape cast operations are usually no-ops that canonicalize away at some point in the pipeline. However, if they are not, the codegen driver lowers them to an inefficient sequence of insert/extract ops. This lowering is enabled at stage 5 _and later ones_ by default. Unfortunately, the AVX2 lowering for transpose operations (stage 6) generates shape cast operations that could be canonicalized away but they are immediately lowered to the insert/extract sequence before canonicalization can happen (the shape cast lowering patterns are also loaded at stage 6).
> 
> This patch introduces a flag to enable/disable the lowering of shape cast ops. I implemented this mostly to provide context but I think this is not a good solution. I think we should move the shape cast stage after the transpose one. Do you see any problem with that?

This seems like it is side stepping the problem. Issue here is that you want one canonicalization to kick in before others. Maybe we can just order them explicitly (i.e. different calls to `applyPatternsAndFoldGreedily`, one that does the shape cast canonicalization before it gets lowered to something else.

(And of course all this would be easier with transformation dialect).

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Marking as requesting change cause it isnt clear to me what decides when to lower the shape case and when not to (or what would happen if we didnt have the fallback lowering of shape cast)

**Comment by dcaballe** [comment]
> Marking as requesting change cause it isnt clear to me what decides when to lower the shape case and when not to (or what would happen if we didnt have the fallback lowering of shape cast)

If a shape cast is not folded away, the lowering will fail because the op will become illegal when lowering to LLVM. However, according to the shape cast doc, that should never happen: `It is currently assumed that this operation does not require moving data, and that it will be folded away before lowering vector operations.` I'm not sure if that is up to date because, why do we need fallback lowering then? :). As I said, the current implementation is mostly to provide context.

> This seems like it is side stepping the problem. Issue here is that you want one canonicalization to kick in before others. Maybe we can just order them explicitly (i.e. different calls to applyPatternsAndFoldGreedily, one that does the shape cast canonicalization before it gets lowered to something else.

The canonicalization needed happens between stages. The problem is that each stage includes all the patterns of the previous stages. We would have to special case stage 7 to do what you described. Actually, to some extent, what you described is almost equivalent to interchanging stage 6 (shape cast) and stage 7 (transpose lowering), since canonicalization would run between the two and everything would work even if a shape cast is not folded away. However, I don't if that change would have other side effects. I have the impression that having shape casts around shouldn't interfere with the transpose lowering but maybe I'm missing something. Hopefully, @nicolasvasilache can clarify.

To provide a bit more context, the transpose lowering was not generating any shape cast ops until a few weeks ago, when I extended the AVX2 patterns so this issue is relatively new and was not taken into account when the order of the stages was decided.

**Comment by nicolasvasilache** [comment]
The various stages ordering has been determined empirically but without a deep study, I think this is all fine to reshuffle if the data supports it. Still, all these issues will soon go away as we move away from hardcoded C++ ordering.

**Comment by dcaballe** [comment]
I swapped the stages and the problem is fixed locally. I'll add the test in a follow-up PR. I haven't seen any test crashing on the IREE side after the change.

**Comment by hanhanW** [comment]
> all these issues will soon go away as we move away from hardcoded C++ ordering.

Why they will go away when we migrate to transform dialect? I thought it's a scheduling dialect, and we'll have the same order no matter using which approach?

I'm fine with this if it brings performances to our tracking models. My concern is that we're getting diverge from Sandbox. If we're going to update the Sandbox side, that would be great. This change may need some data support.

**Comment by dcaballe** [comment]
To provide a bit more context, you can take a look at the large sequence of insert/extract ops generated before and after the shuffle sequence in this transpose test: https://github.com/google/iree/pull/8750/files#diff-ba78b5a877da6ff11946d24a7a189104482ebc5a1da644817d68fb55e6c68fabR117. Those insert/extract ops are the result of lowering shape cast ops. They also happen for all the tests below that one but I didn't add the CHECKs hoping to get this change in.

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
