### PR TITLE
Fix TF llvm commit path in update_to_llvm_syncpoint.py

### PR DESCRIPTION
**Pull request by hanhanW**
`LLVM_COMMIT` and `LLVM_SHA256` are moved to
third_party/llvm/workspace.bzl in https://github.com/tensorflow/tensorflow/commit/04b5fed45189f6f60523116fcc842caa5fb4dd38

### CODE REVIEW

**Comment by hanhanW** [comment]
I probably have to clone one and push to upstream branch to test.

**Comment by hanhanW** [comment]
> I probably have to clone one and push to upstream branch to test.

This doesn't work. Still seeing

```
Traceback (most recent call last):
  File "./scripts/git/update_to_llvm_syncpoint.py", line 368, in <module>
    main(parse_arguments())
  File "./scripts/git/update_to_llvm_syncpoint.py", line 166, in main
    args.tensorflow_rev)
  File "./scripts/git/update_to_llvm_syncpoint.py", line 302, in find_new_commit_from_version_file
    llvm_commit)
  File "./scripts/git/update_to_llvm_syncpoint.py", line 279, in find_llvm_commit_changes_to_file
    f"{repo_path} {branch} {filepath} does not have any references to LLVM"
RuntimeError: /home/runner/work/iree/iree/third_party/tensorflow origin/master tensorflow/workspace.bzl does not have any references to LLVM commit 6c9541d4ddfdab0dcb11436485b466a759c3126c. Maybe  export is behind?
```

I tested it locally and got

```
WARNING: LLVM commit in TF  does not match that in IREE (ffffffffffffffffffffffffffffffffffffffff vs 7e54d7304be2ddb51b4e8ad5d1b29b103360e4cf)
```

by running

```
$ ./scripts/git/submodule_versions.py init
$ ./scripts/git/update_to_llvm_syncpoint.py
```

**Comment by GMNGeoffrey** [comment]
I can't add inline comments on unchanged lines, but you didn't update all references to that constant. The old constant should be entirely replaced.

**Comment by hanhanW** [comment]
> I can't add inline comments on unchanged lines, but you didn't update all references to that constant. The old constant should be entirely replaced.

I thought that should be the same. Thanks for the comment, it works without errors after replaced it.

**Review by GMNGeoffrey — APPROVED** [review]

**Comment by hanhanW** [comment]
I accidentally added SUBMODULE_VERSION.txt and third_party changes when I tested the script. And you approved on that version.

Does the current version (which only fixes the script) look good to you?

**Review by GMNGeoffrey — APPROVED** [review]
> I accidentally added SUBMODULE_VERSION.txt and third_party changes when I tested the script. And you approved on that version.
> 
> Does the current version (which only fixes the script) look good to you?

Yes :-)

**Pull request merged**
