### PR TITLE
[WIP] Externalized MMT4D experiment.

### PR DESCRIPTION
**Pull request by benvanik**
TBD:
* [ ] Lowering config integration for option
* [ ] Figure out where the heck to externalize

The libmmt4d library skeleton is mostly there. There are likely issues with the terminology/params/etc in the tests/benchmarks - I literally don't know how any of this works and am just guessing :)

I have the compiler portions for turning linalg.mmt4d ops into calls and linking in the appropriate bitcode however I can't figure out where to make the externalization happen. I think I need it to happen after bufferization because I need memrefs, but the tile and vectorize stuff runs on tensors and removes the op no matter what I do (looks like even if I exclude the mmt4d patterns the generic contraction op patterns kick in). Looking for help from @MaheshRavishankar as to how to navigate that code as I can't quite get my head around the pipeline (and variants of it for old code paths). I don't want anything to touch the linalg.mmt4d except to turn it from tensor to memref. Another approach would be to have the externalize work on tensors, but I'm not sure how to make the bufferization (either of them?) handle the extern call like that which is why I was trying to do it afterward.

The IR I'm trying to compile is:
```mlir
#map0 = affine_map<(d0, d1, d2, d3) -> (d0, d2, d1, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map2 = affine_map<(d0, d1, d2, d3) -> (d1, d3, d0, d2)>
module  {
  func @matmul_16x16xi8_times_16x16xi8_into_16x16xi32(%arg0: tensor<16x16xi8>, %arg1: tensor<16x16xi8>, %arg2: tensor<16x16xi32>) -> tensor<16x16xi32> {
    %0 = linalg.tensor_expand_shape %arg0 [[0, 1], [2, 3]] : tensor<16x16xi8> into tensor<2x8x4x4xi8>
    %1 = linalg.tensor_expand_shape %arg1 [[0, 1], [2, 3]] : tensor<16x16xi8> into tensor<4x4x2x8xi8>
    %2 = linalg.tensor_expand_shape %arg2 [[0, 1], [2, 3]] : tensor<16x16xi32> into tensor<2x8x2x8xi32>
    %3 = linalg.init_tensor [2, 4, 8, 4] : tensor<2x4x8x4xi8>
    %4 = linalg.generic {indexing_maps = [#map0, #map1], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%0 : tensor<2x8x4x4xi8>) outs(%3 : tensor<2x4x8x4xi8>) {
    ^bb0(%arg3: i8, %arg4: i8):  // no predecessors
      linalg.yield %arg3 : i8
    } -> tensor<2x4x8x4xi8>
    %5 = linalg.init_tensor [2, 4, 8, 4] : tensor<2x4x8x4xi8>
    %6 = linalg.generic {indexing_maps = [#map2, #map1], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%1 : tensor<4x4x2x8xi8>) outs(%5 : tensor<2x4x8x4xi8>) {
    ^bb0(%arg3: i8, %arg4: i8):  // no predecessors
      linalg.yield %arg3 : i8
    } -> tensor<2x4x8x4xi8>
    %7 = linalg.init_tensor [2, 2, 8, 8] : tensor<2x2x8x8xi32>
    %8 = linalg.generic {indexing_maps = [#map0, #map1], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%2 : tensor<2x8x2x8xi32>) outs(%7 : tensor<2x2x8x8xi32>) {
    ^bb0(%arg3: i32, %arg4: i32):  // no predecessors
      linalg.yield %arg3 : i32
    } -> tensor<2x2x8x8xi32>
    %9 = linalg.mmt4d ins(%4, %6 : tensor<2x4x8x4xi8>, tensor<2x4x8x4xi8>) outs(%8 : tensor<2x2x8x8xi32>) -> tensor<2x2x8x8xi32>
    %10 = linalg.init_tensor [2, 8, 2, 8] : tensor<2x8x2x8xi32>
    %11 = linalg.generic {indexing_maps = [#map0, #map1], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%9 : tensor<2x2x8x8xi32>) outs(%10 : tensor<2x8x2x8xi32>) {
    ^bb0(%arg3: i32, %arg4: i32):  // no predecessors
      linalg.yield %arg3 : i32
    } -> tensor<2x8x2x8xi32>
    %12 = linalg.tensor_collapse_shape %11 [[0, 1], [2, 3]] : tensor<2x8x2x8xi32> into tensor<16x16xi32>
    return %12 : tensor<16x16xi32>
  }
}
```

externalize_mmt4d.mlir shows the simple transformation I'm trying to perform.

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
There are a couple of issues here. Lets resolve the easy ones. You probably dont want to use the tensors -> vectors path here. It seems like you want to "bufferize" early. The current pipelines used in the CPU backend are [here](https://github.com/google/iree/blob/ec9d61fcebe22c5b638115597102ec3698bfe236/iree/compiler/Codegen/LLVMCPU/Passes.cpp#L29). These pipeline are invoked [here](https://github.com/google/iree/blob/ec9d61fcebe22c5b638115597102ec3698bfe236/iree/compiler/Codegen/LLVMCPU/LLVMCPULowerExecutableTarget.cpp#L152) based on an analysis of the dispatch region. For the mmt4d ops. That analysis is [here](https://github.com/google/iree/blob/ec9d61fcebe22c5b638115597102ec3698bfe236/iree/compiler/Codegen/LLVMCPU/KernelDispatch.cpp#L378). Right now it just invokes the `CPUTensorsToVectors` pipeline. For the case you have I think you want to just invoke the `CPUDefault` pipeline. This just bufferizes the dispatch region without vectorization or further tiling. Then you will end up with `mmt4d` ops on `memref`s. If you want to lower it to a function call, its probably better to use the `LinalgInterface` which allows you to set the library call name to use. That might have some weird signature when lowering to LLVM, but at least thats the prescribed way. 

The harder issue here is that the dispatch region you have here is probably going to end up with a stack allocation (if it bufferizes, which this specific example hasnt been tried). Neither the IREE bufferization or the upstream bufferization is going to be able to convert this to `memref` without using a stack allocation. AFAIK, for the mmt4d, we dont want stack allocation. The current e2e flow of MMT4D has padding + packing happening in different dispatch regions.

**Comment by benvanik** [comment]
Yeah, you're reinforcing my belief that I'm not be the right person to do that part of the code ;)
I had expected that there would be pointers that are passed to vector.transfer_read/write and those pointers could be passed to this instead. There shouldn't need to be any stack allocations - but whether the current implementations would produce them or not is something I don't know. I'd be happy if someone found a better way to slice this in - either as a pattern or pass as it is - that should really be the simplest part of all this machinery with the rest of the compiler goo doing the bitcode linking being independent.

I'd avoided the Linalg function call stuff on purpose - we need to manage our ABI carefully as we are persisting it in the bitcode files and then combining the IR modules with a need for exact symbol definitions. If it is something that will not change out from under us and is doing the same bare ptr calling convention conversion then it may be ok but when I last peeked inside it was memref descriptors. If that's changed and someone can wire that up then we could remove the pass entirely.

**Comment by benvanik** [comment]
(also sorry for bugging ya on the weekend - happy to wait until monday :)

**Comment by MaheshRavishankar** [comment]
> Sycned with benoit; next steps here:
> 
> * I'll rename to `libmmt` (as this is just M*Mᵀ - zero name bike-shedding allowed)
> * I'll split and land the library independently
> * I'll shore up the linker goo and land that independently
> * All of us get together and figure out how to plumb this through codegen

Was just going to suggest the last one!

**Pull request closed without merging**
