### PR TITLE
Refactor Model builder MatMul GPU benchmark to support multiple strategy

### PR DESCRIPTION
**Pull request by ThomasRaoux**

### CODE REVIEW

**Comment by ThomasRaoux** [comment]
$cycheng, feel free to comment on the PR.

**Review by MaheshRavishankar — APPROVED** [review]
This looks fine. But I am hoping that most of the strategy here will be ported over to IREE directly....

**Comment by ThomasRaoux** [comment]
> This looks fine. But I am hoping that most of the strategy here will be ported over to IREE directly....

I'll definitely do it next once things are working (missing couple patches in MLIR), it is just convenient to have it as @cycheng is doing some experiment in model builder.

**Comment by antiagainst** [comment]
+1 to what Mahesh said. We should try to consolidate various components. IREE main should have better GPU target modelling as we go.

**Comment by ThomasRaoux** [comment]
> +1 to what Mahesh said. We should try to consolidate various components. IREE main should have better GPU target modelling as we go.

Sounds good, that's definitely part of my plan :)

**Comment by cycheng** [comment]
Cool!! Thanks @ThomasRaoux :)

**Pull request merged**
