### PR TITLE
Integrate llvm-project to e2ed3fd71e08 and bump dependencies.

### PR DESCRIPTION
**Pull request by hanhanW**
* llvm-project: e2ed3fd71e08
* mlir-hlo: 40d9c1338e8f023ccce0b0241d664a347aa7c438
* tensorflow: d913bc9cb995a21723719055babc0036be4c9227

### CODE REVIEW

**Review by stellaraccident — APPROVED** [review]
Changes look good to me. Ok ty submit if tests pass.

**Comment by hanhanW** [comment]
We need fixes for https://reviews.llvm.org/D124649 and https://reviews.llvm.org/D124470

**Comment by hanhanW** [comment]
@matthias-springer looks like there are changes about `eliminateInitTensors` in https://reviews.llvm.org/D124853, can you help fix `BufferizationInterfaces.cpp`?

**Comment by MaheshRavishankar** [comment]
@nicolasvasilache seems like the integrate is hitting some assertion in uses of TileOp of the transform dialect

```
./build/third_party/llvm-project/llvm/bin/iree-dialects-opt /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tile-to-in-parallel.mlir  -linalg-transform-interp
iree-dialects-opt: /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/TileToInParallel.cpp:33: FailureOr<iree_compiler::IREE::LinalgExt::InParallelOp> mlir::iree_compiler::IREE::LinalgExt::TileOpToInParallelRewriter::returningMatchAndRewrite(iree_compiler::IREE::LinalgExt::TileOp, mlir::PatternRewriter &) const: Assertion `tileOp.getNumResults() > 0 && tileOp.outs().size() == tileOp.getNumResults()' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: ./build/third_party/llvm-project/llvm/bin/iree-dialects-opt /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/test/Dialect/iree_linalg_ext/tile-to-in-parallel.mlir -linalg-transform-interp
 #0 0x0000000002226b9a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/ravishankarm/Development/iree/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:565:11
 #1 0x0000000002226d6b PrintStackTraceSignalHandler(void*) /home/ravishankarm/Development/iree/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:632:1
 #2 0x000000000222532b llvm::sys::RunSignalHandlers() /home/ravishankarm/Development/iree/iree/third_party/llvm-project/llvm/lib/Support/Signals.cpp:102:5
 #3 0x00000000022274e1 SignalHandler(int) /home/ravishankarm/Development/iree/iree/third_party/llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007fc620ea2200 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12200)
 #5 0x00007fc62090e8a1 raise ./signal/../sysdeps/unix/sysv/linux/raise.c:50:1
 #6 0x00007fc6208f8546 abort ./stdlib/abort.c:81:7
 #7 0x00007fc6208f842f get_sysdep_segment_value ./intl/loadmsgcat.c:509:8
 #8 0x00007fc6208f842f _nl_load_domain ./intl/loadmsgcat.c:970:34
 #9 0x00007fc620907222 (/lib/x86_64-linux-gnu/libc.so.6+0x31222)
#10 0x000000000061d8c5 mlir::iree_compiler::IREE::LinalgExt::TileOpToInParallelRewriter::returningMatchAndRewrite(mlir::iree_compiler::IREE::LinalgExt::TileOp, mlir::PatternRewriter&) const /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/Transforms/TileToInParallel.cpp:38:29
#11 0x00000000005b8700 mlir::iree_compiler::IREE::LinalgExt::RewriteLinalgExtTileToInParallelOp::applyToOne(mlir::iree_compiler::IREE::LinalgExt::TileOp)::$_2::operator()(mlir::iree_compiler::IREE::LinalgExt::TileOp, mlir::PatternRewriter&) const /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.cpp:190:27
#12 0x00000000005af414 auto mlir::functional::applyAt<mlir::iree_compiler::IREE::LinalgExt::TileOp, mlir::iree_compiler::IREE::LinalgExt::RewriteLinalgExtTileToInParallelOp::applyToOne(mlir::iree_compiler::IREE::LinalgExt::TileOp)::$_2&, true>(mlir::iree_compiler::IREE::LinalgExt::TileOp, mlir::iree_compiler::IREE::LinalgExt::RewriteLinalgExtTileToInParallelOp::applyToOne(mlir::iree_compiler::IREE::LinalgExt::TileOp)::$_2&) /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/include/iree-dialects/Transforms/Functional.h:68:10
#13 0x00000000005af375 mlir::iree_compiler::IREE::LinalgExt::RewriteLinalgExtTileToInParallelOp::applyToOne(mlir::iree_compiler::IREE::LinalgExt::TileOp) /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/lib/Dialect/LinalgExt/TransformOps/LinalgExtTransformOps.cpp:195:10
#14 0x00000000005d28a8 mlir::transform::TargetableSingleOperandOpTrait<mlir::iree_compiler::IREE::LinalgExt::RewriteLinalgExtTileToInParallelOp>::apply(mlir::transform::TransformResults&, mlir::transform::TransformState&)::'lambda'(mlir::iree_compiler::IREE::LinalgExt::TileOp)::operator()(mlir::iree_compiler::IREE::LinalgExt::TileOp) const /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/TransformOpTraits.h:100:49
#15 0x00000000005d279e mlir::LogicalResult mlir::transform::detail::applyTransformToEach<mlir::transform::TargetableSingleOperandOpTrait<mlir::iree_compiler::IREE::LinalgExt::RewriteLinalgExtTileToInParallelOp>::apply(mlir::transform::TransformResults&, mlir::transform::TransformState&)::'lambda'(mlir::iree_compiler::IREE::LinalgExt::TileOp)>(llvm::ArrayRef<mlir::Operation*>, llvm::SmallVectorImpl<mlir::Operation*>&, mlir::iree_compiler::IREE::LinalgExt::RewriteLinalgExtTileToInParallelOp) /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/TransformOpTraits.h:67:19
#16 0x00000000005d25ec mlir::transform::TargetableSingleOperandOpTrait<mlir::iree_compiler::IREE::LinalgExt::RewriteLinalgExtTileToInParallelOp>::apply(mlir::transform::TransformResults&, mlir::transform::TransformState&) /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/LinalgTransform/TransformOpTraits.h:98:16
#17 0x00000000005d2529 mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Model<mlir::iree_compiler::IREE::LinalgExt::RewriteLinalgExtTileToInParallelOp>::apply(mlir::transform::detail::TransformOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::transform::TransformResults&, mlir::transform::TransformState&) /home/ravishankarm/Development/iree/iree/build/third_party/llvm-project/llvm/tools/mlir/include/mlir/Dialect/Transform/IR/TransformInterfaces.h.inc:55:56
#18 0x0000000001d84acf mlir::transform::TransformOpInterface::apply(mlir::transform::TransformResults&, mlir::transform::TransformState&) /home/ravishankarm/Development/iree/iree/build/third_party/llvm-project/llvm/tools/mlir/include/mlir/Dialect/Transform/IR/TransformInterfaces.cpp.inc:10:14
#19 0x0000000001d846ab mlir::transform::TransformState::applyTransform(mlir::transform::TransformOpInterface) /home/ravishankarm/Development/iree/iree/third_party/llvm-project/mlir/lib/Dialect/Transform/IR/TransformInterfaces.cpp:126:24
#20 0x000000000064eb47 transform_ext::CanonicalizedSequenceOp::apply(mlir::transform::TransformResults&, mlir::transform::TransformState&) /home/ravishankarm/Development/iree/iree/llvm-external-projects/iree-dialects/lib/Dialect/LinalgTransform/IR/StructuredTransformOpsExt.cpp:388:22
```

**Comment by hanhanW** [comment]
> @nicolasvasilache seems like the integrate is hitting some assertion in uses of TileOp of the transform dialect

This is the last failure. I'm not familiar with that part, @nicolasvasilache could you help fix it?

FYI, this is the IREE commit that touched LinalgExt code. Most of them are about parser, so it might not relate to the failure.

https://github.com/google/iree/pull/9072/commits/bc93ff28b2c30da95821b9854925bc7437e2e215#diff-b2b0f9026491ff21db55470285679c91fccc20ad752cc08dc0add8149f4ab565

**Comment by matthias-springer** [comment]
> @matthias-springer looks like there are changes about `eliminateInitTensors` in https://reviews.llvm.org/D124853, can you help fix `BufferizationInterfaces.cpp`?

Bufferization should be fixed. We still need init-tensor-elimination, but it is now less tightly coupled with bufferization and could even be an entirely different pre-processing pass.

**Pull request merged**
