### PR TITLE
Add vectorization to CPUBufferOpsTileAndVectorizePipeline

### PR DESCRIPTION
**Pull request by hanhanW**
There was correctness issues in vectorization on copy ops. There might be fixes from upstream, so we can't reproduce the issue. The commit adds the vectorization step back.

Fixes https://github.com/google/iree/issues/8579

### CODE REVIEW

**Comment by hanhanW** [comment]
Maybe I should add a pipeline lit tests, I'll add it tomorrow.

**Comment by hanhanW** [comment]
I'm glad that I added a pipeline_test. It looks like there is a bug in uses of FusionExpert for tiling Linalg ops on memrefs. I'll file a bug.

**Comment by hanhanW** [comment]
I believe that they are true improvements, not noises. We do vectorize copy ops, and it brings improvements to us.

**Review by MaheshRavishankar — APPROVED** [review]

**Review by dcaballe — APPROVED** [review]
LGTM! Could you please elaborate on how this is fixing #8579. The issue says that vectorization was disabled for this pipeline and this is enabling it again but I don't get what is fixing the problem. Is it about skipping the reduction loops? It would be good to add that to the PR description.

**Comment by hanhanW** [comment]
> LGTM! Could you please elaborate on how this is fixing #8579. The issue says that vectorization was disabled for this pipeline and this is enabling it again but I don't get what is fixing the problem. Is it about skipping the reduction loops? It would be good to add that to the PR description.

I can not reproduce the issue. It could be a fix from upstream.

**Pull request merged**
