### PR TITLE
[spirv] NFC: Update comments in SPIR-V pipeline

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Comment by benvanik** [comment]
There's no guarantee that an executable has only a single function - does this mean that the SPIR-V backend now can handle multiple functions? If not, we'll want to keep the inliner pass.

**Comment by antiagainst** [comment]
@benvanik are we expecting to see multiple functions in one dispatch region soon? Otherwise it's just a pass lying there doing nothing. I saw it's also removed in LLVM CPU side quite some time ago (#5489). SPIR-V side we have support for converting multiple functions. But not the whole pipeline is robust to it though.

**Comment by benvanik** [comment]
If it's gone from CPU then it shouldn't have been removed from there either, unless it properly handles multiple functions :)

Executables need not only come from dispatch regions: consider them as programs of their own. When we start to talk about libraries what we are really talking about is functions splatted inside of executables that can be called by the code that may come from the dispatch region. We also really need to get spirv linking working which would cause executables to have multiple functions: a decent chunk of our time is spent invoking shader compilers, and it'll matter even more in webgpu (where we really want to be batching things).

I'd rather have us able to handle programs than save on a cheap pass and make things more painful in the future.

**Comment by antiagainst** [comment]
Yup, I'm coming to SPIR-V linking soon. :) But, linking is happening after executable translation, which these passes are for. So I'm not sure how linking affects that. Anyway, not a big issue as my main goal is to clean up the outdated comments. It's just that the inliner is not used so seems a good thing to clean up too. Added back.

**Comment by MaheshRavishankar** [comment]
Yeah, maybe inliner was removed from CPU side. Ack, that we might need at sometime. I might have removed it by accident. We can add it back if needed.

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
