### PR TITLE
NFC: Refactor ConcretizeTileAmongstWorkgroupsPass.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
The refactoring silos everything required for removing unit-trip loop
counts under a flag with future changes trying to use the affine min
canonicalization without removing the loop itself. Goal is to verify
performance overhead that keeping the unit loop around adds.

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
Just sending this WIP refactoring step. @ThomasRaoux this might help with the CUDA PR.

**Comment by antiagainst** [comment]
This is labelled as draft right now. I assume I should hold off on reviewing?

**Comment by MaheshRavishankar** [comment]
> This is labelled as draft right now. I assume I should hold off on reviewing?

I am fixing up a test and I am going to fix the build issue. You can review after that. Ill make it "not a draft" when it is ready.

**Comment by MaheshRavishankar** [comment]
Dropping this PR. I have a follow up PR that does all the cleaning/refactoring that I am going to merge this into.

**Pull request closed without merging**
