### PR TITLE
Adopt TransformDialectExtension

### PR DESCRIPTION
**Pull request by nicolasvasilache**
This revision adds support for dynamic registration of ops into the transform dialect (see https://reviews.llvm.org/D123135 for more context).
    
With this support we can now avoid artificial boundaries and don't need to duplicate ops to allow defining new transform dialect ops.
    
This PR also performs a minimal port of one such op out of `iree-dialects` and into `iree/compiler/Codegen/TransformDialectExtensions`.

For registration, we piggy-back on `Interfaces.cpp::registerCodegenInterfaces` for now. This layering should be improved in the future.

### CODE REVIEW

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Ill look in detail later, but please dont include an LLVM bump as part of a PR. If this requires a specific commit from core, either cherry pick it into `iree-llvm-fork` or wait for IREE to catch up to the point you need.

**Comment by nicolasvasilache** [comment]
> Ill look in detail later, but please dont include an LLVM bump as part of a PR. If this requires a specific commit from core, either cherry pick it into `iree-llvm-fork` or wait for IREE to catch up to the point you need.

This is an artifact of how github shows PRs and the lack of stacked commits.
The LLVM bump is already isolated in #8779

**Comment by nicolasvasilache** [comment]
@benvanik I'd love some suggestions on the layering of the transform registrations.
Atm I am piggy-backing on interfaces but it creates weird dependencies.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Is there a reason to move this into `iree/compiler/...`.

Loosely `iree/compiler/...` is what IREE core team is on the hook for maintaining functional correctness. Moving this into iree compiler core is effectively moving this out of "experimental" state which requires some use case. I am not clear what that is yet....

**Comment by nicolasvasilache** [comment]
> Is there a reason to move this into `iree/compiler/...`.
> 
> Loosely `iree/compiler/...` is what IREE core team is on the hook for maintaining functional correctness. Moving this into iree compiler core is effectively moving this out of "experimental" state which requires some use case. I am not clear what that is yet....

I am confused .. didn't we specifically make room in `iree/compiler/...` under a flag to allow bringing up the transform dialect in IREE ? Didn't we also add temporary copies of HAL operations in LinalgExt + iree/compiler/Codegen/Common/SetNumWorkgroupsFromLinalgExtPass.cpp that we should retire when it was possible to register transform dialect ops dynamically outside of the transform dialect?
This PR is the first step of the cleanup, the followup PR drops the HAL operations from LinalgExt as we had discussed and moves the corresponding transform in IREE.

To properly use the transform dialect and Linalg in general I expect 2 immediate patterns to be useful in IREE because they depend on IREE code:
- Tile -> InParallel which is a nice abstraction to represent tiling+parallelism+distribution+tensors in Linalg. This is needed as a pattern somewhere that can link with IREE code because of the HAL materialization of distribution.
- Bufferization which requires IREE specific-code and also needs to be registered from a place that can link with IREE code.

Now none of this has to live in iree/compiler/... specifically but it needs to:
- be able to link with IREE
- be able to register ops in the transform dialect at startup time

Please advise where you'd prefer this to live and the layering.

As for use case: this brings the results of https://arxiv.org/abs/2202.03293 without having to hack copies of the experimental retired sandbox CodegenStrategy C++ code, so consider it a replacement for those old abstractions.

**Comment by nicolasvasilache** [comment]
I layered this in a more isolated fashion in `iree/compiler/Codegen/TransformDialectExtensions`, this can move further if necessary but the essential visibility requirements can't change atm.
One solution to fully isolate this form IREE would be for IREE to have a BYOC type of model and itself expose dynamic registrations. 
This is much more involved obviously than just adding a flag like we've been doing so far.

**Review by stellaraccident — COMMENTED** [review]
I think this may be over indexing on that one comment about iree/compiler, which is less about being on one side of the line or the other and more about sequencing in with the entire development plan and not getting ahead of ourselves. As something up and coming, I think what Mahesh is actually asking is that to the extent possible, we keep this work optional and layered in parallel to the existing code in a more or less ejectable way (ie. If tomorrow we decided to not finish the work, there is a pretty clear delineation on what to delete, and today, as people debug things, it is clear that this is "new path" that can be ignored if not working on it).

Agreed that interfaces and other similar detritus generally needs to go with the user and breaks layering at the registration points. Thanks for segmenting it.

From what I can tell, the friction in landing this stack is mostly due to lack of a clear picture of the sequence of what is getting done, how and when. In your PR descriptions, you include the paper link which answers "why" but not those other questions, and not in a way that load bearing details can be discussed.

There are a couple of easy ways out: a) write a lightweight RFC/design doc and share on iree-discuss or b) file an issue describing the entire spike of work.

We usually start with (b) and escalate to something more "debatable" if there isn't clarity. If you do that, one way to forecast the sequencing is to use the checkbox feature:

* [ ] Load delorian on to truck
* [ ] Acquire plutonium
* [ ] Pack extra fuel rods in the trunk
* [ ] Don't forget to pack extra gasoline

Have your proposed sequencing in the top issue and keep it up to date as the discussion evolves below. Then reference the issue in every PR description. For things like this that may involve ~months of work to land completely, hidden infra landmines, or debatable priorities on sequencing/when to do things, this can help the folks who have a stake in those things but aren't focused on your work particularly to engage in a lightweight way.

I don't think it's too late to start such an issue, and even back dating and checking the first couple of steps would help with the clarity.

**Comment by MaheshRavishankar** [comment]
> > Is there a reason to move this into `iree/compiler/...`.
> > Loosely `iree/compiler/...` is what IREE core team is on the hook for maintaining functional correctness. Moving this into iree compiler core is effectively moving this out of "experimental" state which requires some use case. I am not clear what that is yet....
> 
> I am confused .. didn't we specifically make room in `iree/compiler/...` under a flag to allow bringing up the transform dialect in IREE ? Didn't we also add temporary copies of HAL operations in LinalgExt + iree/compiler/Codegen/Common/SetNumWorkgroupsFromLinalgExtPass.cpp that we should retire when it was possible to register transform dialect ops dynamically outside of the transform dialect? This PR is the first step of the cleanup, the followup PR drops the HAL operations from LinalgExt as we had discussed and moves the corresponding transform in IREE.
> 
> To properly use the transform dialect and Linalg in general I expect 2 immediate patterns to be useful in IREE because they depend on IREE code:
> 
> * Tile -> InParallel which is a nice abstraction to represent tiling+parallelism+distribution+tensors in Linalg. This is needed as a pattern somewhere that can link with IREE code because of the HAL materialization of distribution.
> * Bufferization which requires IREE specific-code and also needs to be registered from a place that can link with IREE code.
> 

I am trying to get an idea of what the goals are here. This is what I had in mind. The immediate goal for using the transform dialect were
1) Replace existing use of the Codegen Driver in CPU backend with using the transform dialect approach. The initial work of this I assumed was meant to target single threaded computation (this is how I initially setup the pipeline for use with the Transform dialect). For the single threaded case, I think you wouldnt require anything from HAL to lower to LLVM, and would allow you to verify things are working as expected. There is some amount of "feature parity" needed with what is done currently with CodegenDriver, and then we can start rolling that into the main IREE compiler stack. So the initial setup of pipeline to insert passes from `iree-dialects` guarded by a flag was meant to enable this evaluation without having this built in `iree/compiler/...`
2) I assumed the `TileOp` abstraction is something needed to verify multi-threaded performance. I think moving over IREEs codegen to use `TileOp` is fairly disruptive. In terms of ordering, it would be better to make this transition (if needed) later on based on a better understanding of what the trade-offs are. So having the `TileOp` connected to the HAL "parallelism abstraction" as it is today (duplicate ops in `iree-dialects` that get converted to the actual ops in IREE) I thought connects things enough to allow for evaluating multi-threaded performance with transformation dialect (again without having to build out this code in `iree/compiler/...`). Then we can evaluate if we actually need to use the `TileOp` to realize that performance. AFAICS the final code generated with `TileOp` and what is done currently in IREE should be similar. If that is not the case it would be good to get an idea of why there is a mismatch. That will give us a better place to decide which path to take.

So with either of these, my understanding is that the silo carved out for using the transformation dialect within `iree-dialects` should not need to move any code into `iree/compiler/...` to evaluate that things connect and work e2e. Also, `iree-dialects` was meant as a place to stage things before they can move upstream. So just "simulating" by keeping things in `iree-dialects` vs within `iree/compiler/...` is useful IMO. IIUC the registration you have here is just to avoid the duplicate ops in `iree-dialects` for the HAL ops needed to connect things. I dont think those duplicate ops are that much of a problem for a time being.

> Now none of this has to live in iree/compiler/... specifically but it needs to:
> 
> * be able to link with IREE
> * be able to register ops in the transform dialect at startup time
> 
> Please advise where you'd prefer this to live and the layering.
> 
> As for use case: this brings the results of [arxiv.org/abs/2202.03293](https://arxiv.org/abs/2202.03293) without having to hack copies of the experimental retired sandbox CodegenStrategy C++ code, so consider it a replacement for those old abstractions.

FTR, the use of CodegenStrategy (by copying code from sandbox) was explicit recommendation made to us to use the upstream vectorization related work in a way that connects "correctly". It took us a while to move everything over to use the CodegenStrategy. There are a lot of things IREE needs to "support" and is non-trivial amount of work to make the transition happen (took two of us 2-3 months to make this happen, but it did also involve some changes to IREE itself that was needed to connect everything). So moving to transform dialect is also going to be non-trivial amount of work, and needs to be moved in a more gradual fashion. Keeping the code in `iree-dialects` and moving things needed more deliberately into `iree/compiler/...` based on a good understanding of what it is used for by people in IREE (me, Hanhan and Diego, for example and prioritized appropriately w.r.t other things on peoples plate), is a way to manage that switch. It would be too disruptive to do a binary switch.

As Stella mentioned, if there is a disconnect between the work plan and progression that I have in my mind, vs. what you were planning, this needs to be hashed out before landing code?

**Comment by stellaraccident** [comment]
Thanks Mahesh - given all of the moving parts, it does seem like this raises to design-doc territory. I think there is a lot more work hiding here than may be visible, and that increases the need to have a documented path forward. That will also increase our ability to fan it out to additional people as needed too.

**Comment by nicolasvasilache** [comment]
I still do not understand the concern: there has never been a question of a binary switch on anything.
Still there seems to be issues with the mere existence of one op related to parallelism + tensors so I will reorder things and keep my work on parallelism in a private branch.

**Pull request closed without merging**
