### PR TITLE
CMake: Add configuration for ruy targets

### PR DESCRIPTION
**Pull request by marbre**
This is required to build iree_tools_iree-run-module

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Can we contribute the CMakeLists to TF? I believe TF allows community-supported builds and it's got some CMakeLists files in there. @silvasean would ruy accept CMakeLists build files?

**Comment by marbre** [comment]
@stellaraccident mentioned that the CMake files in TF were removed some time ago, see https://github.com/google/iree/issues/179#issuecomment-563366754. But maybe it's an option for ruy?

**Comment by GMNGeoffrey** [comment]
Hmm I probably misunderstood the state of tensorflow. Really ruy has nothing to do with TF in particular AFAIU, so it would sure be nice if it didn't live in the tensorflow repository...

In that case, let's go ahead with an overlay here.

**Comment by silvasean** [comment]
Ruy will soon be open source as a standalone project in https://github.com/google/ruy (still empty for now).

@bjacob about the question of adding CMake support in Ruy. Gemmlowp has it in "contrib" (not sure how up to date it is: https://github.com/google/gemmlowp/blob/master/contrib/CMakeLists.txt).

**Pull request closed without merging**
