### PR TITLE
Update TF & LLVM submodules

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
Now possible because of https://github.com/google/iree/pull/598

$ git_scripts/update_tf_llvm_submodules.py --update_build_files=True

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Grrr looks like we'll have to deal with experimental_cc_shared_library now. TF has taken a dep on it, but I guess we have an older version of rules_cc or something

**Comment by GMNGeoffrey** [comment]
This is going to require some work to get our version of rules_cc in sync with TFs :-/

**Comment by marbre** [comment]
> This is going to require some work to get our version of rules_cc in sync with TFs :-/

Is that something you have to solve internally with regard to the internal build? If not, you might drop a comment with the "current" status. I might find some time "tomorrow" to take a look, so after your workday.

**Comment by GMNGeoffrey** [comment]
> > This is going to require some work to get our version of rules_cc in sync with TFs :-/
> 
> Is that something you have to solve internally with regard to the internal build? If not, you might drop a comment with the "current" status. I might find some time "tomorrow" to take a look, so after your workday.

It's the way we dep on rules_cc vs the way TF does it. We use bazel-federation, which maybe we shouldn't be. @stellaraccident set that up and I think was trying to avoid having a thousand different bazel imports in our workspace. This isn't a problem internally, where all rules come from the monorepo itself, so it's purely an OSS issue. We might have additional ability to bother TF folks and ask what they're doing, but if you want to fiddle with bazel gunk then I will not stop you :-P

**Comment by GMNGeoffrey** [comment]
I will switch our deps off of bazel federation to directly grab all the repos using whatever hash TF uses :-/

**Comment by stellaraccident** [comment]
I really wish Bazel was a cohesive system that held itself together across
projects versus a carefully constructed collection of sha hashes that have
to be globally synchronized across deps.

Feel free to remove bazel federation in favor of the rules_cc that TF uses.
There doesn't seem to be a unified path forward for these things.

**Pull request closed without merging**
