### PR TITLE
[Cleanup] Refactor BUILD file.

### PR DESCRIPTION
**Pull request by hanhanW**
This makes us easier to track and add tests.

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
So I just noticed this, but we actually deliberately removed normal globs from the build files because glob is not well supported in CMake. Requiring explicit lists of files is WAI. `enforce_glob` provides a mechanism to also ensure that those static lists match an expected glob, but BUILD files should be static wrt the file tree

**Comment by GMNGeoffrey** [comment]
https://github.com/google/iree/commit/93a1ff13490596c5add7f09bbeeb817c621d4bad

Looks like I forgot to remove bazel_to_cmake support for glob

**Comment by hanhanW** [comment]
> So I just noticed this, but we actually deliberately removed normal globs from the build files because glob is not well supported in CMake. Requiring explicit lists of files is WAI. `enforce_glob` provides a mechanism to also ensure that those static lists match an expected glob, but BUILD files should be static wrt the file tree

oops, sorry about this. I did not know the difference and should ask you first. I will send out another PR to fix it.

**Comment by GMNGeoffrey** [comment]
No worries. I should've finished my cleanup and removed glob support from bazel_to_cmake :-)

**Pull request merged**
