### PR TITLE
Add float and quantized models to benchmark suite

### PR DESCRIPTION
**Pull request by mariecwhite**

### CODE REVIEW

**Comment by rsuderman** [comment]
@GMNGeoffrey how do we trigger a sample run of benchmarking again?

**Comment by GMNGeoffrey** [comment]
Go to https://buildkite.com/iree/iree-benchmark and trigger a build. For the "branch", put in pull/$PR_NUMBER/head (yes really the branch, not the commit)

It's a pinned message in the builds channel: https://discord.com/channels/689900678990135345/689957613152239638 because that's documentation :-P

**Review by GMNGeoffrey — COMMENTED** [review]
This is *a lot* of additional models and our benchmark pipeline is already quite slow. Are all of them really necessary to run continuously?

**Comment by antiagainst** [comment]
I think we just need to add the `buildkite:benchmark` label to trigger the benchmarking pipeline. (I just did that.) ;-P

Yeah, there are a lot of model variants. I have the same question as @GMNGeoffrey that whether all of them are needed. I can see the needs for small bitwidths, etc., but not some other variants. Would you mind to explain a bit more?

Under the current pipeline settings, generally it's hard to put more language models in as they have huge weights. It would  blow up the size of generated artifacts (given we have many permutations towards different hardware and runtime configurations). Vision models are easier though, but still weighs on benchmark time.

So I think putting more models in step by step would be better than landing all of them once. Anyway, let's wait for the benchmark run to see the impact on artifact size and benchmark time. :)

BTW, it would be nice to pull in Inception and EfficientNet, given they are different model architectures. Could you also help on that? Thanks! :)

**Comment by GMNGeoffrey** [comment]
> I think we just need to add the `buildkite:benchmark` label to trigger the benchmarking pipeline. (I just did that.) ;-P

:facepalm: oh right. I forgot this is one of the ones that actually runs on forks.

**Comment by mariecwhite** [comment]
Each model tests different paths and they include both a float version + quantized version. I've written a small rationale for including each model in the code comments. I believe @GMNGeoffrey has on his radar running a set of benchmarks for continuous testing, and another set to run nightly. I'll cherry-pick a smaller set to add for continuous testing.

Happy to add Inception and EfficientNet!

**Comment by antiagainst** [comment]
Yup; right now it times out after 1 hour on the phone because too many permutations: https://buildkite.com/iree/iree-benchmark/builds/2038. Aside from taking in models step by step, we can also only register them for certain build configurations to get started.

**Comment by mariecwhite** [comment]
Closing this PR in favor of adding benchmarks one at a time.

**Comment by GMNGeoffrey** [comment]
Thanks Marie. Sorry for the poor infra support here :-/ I hope that by EOQ we'll be in a much better spot

**Pull request closed without merging**
