### PR TITLE
Publish testing documentation to website

### PR DESCRIPTION
**Pull request by GMNGeoffrey**

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
> 1. https://github.com/google/iree/blob/5519cc570c7f4011566986169c84a29e82553cb1/scripts/prepare_doc_publication.py#L45-L82
>     set url to 'TestingGuide' and title to 'Testing Guide'? (I think the underscores are fine, but let's stay consistent for now)

I think we should steer clear of these kind of manual updates and move towards a "write doc -> doc shows up on website" flow. Increasing the burden of writing docs means there are no docs. I can do this one for now, but I'd really like to not have this kind of thing.

> 2. could also set an explicit nav ordering

How much do we care? Alphabetical seems fine to me...

> 3. update the link between docs to be relative now?

I was going to do that once the doc actually showed up on the website, since I wasn't confident about it :-D

**Comment by ScottTodd** [comment]
nvm about the `DOC_TITLE_DICT` suggestion - it pulls from the header by default, which already has the right title

**Comment by ScottTodd** [comment]
> I think we should steer clear of these kind of manual updates and move towards a "write doc -> doc shows up on website" flow. Increasing the burden of writing docs means there are no docs. I can do this one for now, but I'd really like to not have this kind of thing.

I'd generally agree that simple workflows are preferable, but publishing content on a webpage is structurally different from writing regular markdown files. There's extra flexibility in the presentation that we should be taking advantage of. The transformation steps that we have right now are simple, and I don't want to place artificial limits on the kinds of changes we can make.

Some of the things I want to get working on the webpage are platform / build system switches and more intentional styling on callouts. Those aren't possible with markdown and will need javascript, css, and hooks in the markdown to work with.

Now the file renames in `PERMALINK_DICT` can be mostly removed by reconciling the files on the `master` branch with the format that we use in URLs - we should definitely do that.

**Comment by GMNGeoffrey** [comment]
> I'd generally agree that simple workflows are preferable, but publishing content on a webpage is structurally different from writing regular markdown files. There's extra flexibility in the presentation that we should be taking advantage of. The transformation steps that we have right now are simple, and I don't want to place artificial limits on the kinds of changes we can make.
> 
> Some of the things I want to get working on the webpage are platform / build system switches and more intentional styling on callouts. Those aren't possible with markdown and will need javascript, css, and hooks in the markdown to work with.

I think this should be something where it's expressible and readable in markdown and gets extra goodies when published. That is the model that internal documentation uses and I think it works well. I'm fine investing extra effort in making our documentation prettier on the website but it shouldn't be at the cost of having to update a bunch of extra things when writing a doc.

> Now the file renames in `PERMALINK_DICT` can be mostly removed by reconciling the files on the `master` branch with the format that we use in URLs - we should definitely do that.

Yeah +1 on that

**Comment by ScottTodd** [comment]
> I think this should be something where it's expressible and readable in markdown and gets extra goodies when published.

I'd flip this around - the published page is what matters, and being viewable in standard GitHub-flavored markdown (or some other flavor) is a bonus. Optimize for the reader, not the writer.

Our current setup using GitHub flavored markdown as source files with automatically inserted jekyll frontmatter makes writing documents for the website similar to writing for GitHub, but we're leaving some documentation features untapped at the moment.

**Comment by GMNGeoffrey** [comment]
> > I think this should be something where it's expressible and readable in markdown and gets extra goodies when published.
> 
> I'd flip this around - the published page is what matters, and being viewable in standard GitHub-flavored markdown (or some other flavor) is a bonus. Optimize for the reader, not the writer.
> 
> Our current setup using GitHub flavored markdown as source files with automatically inserted jekyll frontmatter makes writing documents for the website similar to writing for GitHub, but we're leaving some documentation features untapped at the moment.

If our only job was creating a website, sure. The whole point of markdown is that it's readable as source and can be converted to HTML

> Its key design goal is readability – that the language be readable as-is, without looking like it has been marked up with tags or formatting instructions,[10] unlike text formatted with a markup language, such as Rich Text Format (RTF) or HTML, which have obvious tags and formatting instructions.
https://en.wikipedia.org/wiki/Markdown

> Optimize for the reader, not the writer.
If you don't optimize for the writer you end up with no documentation at all. We should write valid markdown, potentially with some nifty widgets that are applied as tooling across documents (so the doc author doesn't have to edit some other file to specifically reference their new doc and insert some thing in there).

**Comment by ScottTodd** [comment]
> The whole point of markdown is that it's readable as source and can be converted to HTML

I expect we'll stick with publishing a static website with markdown source. However, GitHub flavored markdown can only get us so far on its own.

> We should write valid markdown, potentially with some nifty widgets that are applied

Some of the features I want to use on published pages are supported in other [flavors of markdown](https://github.com/commonmark/commonmark-spec/wiki/markdown-flavors), but will not render as nicely when interpreted as GitHub flavored markdown. For example, R Markdown's [tabbed sections](https://bookdown.org/yihui/rmarkdown/html-document.html#tabbed-sections) will let us put Bazel and CMake commands (or Windows/Linux setup instructions) side-by-side with tabbing behavior. Markdeep has ["admonitions"](https://casual-effects.com/markdeep/features.md.html#basicformatting/admonitions) and other flavors have similar techniques for highlighting notes/warnings/tips.

**Comment by GMNGeoffrey** [comment]
> > The whole point of markdown is that it's readable as source and can be converted to HTML
> 
> I expect we'll stick with publishing a static website with markdown source. However, GitHub flavored markdown can only get us so far on its own.
> 
> > We should write valid markdown, potentially with some nifty widgets that are applied
> 
> Some of the features I want to use on published pages are supported in other [flavors of markdown](https://github.com/commonmark/commonmark-spec/wiki/markdown-flavors), but will not render as nicely when interpreted as GitHub flavored markdown. For example, R Markdown's [tabbed sections](https://bookdown.org/yihui/rmarkdown/html-document.html#tabbed-sections) will let us put Bazel and CMake commands (or Windows/Linux setup instructions) side-by-side with tabbing behavior. Markdeep has ["admonitions"](https://casual-effects.com/markdeep/features.md.html#basicformatting/admonitions) and other flavors have similar techniques for highlighting notes/warnings/tips.

Wait all these things are exactly the sort of thing I described that is readable in the source but adds nice extra behavior in the website. I'm all for that. What are we actually arguing about now? I just don't want to have to maintain a manual mapping of page name to file name and that sort of thing.

**Comment by ScottTodd** [comment]
> > > The whole point of markdown is that it's readable as source and can be converted to HTML
> > 
> > 
> > I expect we'll stick with publishing a static website with markdown source. However, GitHub flavored markdown can only get us so far on its own.
> > > We should write valid markdown, potentially with some nifty widgets that are applied
> > 
> > 
> > Some of the features I want to use on published pages are supported in other [flavors of markdown](https://github.com/commonmark/commonmark-spec/wiki/markdown-flavors), but will not render as nicely when interpreted as GitHub flavored markdown. For example, R Markdown's [tabbed sections](https://bookdown.org/yihui/rmarkdown/html-document.html#tabbed-sections) will let us put Bazel and CMake commands (or Windows/Linux setup instructions) side-by-side with tabbing behavior. Markdeep has ["admonitions"](https://casual-effects.com/markdeep/features.md.html#basicformatting/admonitions) and other flavors have similar techniques for highlighting notes/warnings/tips.
> 
> Wait all these things are exactly the sort of thing I described that is readable in the source but adds nice extra behavior in the website. I'm all for that. What are we actually arguing about now? I just don't want to have to maintain a manual mapping of page name to file name and that sort of thing.

The original thread was regarding changes to `iree/scripts/prepare_doc_publication.py` (that I think should still be made here). The general concern that I'm seeing is that changes to the website are more than simply changes to markdown files (python scripts, bash scripts, frontmatter, markdown flavors that aren't preview-able on github, etc.). We can reconcile doc names with permalinks to help a bit, but the nav ordering will still be handled outside of markdown sources (or with explicit frontmatter in those sources).

I could also push onto this branch with the changes to that script that I'd like to see. Up to you.

**Comment by GMNGeoffrey** [comment]
> The original thread was regarding changes to `iree/scripts/prepare_doc_publication.py` (that I think should still be made here). The general concern that I'm seeing is that changes to the website are more than simply changes to markdown files (python scripts, bash scripts, frontmatter, markdown flavors that aren't preview-able on github, etc.). We can reconcile doc names with permalinks to help a bit, but the nav ordering will still be handled outside of markdown sources (or with explicit frontmatter in those sources).
> 
> I could also push onto this branch with the changes to that script that I'd like to see. Up to you.

Yeah that is my general concern. I think not being preview-able isn't the end of the world, though it is unfortunate. I'll make the change for the permalink mapping. It seems like doc title shouldn't be necessary, based on your comment. Was there a particular nav ordering you wanted for this?

I do think most of that should go away though. Permalinks should match filenames, we should export all docs in the docs directory (looks like there's already a TODO). Fiddling with nav ordering is fine, although I think it should be possible to do it in a way that's a bit less buried. Can we put it alongside the docs somewhere and just have it be a list of doc names rather than a mapping where you then have to visualize where everything goes? I do like "remainder is alphabetical" rather than having to make that explicit though.

**Comment by antiagainst** [comment]
The current setting is trying to have the nice things of both worlds: GitHub-flavored rendering when browsing the source code and nice goodies coming from Jekyll. Because of the system boundary, it's inevitable that we need to throw in additional configurations somewhere to control things. it's just where we want to cut the boundary and how do we want to set as the default. I think one way to reconcile things is to directly write the front matters in the source markdown. It's putting information for website publication into the source code but it's not very intrusive. I'm totally okay with that if folks think that's preferrable. :)

**Comment by GMNGeoffrey** [comment]
> The current setting is trying to have the nice things of both worlds: GitHub-flavored rendering when browsing the source code and nice goodies coming from Jekyll. Because of the system boundary, it's inevitable that we need to throw in additional configurations somewhere to control things. it's just where we want to cut the boundary and how do we want to set as the default. I think one way to reconcile things is to directly write the front matters in the source markdown. It's putting information for website publication into the source code but it's not very intrusive. I'm totally okay with that if folks think that's preferrable. :)

Yeah sorry I didn't mean for this to feel like a dig at your work here. I hope that's not how it came across. I think we should just try to minimize the differences here. Like snake vs camel case doesn't seem important, and having to manually list the docs seems like an unnecessary extra step. Same with redoing the directory structure. I think putting non-intrusive things directly in the source is better if it's small. It's kind of hard for me to see how much is involved in frontmatter. What happens when GitHub tries to render the frontmatter? It also depends on whether the frontmatter can reasonably be determined for a single doc in isolation. Nav order seems like something that has to be considered for all of them as a whole, so I think it's better to have it all in one place

**Comment by antiagainst** [comment]
Oh certainly no problem at all! :) Making things more smooth and integrated is certainly preferable. (Text is worse than face-to-face chat on this front because one cannot convey the facial expressions. So I'm trying to plug in as much as emojis as possible. ;-P) 

If you'd like to see what front matter are needed, check for example this one (https://raw.githubusercontent.com/pmarsceill/just-the-docs/master/docs/configuration.md) and it's rendered version on GitHub (https://github.com/pmarsceill/just-the-docs/blob/master/docs/configuration.md).

**Comment by GMNGeoffrey** [comment]
> Text is worse than face-to-face chat on this front because one cannot convey the facial expressions. So I'm trying to plug in as much as emojis as possible. ;-P

Yeah feeling that pain and reacting similarly :-D

> If you'd like to see what front matter are needed, check for example this one (https://raw.githubusercontent.com/pmarsceill/just-the-docs/master/docs/configuration.md) and it's rendered version on GitHub (https://github.com/pmarsceill/just-the-docs/blob/master/docs/configuration.md).

Yeah that does look a bit gross, but I think not the end of the world. If it's all autogenerated then it seems better to apply it behind the scenes rather than making people type it. And it looks like you already have something to check for pre-existing frontmatter. So we could put any overrides in the doc itself. I don't really like having nav order in the doc though because it's not something about the doc in isolation. Same with directory parent.

Anyway seems alright for now, but I think we should get rid of diffs between the doc and page title and path.

**Pull request closed without merging**
