### PR TITLE
Always add local_task and VMVX if building the compiler.

### PR DESCRIPTION
**Pull request by ScottTodd**
Fixes https://github.com/google/iree/issues/8196

The [`ConstEval`](https://github.com/google/iree/tree/main/compiler/src/iree/compiler/ConstEval) compiler component unconditionally depends on VMVX and the `local-task` HAL driver. The compiler needs _some_ reference implementation available, but we still want to be able to prune the set of built and automatically registered drivers in the runtime.

This is one solution we liked - if the compiler is enabled, force its requirements enabled too.

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by ScottTodd** [comment]
hmm... `cmake_baremetal_riscv32` is failing with

```
CMake Error at build_tools/cmake/iree_cc_library.cmake:113 (add_library):
  Target "iree_hal_drivers_local_task_task_driver" links to target
  "iree::base::internal::event_pool" but the target was not found.  Perhaps a
  find_package() call is missing for an IMPORTED target, or an ALIAS target
  is missing?
```

so even though the targets are excluded, they still have to be valid. I could add a `IREE_ENABLE_THREADING` check :/

**Comment by benvanik** [comment]
we probably only want to include if it building the compiler - then if cross-compiling there won't be any issues.

**Comment by benvanik** [comment]
Alternatively, we just set the LOCAL_TASK ON if building the compiler? then no spooky hidden targets?

**Comment by ScottTodd** [comment]
> Alternatively, we just set the LOCAL_TASK ON if building the compiler? then no spooky hidden targets?

Pushed commits for both ideas. I like the always on. Less spooky, more "if you don't want it, just don't build the entire compiler".

**Comment by benvanik** [comment]
neato - I think the force-enable is nicer - especially because it also needs to set the executable loader. If you can build LLVM you've definitely got the thread deps needed to compile that driver, and if you're trying to build a size-optimized runtime you're probably not going to do that from the same cmake invocation as when you build the compiler.

**Pull request merged**
