### PR TITLE
Call ::testing::InitGoogleTest before RUN_ALL_TESTS

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Comment by ScottTodd** [comment]
Discussed before at https://github.com/google/iree/pull/1856

**Comment by benvanik** [comment]
I've solved this in the past by having a common test main.cc (like iree/testing/gtest_main.cc) that does this so that each binary doesn't need to do the same dance (including the STDIN/etc). Useful on other platforms when trying to run gtests from within APKs/IPAs/etc that have non-standard main functions, too.

**Comment by benvanik** [comment]
Turns out, I already did that for benchmarks: https://github.com/google/iree/blob/4e4f587b254c7e12aa3ceddb121a7cd54d4d1f83/iree/testing/benchmark_main.cc#L20-L25

**Comment by antiagainst** [comment]
Oh, didn't notice we have prior discussion and solution to this already; just naively thought this is just another compiler warning-ish thing that can be addressed with adding a oneliner. :) I won't have bandwidth to push on this given the complication then.

**Comment by GMNGeoffrey** [comment]
> Oh, didn't notice we have prior discussion and solution to this already; just naively thought this is just another compiler warning-ish thing that can be addressed with adding a oneliner. :) I won't have bandwidth to push on this given the complication then.

Yeah unfortunately that's where I landed too :-/ Sorry for the warning spam

**Pull request closed without merging**
