### PR TITLE
Adopt upstream changes, revising the naming of MLIROptMain and MLIRMlirOptLib

### PR DESCRIPTION
**Pull request by marbre**
**Do not merge before before MLIR head includes commit https://github.com/llvm/llvm-project/commit/a9a305716bbfa657ce0f7ae9cd50df82720a6db0!**

### CODE REVIEW

**Comment by ScottTodd** [comment]
Great :D we can merge this when we next sync the LLVM commit.

cc @GMNGeoffrey

**Comment by GMNGeoffrey** [comment]
If we import this now, we can make it part of the integration of LLVM upstream.

**Comment by GMNGeoffrey** [comment]
The submodule updates have landed. I'm going to rebase this on master and run the presubmits

**Comment by GMNGeoffrey** [comment]
Actually I'm not able to push to the branch here. I'm getting permission denied. I thought this had "maintainers can edit" on the PR. Maybe I'm doing something wrong.

@marbre if you're online could you rebase this on master?

**Comment by GMNGeoffrey** [comment]
I've forked this as https://github.com/google/iree/pull/765. When it goes in it will still reference this PR and have proper author attribution

**Comment by marbre** [comment]
> Actually I'm not able to push to the branch here. I'm getting permission denied. I thought this had "maintainers can edit" on the PR. Maybe I'm doing something wrong.
> 
> @marbre if you're online could you rebase this on master?

It should have had "maintainers can edit". Wasn't online Friday evening, so couldn't rebase. Thanks for taking over :)

**Comment by GMNGeoffrey** [comment]
Yeah no worries, it was late :-) I followed the instructions for updating a PR from a fork from the command line, but it didn't work

**Pull request closed without merging**
