### PR TITLE
Merge google -> main

### PR DESCRIPTION
**Pull request by hanhanW**
* a0e6ad80 Synchronize submodules                                                          
* ba397437 Update Tensorflow submodules                                                    
* 631a1dd2 Synchronize submodules                                                          
* 64a6aef7 Integrate LLVM at llvm/llvm-project@834133c950fc

### CODE REVIEW

**Comment by ScottTodd** [comment]
This should have been merged with a merge commit. It may complicate the next set of merges when Copybara gets involved.

The merge commit message should also have matched the PR description - the `PiperOrigin-RevId` in particular causes further issues with Copybara.

**Comment by ScottTodd** [comment]
> This should have been merged with a merge commit. It may complicate the next set of merges when Copybara gets involved.
> 
> The merge commit message should also have matched the PR description - the `PiperOrigin-RevId` in particular causes further issues with Copybara.

We may need to `git revert` the squashed merge of this PR, or even force push over to undo it.

**Comment by hanhanW** [comment]
> > This should have been merged with a merge commit. It may complicate the next set of merges when Copybara gets involved.
> > The merge commit message should also have matched the PR description - the `PiperOrigin-RevId` in particular causes further issues with Copybara.
> 
> We may need to `git revert` the squashed merge of this PR, or even force push over to undo it.

I've created #2716, can't it be done with that change? If force push is easier, let's do it. Could you do it for me, just afraid to mess things up again :( ?

**Comment by ScottTodd** [comment]
> > > This should have been merged with a merge commit. It may complicate the next set of merges when Copybara gets involved.
> > > The merge commit message should also have matched the PR description - the `PiperOrigin-RevId` in particular causes further issues with Copybara.
> > 
> > 
> > We may need to `git revert` the squashed merge of this PR, or even force push over to undo it.
> 
> I've created #2716, can't it be done with that change? If force push is easier, let's do it. Could you do it for me, just afraid to mess things up again :( ?

I'm not positive, the merge process can be fragile. Let's check with @GMNGeoffrey .

**Pull request merged**
