### PR TITLE
Fix compiler flags for GCC

### PR DESCRIPTION
**Pull request by marbre**
This brings IREE closer to beeing build with GCC, see https://github.com/google/iree/issues/6#issuecomment-544168619. `-Wno-strict-prototypes` is supported by GCC in general, but only for C/Objective-C. Therefore, moving it to the CLANG flags.

### CODE REVIEW

**Comment by marbre** [comment]
Thanks for the review and the quick response. I will sign the CLA asap. However, I thought it might be a good idea to already start the review process on the PR.

**Comment by marbre** [comment]
@googlebot I signed it!

**Comment by GMNGeoffrey** [comment]
Hey Marius,

What email did you sign the cla with? The commit and pull request are authored by "marius.brehler@iml.fraunhofer.de". Could you please sign with that email?

Thanks!

**Comment by marbre** [comment]
> Hey Marius,
> 
> What email did you sign the cla with? The commit and pull request are authored by "[marius.brehler@iml.fraunhofer.de](mailto:marius.brehler@iml.fraunhofer.de)". Could you please sign with that email?
> 
> Thanks!

The CLA is signed for that email, but it is a cooperate CLA and not a personal CLA.

**Comment by ScottTodd** [comment]
Could you please check through the steps for corporate signers posted by googlebot again? It should automatically switch to "cla: yes" once everything is in order, but we still see the CLA as not signed for some reason. Thanks!

**Comment by marbre** [comment]
I think I have done everything right, but https://cla.developers.google.com/about states "After the agreement is electronically signed, it will need to be reviewed by someone at Google. [..] This normally takes a few days.". So maybe the CLA is not yet processes, since I was informed that it was finally signed from our side last Friday.

**Comment by benvanik** [comment]
@googlebot try again please???

**Comment by benvanik** [comment]
(sorry about the delay on the CLA stuff @marbre - hopefully some lawyercats get to it soon!)
image

**Comment by GMNGeoffrey** [comment]
What's the corporate CLA you should be covered under?

I see "Fraunhofer Institute for Open Communication Systems FOKUS". Is that the right one?

**Comment by GMNGeoffrey** [comment]
@googlebot try again

**Comment by marbre** [comment]
@GMNGeoffrey 
I was told to fill in "Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V. for its Fraunhofer Institute for Material Flow and Logistics (IML)" as corporation name, but it might have got signed by the authorized signer with the corporation name "Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V." filled in.

**Comment by GMNGeoffrey** [comment]
Thanks. Sorry for the bureaucracy :-/ Please let us know when you've got an update. I'm eager to try out the cmake changes :-)

**Comment by marbre** [comment]
@GMNGeoffrey 
No need to apologize :) I will let you know once the CLA is signed again.
Although not everything is implemented yet, I hope the changes boosts the build process with CMake. Can't wait to look deeper into IREE (probably into the C99 HAL or something like this).

**Comment by marbre** [comment]
@googlebot I signed it!

Finally, the CLA was signed again today :) I think it might still last some days until the CLA was checked from your side. Anyway, the contributions can hopefully land in the repo soon.

**Comment by GMNGeoffrey** [comment]
Yeah I'm still not seeing it show up on our side. We'll check back next week.

For Googlers, here's a direct link to the page listing the corporate CLAs: http://go/corpclas. Mostly so I don't have to click through a million pages to find it again.

**Comment by marbre** [comment]
@googlebot Rescan

**Comment by GMNGeoffrey** [comment]
Ugh sorry I ended up getting credited this commit in master :-( It's because I updated it when I merged in master.

**Comment by marbre** [comment]
No big deal :) This is more iree-copybara-bot fault, squashing all commits into a single one ;D

**Comment by GMNGeoffrey** [comment]
Well we're the ones who control what the bot does (mostly). Squashing everything into a single commit is the behavior we want, I think (equivalent to "squash and merge" on GitHub). I didn't realize clicking the nice "update" button on GitHub would confuse the bot. Basically the issue is that GitHub always associates pull requests with your primary email and so to avoid all our commits getting linked to our personal emails instead of our work ones, the bot takes the commit author from the HEAD commit. Anyway, we'll just avoid clicking the update button on GitHub in the future. The FR on GitHub to handle this properly is https://github.com/todogroup/gh-issues/issues/32

**Comment by marbre** [comment]
Ah okay, I see. Yeah, if squashing all commits of a PR is preferred that is of course okay, but somehow kills git-bisect. Anyway, I am fine with it, if that is the preferred workflow here :) I was just a little confused as I am more used to workflows where explicit squashing is mandatory and where in addition commits are rebased into branches instead of merging branches of pull requests (like in Gentoo Linux's development process).

**Comment by GMNGeoffrey** [comment]
When you say it kills git-bisect, do you mean just because commits are bigger in the master tree? How is that different than explicit squashing (I assume you mean that a PR has to be squashed before it's sent)? Personally, I'm generally a fan of small commits/PRs for identifying errors, as you mention, as well as for ease of review, merging, rollback, etc. I think it makes sense to move a PR into master as a single commit though. Usually the extra fix-up commits aren't really separate things we want to test, but maybe I'm misunderstanding or you've had a different experience. Especially here, the extra commit wasn't really an extra commit so much as me foolishly clicking a big shiny button in GitHub that I thought would do something I wanted :-D

We're generally trying to make the workflows here easy and understandable for external contributors, and part of that is to use patterns that are well-established. We'd welcome any feedback on how to improve things (including by just documenting them better in CONTRIBUTING.md). We're a little limited by our tooling as we actually have an internal source of truth and what actually happens is that the PR is imported into there, committed, and then migrated back out to GitHub. The effect is basically the same as rebasing the branch onto master (except that it looks much worse on the GitHub UI, which is on my long todo list of OSS infra improvements).

The tool we use for the copying is called copybara. The OSS version is here (I think it's basically the same as the internal one except probably doesn't include the configuration specific to Google's internal mono-repo, but haven't investigated thoroughly): https://github.com/google/copybara

**Comment by marbre** [comment]
Yes, that is what I essentially mean. Those big commits do not allow easy bisecting nor is it easy to see what happened when looking at the git log. With explicit squashing I don't mean to squash all the commits belonging to a single PR. Instead, small extra fix-up commits should be squashed to those commits they "fix". So either the fix-up commits get reordered and than squashed to the commits they should fix **or** you rebase interactively, pick the commits and fix the commit directly. Thus you never have those nasty fix-up commits in your repository. This allows you to go ahead with useful, small commits and IMHO those can be safely moved into the master. So more work for the commiter/author of the PR, but allows to profit from small (more or less self consistent) commits ;-D

So anyway, I am absolutely fine with the workflow here. I just wasn't used to squashing all commits to a single one prior to merging. Before, I just got to know the "merge all commits as is"  into the master or "clean your commits, will be merged afterwards" (as described above).

**Comment by GMNGeoffrey** [comment]
Ah I see, that makes sense. The bot workflow I think has to pull in all the commits in a PR as a single "changelist" (CL), which we then run internal tests on, etc. Also we generally try to test each thing that is committed to master, and PRs only get tested as a whole. Internally, we try to make CLs small (well, I do. Opinions vary). I think a similar goal for PRs would be good, as they're going to map to a single CL. So that means, for example, trying to separate refactoring into a different PR than a functionality change.

Of course that runs into problems if there's any dependency between your PRs. We've got decent support for it internally, but I don't know whether git has good workflows for it. I guess you can branch off your existing PR branch? I'm not sure.

I'll add more detail on all this to the contributing guide, so people know what to expect

**Pull request closed without merging**
