### PR TITLE
Drop vectorization from buildkite builds due to failure.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
Failure starts at google->main integration (PR #5182)

### CODE REVIEW

**Review by GMNGeoffrey — APPROVED** [review]

**Comment by hanhanW** [comment]
It looks like there are some issues in the pipeline: https://gist.github.com/hanhanW/3c866378aae13988f2ce4b67db12bafb
I'm not sure why we still see vector stuff there, btw.

full log:
https://buildkite.com/organizations/iree/pipelines/iree-android-benchmark/builds/2121/jobs/e41a7a07-3b20-4271-b7b8-75ec5f82ca1c/raw_log

To repro on your local side.

1) Download the mlir file from: https://storage.googleapis.com/iree-model-artifacts/mobilenet-v2.tar.gz
2) Run `iree-translate mobilenet-v2/iree_input.mlir --iree-mlir-to-vm-bytecode-module --iree-hal-target-backends=vulkan-spirv --iree-vulkan-target-triple=valhall-g77-unknown-android10 --iree-hal-benchmark-dispatch-repeat-count=64 -o /tmp/a.vmfb`. (you probably don't need the last flag)

**Comment by MaheshRavishankar** [comment]
@ThomasRaoux would you be able to take a look?

**Comment by ThomasRaoux** [comment]
> @ThomasRaoux would you be able to take a look?

Sure, I’ll take a look tomorrow morning.

**Comment by ThomasRaoux** [comment]
> @ThomasRaoux would you be able to take a look?

For the problem of vectorization kicking in even when the option is off it seems to be because we miss the check for convolution case. Sent a PR for it:
https://github.com/google/iree/pull/5187
This fix compilation when vectorization option is off. The problem with vectorization is still there.

**Comment by hanhanW** [comment]
Hey @MaheshRavishankar, I can help on triggering iree-android-benchmark after you rebase to ToT.

**Comment by ThomasRaoux** [comment]
> Hey @MaheshRavishankar, I can help on triggering iree-android-benchmark after you rebase to ToT.

Do we still want to push this PR? Build is back to green, we should just add tests to make sure we can such breaks before?

**Comment by hanhanW** [comment]
> Do we still want to push this PR? Build is back to green, we should just add tests to make sure we can such breaks before?

I think you are right. I missed that the build is green now. We should add more tests.

**Comment by MaheshRavishankar** [comment]
Yeah, please add more e2e tests with vectorization on matmul and conv paths. I am not sure we have enough here.

**Comment by MaheshRavishankar** [comment]
Dropping this PR.

**Pull request closed without merging**
