### PR TITLE
Add support for vectorizing depthwise convolution ops.

### PR DESCRIPTION
**Pull request by hanhanW**

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
(awww.. I came here thinking you already had perf numbers... waiting for benchmarks to run...)

**Comment by hanhanW** [comment]
> (awww.. I came here thinking you already had perf numbers... waiting for benchmarks to run...)

yeah, my local phone is weird today. I can't reproduce what I had in https://github.com/google/iree/commit/00a3f2c1a46ff9167c567ee3466baaf8c8a0d881. I always got 380 ms for DeepLabV3, versus 188 ms in the commit. I thought something messed up, but it seems not. The perf numbers in perf.iree.dev look good. Thus, I decided to let bot run benchmarks for me this time. I can summarize it somewhere once I get those numbers. :D

**Comment by MaheshRavishankar** [comment]
> > (awww.. I came here thinking you already had perf numbers... waiting for benchmarks to run...)
> 
> yeah, my local phone is weird today. I can't reproduce what I had in [00a3f2c](https://github.com/google/iree/commit/00a3f2c1a46ff9167c567ee3466baaf8c8a0d881). I always got 380 ms for DeepLabV3, versus 188 ms in the commit. I thought something messed up, but it seems not. The perf numbers in perf.iree.dev look good. Thus, I decided to let bot run benchmarks for me this time. I can summarize it somewhere once I get those numbers. :D

Hehe, I was just joking. The benchmark summary from the runs is fine.

**Comment by hanhanW** [comment]
We have around 5 - 10 % improvements for vision models.

The regression looks like noises because it only happens on Pixel 6. We usually see similar multiplier improvements in Pixel 4 and Pixel 6.

**Review by MaheshRavishankar — APPROVED** [review]

**Pull request merged**
