### PR TITLE
Avoid crash when InterfaceBindingSubspanOp doesn't return Memref

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
`InterfaceBindingSubspanOp` can return any type:
https://github.com/google/iree/blob/4f02b7e604c9/iree/compiler/Dialect/HAL/IR/HALOps.td#L2350

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]
This is fine, but could you give me a repro for the error. The root cause is probably much higher up the stack.

**Comment by GMNGeoffrey** [comment]
Whoops, those lines were copy-pasted from a local version where I cast to the correct op (I don't really understand why the LLVM converters aren't doing that).

**Comment by GMNGeoffrey** [comment]
> This is fine, but could you give me a repro for the error. The root cause is probably much higher up the stack.

Yeah I'm working on repros. The model is big, so it's hard to get isolated repro cases, especially when passes don't have clear input/output contracts (this is what I was talking about the other day). Here's one: https://github.com/google/iree/issues/7254

**Comment by GMNGeoffrey** [comment]
(and somehow unknown locations have crept into our input pipeline, which are burying the real locations :confused:)

**Comment by GMNGeoffrey** [comment]
```
<unknown>:0: error: 'llvm.getelementptr' op operation's operand is null
<unknown>:0: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"llvm", "system-elf-x86_64", {data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "x86_64-grtev4-linux-gnu"}>
<unknown>:0: error: failed to serialize executables
```

:-(

**Pull request merged**
