### PR TITLE
Fixed vulkan errors with not destroyed lists and incorrect error check on pybindings

### PR DESCRIPTION
**Pull request by rsuderman**
Lists were not being freed resulting in errors for some of our vulkan tests.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
> non-uninitialized?

You mean not released? I think uninitialized would be if it was never initialized...

**Comment by rsuderman** [comment]
> non-uninitialized?

Yeah... uninitialize is used to delete lists. Tried to use the APIs wording but definitely felt clunky. Renamed.

**Comment by benvanik** [comment]
This isn't correct; the inputs/outputs cannot be deinitialized like that - they need to be reset() (like std::unique_ptr)

**Comment by benvanik** [comment]
fix here: https://github.com/google/iree/pull/2589 (next time, please let me review changes like this)

**Pull request merged**
