### PR TITLE
Disable folding unit dimension reshapes during fusion

### PR DESCRIPTION
**Pull request by ThomasRaoux**
This fixes regression in MobileBert GPU.

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
> This fixes regression in MobileBert GPU.

Do you still need to look at impact on use of tile+fuse?

**Comment by ThomasRaoux** [comment]
> > This fixes regression in MobileBert GPU.
> 
> Do you still need to look at impact on use of tile+fuse?
actually it does increase the number of dispatch regions in MobileNet from 93 to 111 so it does seem like we need to refine this.

**Comment by antiagainst** [comment]
Yeah this is needed for MobileNet models. We need to look a bit deeper to see if there is a better way to fix it.. Let's chat a bit more tomorrow.

**Comment by ThomasRaoux** [comment]
> Yeah this is needed for MobileNet models. We need to look a bit deeper to see if there is a better way to fix it.. Let's chat a bit more tomorrow.

After talking to Mahesh I'm adding a fine grain control to the reshape folding: https://reviews.llvm.org/D101917. 
It shouldn't be too hard to come up with a simple logic to do the right choice

**Comment by ThomasRaoux** [comment]
Closing this PR, I'll send a new one once the llvm changes make it to IREE.

**Pull request closed without merging**
