### PR TITLE
Handle offsets/strides correctly while rewriting destructive updates.

### LINKED ISSUE #8790: mhlo.gather to mhlo.select results in incorrect slice selected
It appears that a slice into select is grabbing the wrong section of buffer before executing the select operation. Speculatively, I am guessing the dispatch changes are grabbing the full parent buffer rather than the slice section.

Reproduction:

1. Download attached [file](https://github.com/google/iree/files/8430430/test.mlir.zip) and unzip test.mlir
2. Compile to target dylib:
  `iree-compile /tmp/test.mlir --iree-input-type=mhlo --iree-hal-target-backends=dylib -o /tmp/test.vmfb`
3. Execute with iree-run-module: 
  `iree-run-module --driver=dylib --module_file=/tmp/test.vmfb --entry_function=main --function_input="3x4xf32=[[0.1 0.2, 0.3, 0.4], [0.2, 0.3, 0.4, 0.5], [0.3, 0.4, 0.5, 0.6]]"`
 4. Results are as shown below:
` 2x4xf32=[0.1 0.2 0.3 0][0.2 0.3 0 0]`
but should be:
`2x4xf32=[0.2 0.3 0 0][0.3 0 0 0]`

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
The current rewrite of destructive updates ignores all offsets/strides
of the source flow.dispatch.tensor.load/store. Fix that to handle these
offset and strides correctly.

Fixes #8790 , #8825

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
This PR has a failing test for me locally. It seems to be failing for something totally unrelated. So hoping its a flake while I triage that.

**Review by benvanik — APPROVED** [review]
you have a stray test.vmfb you'll want to delete

**Comment by MaheshRavishankar** [comment]
I have a failing test on this PR that might (but most probably is not related to this PR). Here is the example

```
#config = #iree_codegen.lowering_config<tile_sizes = [[2], [2], [0]]>
#executable_layout = #hal.executable.layout<push_constants = 0, sets = [
  #hal.descriptor_set.layout<0, bindings = [
    #hal.descriptor_set.binding<0, storage_buffer>,
    #hal.descriptor_set.binding<1, storage_buffer>
  ]>
]>
#executable_target_embedded_elf_arm_64_ = #hal.executable.target<"llvm", "embedded-elf-arm_64", {
  data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128",
  native_vector_size = 16 : index,
  target_triple = "aarch64-unknown-unknown-eabi-elf"
}>
#translation = #iree_codegen.translation_info<CPUTileFuseAndVectorize>
hal.executable private @rank_reduced_slice {
  hal.executable.variant public @llvm, target = #executable_target_embedded_elf_arm_64_ {
    hal.executable.entry_point public @rank_reduced_slice layout(#executable_layout) {translation_info = #translation}
    builtin.module {
      func.func @rank_reduced_slice() {
        %in_binding = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer)
            : !flow.dispatch.tensor<readonly:1x40xf32>
        %out_binding = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer)
            : !flow.dispatch.tensor<writeonly:10xf32>
        %in = flow.dispatch.tensor.load %in_binding, offsets = [0, 10], sizes = [1, 10], strides = [1, 1]
            : !flow.dispatch.tensor<readonly:1x40xf32> -> tensor<10xf32>
        %out = linalg.init_tensor [10] : tensor<10xf32>
        %val = linalg.generic {
            indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>],
            iterator_types = ["parallel"]}
            ins(%in : tensor<10xf32>) outs(%out : tensor<10xf32>) attrs =  {lowering_config = #config} {
          ^bb0(%b0 : f32, %b1 : f32):
            %0 = arith.addf %b0, %b0 : f32
            linalg.yield %0 : f32
          } -> tensor<10xf32>
        flow.dispatch.tensor.store %val, %out_binding, offsets = [0], sizes = [10], strides = [1]
            : tensor<10xf32> -> !flow.dispatch.tensor<writeonly:10xf32>
        return
      }
    }
  }
}
```

with  this command line

```
$iree-opt -pass-pipeline="hal.executable(hal.executable.variant(builtin.module(func.func(iree-codegen-tile-and-distribute-to-workgroups))))"  failing_test.mlir 
```

Current output is 
```
#config = #iree_codegen.lowering_config<tile_sizes = [[2], [2], [0]]>
#executable_layout = #hal.executable.layout<push_constants = 0, sets = [#hal.descriptor_set.layout<0, bindings = [#hal.descriptor_set.binding<0, storage_buffer>, #hal.descriptor_set.binding<1, storage_buffer>]>]>
#executable_target_embedded_elf_arm_64_ = #hal.executable.target<"llvm", "embedded-elf-arm_64", {data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "aarch64-unknown-unknown-eabi-elf"}>
#map0 = affine_map<()[s0] -> (s0 * 2)>
#map1 = affine_map<(d0) -> (d0)>
#translation = #iree_codegen.translation_info<CPUTileFuseAndVectorize>
module {
  hal.executable private @rank_reduced_slice {
    hal.executable.variant public @llvm, target = #executable_target_embedded_elf_arm_64_ {
      hal.executable.entry_point public @rank_reduced_slice layout(#executable_layout) {translation_info = #translation}
      builtin.module {
        func @rank_reduced_slice() {
          %c10 = arith.constant 10 : index
          %c1 = arith.constant 1 : index
          %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) : !flow.dispatch.tensor<readonly:1x40xf32>
          %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) : !flow.dispatch.tensor<writeonly:10xf32>
          %2 = flow.dispatch.tensor.load %0, offsets = [0, 10], sizes = [1, 10], strides = [1, 1] : !flow.dispatch.tensor<readonly:1x40xf32> -> tensor<10xf32>
          %3 = linalg.init_tensor [10] : tensor<10xf32>
          %workgroup_id_x = hal.interface.workgroup.id[0] : index
          %workgroup_count_x = hal.interface.workgroup.count[0] : index
          %4 = affine.apply #map0()[%workgroup_id_x]
          %5 = affine.apply #map0()[%workgroup_count_x]
          scf.for %arg0 = %4 to %c10 step %5 {
            %6 = tensor.extract_slice %2[%arg0] [2] [1] : tensor<10xf32> to tensor<2xf32>
            %7 = tensor.extract_slice %3[%arg0] [2] [1] : tensor<10xf32> to tensor<2xf32>
            %8 = linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel"]} ins(%6 : tensor<2xf32>) outs(%7 : tensor<2xf32>) attrs =  {lowering_config = #config} {
            ^bb0(%arg1: f32, %arg2: f32):
              %9 = arith.addf %arg1, %arg1 : f32
              linalg.yield %9 : f32
            } -> tensor<2xf32>
            flow.dispatch.tensor.store %8, %1, offsets = [%arg0], sizes = [2], strides = [%c1] : tensor<2xf32> -> !flow.dispatch.tensor<writeonly:10xf32>
          }
          return
        }
      }
    }
  }
}
```

The error is that `%2 = flow.dispatch.tensor.load` has to be folded with  `tensor.extract_slice %2`...
Setting a break point here https://github.com/google/iree/blob/6bf7ce64f63ff99f0c935a22459354e54f0c352e/iree/compiler/Codegen/Common/DestructiveUpdateUtils.cpp#L209

```
 auto loadOp = op.source().getDefiningOp<IREE::Flow::DispatchTensorLoadOp>();
 if (!loadOp) {
   ...
}
```
The `if` is not taken even though `op.source()` is defined by `IREE::Flow::DispatchTensorLoadOp`.

**Comment by MaheshRavishankar** [comment]
> I have a failing test on this PR that might (but most probably is not related to this PR). Here is the example
> 
> ```
> #config = #iree_codegen.lowering_config<tile_sizes = [[2], [2], [0]]>
> #executable_layout = #hal.executable.layout<push_constants = 0, sets = [
>   #hal.descriptor_set.layout<0, bindings = [
>     #hal.descriptor_set.binding<0, storage_buffer>,
>     #hal.descriptor_set.binding<1, storage_buffer>
>   ]>
> ]>
> #executable_target_embedded_elf_arm_64_ = #hal.executable.target<"llvm", "embedded-elf-arm_64", {
>   data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128",
>   native_vector_size = 16 : index,
>   target_triple = "aarch64-unknown-unknown-eabi-elf"
> }>
> #translation = #iree_codegen.translation_info<CPUTileFuseAndVectorize>
> hal.executable private @rank_reduced_slice {
>   hal.executable.variant public @llvm, target = #executable_target_embedded_elf_arm_64_ {
>     hal.executable.entry_point public @rank_reduced_slice layout(#executable_layout) {translation_info = #translation}
>     builtin.module {
>       func.func @rank_reduced_slice() {
>         %in_binding = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer)
>             : !flow.dispatch.tensor<readonly:1x40xf32>
>         %out_binding = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer)
>             : !flow.dispatch.tensor<writeonly:10xf32>
>         %in = flow.dispatch.tensor.load %in_binding, offsets = [0, 10], sizes = [1, 10], strides = [1, 1]
>             : !flow.dispatch.tensor<readonly:1x40xf32> -> tensor<10xf32>
>         %out = linalg.init_tensor [10] : tensor<10xf32>
>         %val = linalg.generic {
>             indexing_maps = [affine_map<(d0) -> (d0)>, affine_map<(d0) -> (d0)>],
>             iterator_types = ["parallel"]}
>             ins(%in : tensor<10xf32>) outs(%out : tensor<10xf32>) attrs =  {lowering_config = #config} {
>           ^bb0(%b0 : f32, %b1 : f32):
>             %0 = arith.addf %b0, %b0 : f32
>             linalg.yield %0 : f32
>           } -> tensor<10xf32>
>         flow.dispatch.tensor.store %val, %out_binding, offsets = [0], sizes = [10], strides = [1]
>             : tensor<10xf32> -> !flow.dispatch.tensor<writeonly:10xf32>
>         return
>       }
>     }
>   }
> }
> ```
> 
> with this command line
> 
> ```
> $iree-opt -pass-pipeline="hal.executable(hal.executable.variant(builtin.module(func.func(iree-codegen-tile-and-distribute-to-workgroups))))"  failing_test.mlir 
> ```
> 
> Current output is
> 
> ```
> #config = #iree_codegen.lowering_config<tile_sizes = [[2], [2], [0]]>
> #executable_layout = #hal.executable.layout<push_constants = 0, sets = [#hal.descriptor_set.layout<0, bindings = [#hal.descriptor_set.binding<0, storage_buffer>, #hal.descriptor_set.binding<1, storage_buffer>]>]>
> #executable_target_embedded_elf_arm_64_ = #hal.executable.target<"llvm", "embedded-elf-arm_64", {data_layout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128", native_vector_size = 16 : index, target_triple = "aarch64-unknown-unknown-eabi-elf"}>
> #map0 = affine_map<()[s0] -> (s0 * 2)>
> #map1 = affine_map<(d0) -> (d0)>
> #translation = #iree_codegen.translation_info<CPUTileFuseAndVectorize>
> module {
>   hal.executable private @rank_reduced_slice {
>     hal.executable.variant public @llvm, target = #executable_target_embedded_elf_arm_64_ {
>       hal.executable.entry_point public @rank_reduced_slice layout(#executable_layout) {translation_info = #translation}
>       builtin.module {
>         func @rank_reduced_slice() {
>           %c10 = arith.constant 10 : index
>           %c1 = arith.constant 1 : index
>           %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) : !flow.dispatch.tensor<readonly:1x40xf32>
>           %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) : !flow.dispatch.tensor<writeonly:10xf32>
>           %2 = flow.dispatch.tensor.load %0, offsets = [0, 10], sizes = [1, 10], strides = [1, 1] : !flow.dispatch.tensor<readonly:1x40xf32> -> tensor<10xf32>
>           %3 = linalg.init_tensor [10] : tensor<10xf32>
>           %workgroup_id_x = hal.interface.workgroup.id[0] : index
>           %workgroup_count_x = hal.interface.workgroup.count[0] : index
>           %4 = affine.apply #map0()[%workgroup_id_x]
>           %5 = affine.apply #map0()[%workgroup_count_x]
>           scf.for %arg0 = %4 to %c10 step %5 {
>             %6 = tensor.extract_slice %2[%arg0] [2] [1] : tensor<10xf32> to tensor<2xf32>
>             %7 = tensor.extract_slice %3[%arg0] [2] [1] : tensor<10xf32> to tensor<2xf32>
>             %8 = linalg.generic {indexing_maps = [#map1, #map1], iterator_types = ["parallel"]} ins(%6 : tensor<2xf32>) outs(%7 : tensor<2xf32>) attrs =  {lowering_config = #config} {
>             ^bb0(%arg1: f32, %arg2: f32):
>               %9 = arith.addf %arg1, %arg1 : f32
>               linalg.yield %9 : f32
>             } -> tensor<2xf32>
>             flow.dispatch.tensor.store %8, %1, offsets = [%arg0], sizes = [2], strides = [%c1] : tensor<2xf32> -> !flow.dispatch.tensor<writeonly:10xf32>
>           }
>           return
>         }
>       }
>     }
>   }
> }
> ```
> 
> The error is that `%2 = flow.dispatch.tensor.load` has to be folded with `tensor.extract_slice %2`... Setting a break point here
> 
> https://github.com/google/iree/blob/6bf7ce64f63ff99f0c935a22459354e54f0c352e/iree/compiler/Codegen/Common/DestructiveUpdateUtils.cpp#L209
> 
> ```
>  auto loadOp = op.source().getDefiningOp<IREE::Flow::DispatchTensorLoadOp>();
>  if (!loadOp) {
>    ...
> }
> ```
> 
> The `if` is not taken even though `op.source()` is defined by `IREE::Flow::DispatchTensorLoadOp`.

This was not the issue. Its a red herring. Issue was w.r.t handling rank-reduced operations. Should be fixed now

**Pull request merged**
