### PR TITLE
Bump LLVM to 82c18dd9add0fa96ac95256fd1b0b1202f9f56dd

### PR DESCRIPTION
**Pull request by nicolasvasilache**

### CODE REVIEW

**Comment by hanhanW** [comment]
> Do we really need to bump it or would a cherry pick work. All checks are fine, but it might be better to keep bumping LLVM, MHLO and TF together. Also LLVM bump PRs probably needs someone from core IREE team to be reviewer.

I can start an integration later today. TF has checked in the needed cherry-pick commit, so we can make LLVM version aligned with TF/MHLO repo.

**Comment by MaheshRavishankar** [comment]
> > Do we really need to bump it or would a cherry pick work. All checks are fine, but it might be better to keep bumping LLVM, MHLO and TF together. Also LLVM bump PRs probably needs someone from core IREE team to be reviewer.
> 
> I can start an integration later today. TF has checked in the needed cherry-pick commit, so we can make LLVM version aligned with TF/MHLO repo.

Thanks Hanhan!

**Comment by nicolasvasilache** [comment]
> Do we really need to bump it or would a cherry pick work. All checks are fine, but it might be better to keep bumping LLVM, MHLO and TF together. Also LLVM bump PRs probably needs someone from core IREE team to be reviewer.

My expectation is that a bump that is green is always better than a cherry-pick as there is literally 0 possible surprises in either projects (OTOH a cheery-pick may well fail to build with TF if we tried). Is this inaccurate?

**Comment by hanhanW** [comment]
> My expectation is that a bump that is green is always better than a cherry-pick as there is literally 0 possible surprises in either projects (OTOH a cherry-pick may well fail to build with e.g. TF if we tried). Is this inaccurate?

Sometimes it may break internal stuff because the internal integration is not happened yet. I think you're right for most of cases if there are no IREE file changes.

**Comment by hanhanW** [comment]
This is covered in https://github.com/google/iree/pull/8786

**Comment by nicolasvasilache** [comment]
sg, thanks @hanhanW !

**Pull request closed without merging**
