### PR TITLE
bump tracy to 0.8.1

### PR DESCRIPTION
**Pull request by bjacob**
incomplete - need capture builds for ARM - @antiagainst

### CODE REVIEW

**Comment by bjacob** [comment]
Actually, just noticed that Tracy's own Unix makefile uses `nfd_portal.cpp` and adds the libdbus dependency. We should probably do the same to avoid diverging. i'll do it tomorrow.

**Comment by antiagainst** [comment]
SG. Please feel free to ping me afterwards. I'll push another commit to update the tracy-capture build. :)

**Comment by bjacob** [comment]
@antiagainst: should be good to go now.

**Review by antiagainst — APPROVED** [review]

**Comment by bjacob** [comment]
Thanks you!!

**Pull request merged**
