### PR TITLE
Fix-forward sync.h include on Android.

### PR DESCRIPTION
**Pull request by ScottTodd**
Following https://github.com/google/iree/pull/3884 now that I have Android building locally.

### CODE REVIEW

**Comment by ScottTodd** [comment]
@GMNGeoffrey can we trigger an Android build to run on presubmit on this?

**Comment by GMNGeoffrey** [comment]
> @GMNGeoffrey can we trigger an Android build to run on presubmit on this?

The way it's configured currently, the answer appears to be "no", unfortunately. The steps are each configured to skip if the branch isn't "main" (instead of just limiting the pipeline to "main"). Let me look into changing that. Even then though, there doesn't seem to be a way to manually trigger a build for a branch in a fork, which is annoying :-/ I'll contact buildkite support.

**Comment by GMNGeoffrey** [comment]
> > @GMNGeoffrey can we trigger an Android build to run on presubmit on this?
> 
> The way it's configured currently, the answer appears to be "no", unfortunately. The steps are each configured to skip if the branch isn't "main" (instead of just limiting the pipeline to "main"). Let me look into changing that. Even then though, there doesn't seem to be a way to manually trigger a build for a branch in a fork, which is annoying :-/ I'll contact buildkite support.

I think I figured out a way to make BuildKite test this.

**Review by benvanik — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
> > > @GMNGeoffrey can we trigger an Android build to run on presubmit on this?
> > 
> > 
> > The way it's configured currently, the answer appears to be "no", unfortunately. The steps are each configured to skip if the branch isn't "main" (instead of just limiting the pipeline to "main"). Let me look into changing that. Even then though, there doesn't seem to be a way to manually trigger a build for a branch in a fork, which is annoying :-/ I'll contact buildkite support.
> 
> I think I figured out a way to make BuildKite test this.

Nope. It isn't working. If you tested locally, go ahead and merge

**Pull request merged**
