### PR TITLE
Add musl submodule for math function implementation.

### LINKED ISSUE #4717: LLVM codegen is pulling in libc/libm (malloc, free, floorf) functions and shouldn't be
Here's where the flag is set:

https://github.com/google/iree/blob/af39f98403a30b85442130f25ceec5eb53e0c60d/iree/compiler/Dialect/HAL/Target/LLVM/internal/UnixLinkerTool.cpp#L127-L129

We punted on this back with https://github.com/google/iree/issues/2810 and now the flag is even leaking into our [Python documentation](https://github.com/google/iree/blob/main/bindings/python/pyiree/jax/README.md#ahead-of-time-compilation).

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
This adds musl as a submodule of IREE. Using the source (with help of
custom makefiles), the .ll file for math functions needed are
generated and linked into `librt.bc`.

Fixes #4717

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
This works for floorf. Looks like I have a segfault on some other tests. Will track that down, but would like to get some feedback on general direction.

**Comment by benvanik** [comment]
(commit has `suubmodule` typo :)

**Comment by benvanik** [comment]
Ah the lld errors are because we need to add the dep on lld now that gcmn has it in the llvm bazel files

**Comment by MaheshRavishankar** [comment]
> Ah the lld errors are because we need to add the dep on lld now that gcmn has it in the llvm bazel files

How do I add this dependence on lld from llvm?

**Comment by benvanik** [comment]
I'm not actually sure how to reference the full path (will see if I can dig it up) but this is the rule:
https://github.com/llvm/llvm-project/blob/693a95a69416e23a31e46d3d2c81e854688e606e/utils/bazel/llvm-project-overlay/lld/BUILD.bazel#L334

 and we'd want to add it to `data =` on iree-opt/iree-translate/iree-run-mlir here: https://github.com/google/iree/blob/1c497ab62d7817c9cb492cdb3413b0164983b221/iree/tools/BUILD

**Comment by benvanik** [comment]
nice is just `@llvm-project//lld`
so
`data = ["@llvm-project//lld"]` should (in theory) be enough

**Comment by MaheshRavishankar** [comment]
> I'm not actually sure how to reference the full path (will see if I can dig it up) but this is the rule:
> [llvm/llvm-project@`693a95a`/utils/bazel/llvm-project-overlay/lld/BUILD.bazel#L334](https://github.com/llvm/llvm-project/blob/693a95a69416e23a31e46d3d2c81e854688e606e/utils/bazel/llvm-project-overlay/lld/BUILD.bazel#L334)
> 
> and we'd want to add it to `data =` on iree-opt/iree-translate/iree-run-mlir here: [`1c497ab`/iree/tools/BUILD](https://github.com/google/iree/blob/1c497ab62d7817c9cb492cdb3413b0164983b221/iree/tools/BUILD)

Great! Thanks. Thats what I was looking for

**Comment by benvanik** [comment]
actually try the `@llvm-project//lld:gen_lld` if you get errors (like can't find lld) - wish that `:lld` was `:gen_lld` but oh well

we already do this on the cmake side so if there are errors once the dep is added then it may be bazel-specific pathing we need to fix in https://github.com/google/iree/blob/69afdd2ebc5ca91b62c91bd254478a633e62a643/iree/compiler/Dialect/HAL/Target/LLVM/internal/EmbeddedLinkerTool.cpp#L58

happy to help if you run into issues!

**Comment by MaheshRavishankar** [comment]
Some of the other unrelated tests seem to hit a segfault with this change. Looking at the assembly, there no calls etc. For example the `broadcast_in_dim.mlir` tests fails with this stack trace when running

```
iree-check-module --driver=dylib broadcast_in_dim.vmfb
```

```
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:502
#1  0x000000000046ed2c in iree_elf_module_load_segments (raw_data=..., load_state=0x7fffffff96f0, module=0x61a6e8) at /home/ravishankarm/Development/iree/iree/iree/hal/local/elf/elf_module.c:275
#2  0x000000000046e8c9 in iree_elf_module_initialize_from_memory (raw_data=..., import_table=0x0, host_allocator=..., out_module=0x61a6e8) at /home/ravishankarm/Development/iree/iree/iree/hal/local/elf/elf_module.c:589
#3  0x000000000046e391 in iree_hal_elf_executable_create (caching_mode=7, elf_data=..., executable_layout_count=2, executable_layouts=0x61a680, import_provider=..., host_allocator=..., out_executable=0x7fffffff99a0) at /home/ravishankarm/Development/iree/iree/iree/hal/local/loaders/embedded_library_loader.c:156
#4  0x000000000046e174 in iree_hal_embedded_library_loader_try_load (base_executable_loader=0x60aba0, executable_spec=0x7fffffff9968, out_executable=0x7fffffff99a0) at /home/ravishankarm/Development/iree/iree/iree/hal/local/loaders/embedded_library_loader.c:329
#5  0x000000000049375f in iree_hal_executable_loader_try_load (executable_loader=0x60aba0, executable_spec=0x7fffffff9968, out_executable=0x7fffffff99a0) at /home/ravishankarm/Development/iree/iree/iree/hal/local/executable_loader.c:100
#6  0x0000000000495356 in iree_hal_local_executable_cache_prepare_executable (base_executable_cache=0x619e00, executable_spec=0x7fffffff9968, out_executable=0x7fffffff99a0) at /home/ravishankarm/Development/iree/iree/iree/hal/local/local_executable_cache.c:114
#7  0x000000000054ba28 in iree_hal_executable_cache_prepare_executable (executable_cache=0x619e00, executable_spec=0x7fffffff9968, out_executable=0x7fffffff99a0) at /home/ravishankarm/Development/iree/iree/iree/hal/executable_cache.c:64
#8  0x000000000044a7fe in iree_hal_module_executable_create (stack=0x7fffffffb4f0, module=0x615f80, state=0x616d30, args=0x7fffffff9cc0, rets=0x7fffffff9cb0) at /home/ravishankarm/Development/iree/iree/iree/modules/hal/module.c:919
#9  0x000000000055bd10 in iree_vm_shim_rrrCrD_r (stack=0x7fffffffb4f0, call=0x7fffffff9c70, target_fn=0x44a4c0 <iree_hal_module_executable_create>, module=0x615f80, module_state=0x616d30, out_result=0x7fffffffb3e8) at /home/ravishankarm/Development/iree/iree/iree/vm/shims.c:29
#10 0x0000000000559485 in iree_vm_native_module_begin_call (self=0x615f80, stack=0x7fffffffb4f0, call=0x7fffffff9c70, out_result=0x7fffffffb3e8) at /home/ravishankarm/Development/iree/iree/iree/vm/native_module.c:304
#11 0x0000000000464194 in iree_vm_bytecode_issue_import_call (stack=0x7fffffffb4f0, call=..., cconv_results=..., dst_reg_list=0x60d120, out_caller_frame=0x7fffffffb2a8, out_caller_registers=0x7fffffffb288, out_result=0x7fffffffb3e8) at /home/ravishankarm/Development/iree/iree/iree/vm/bytecode_dispatch.c:474
#12 0x000000000046284c in iree_vm_bytecode_call_import_variadic (stack=0x7fffffffb4f0, module_state=0x61a050, import_ordinal=17, caller_registers=..., segment_size_list=0x60d10a, src_reg_list=0x60d114, dst_reg_list=0x60d120, out_caller_frame=0x7fffffffb2a8, out_caller_registers=0x7fffffffb288, out_result=0x7fffffffb3e8) at /home/ravishankarm/Development/iree/iree/iree/vm/bytecode_dispatch.c:605
#13 0x000000000045b022 in iree_vm_bytecode_dispatch (stack=0x7fffffffb4f0, module=0x60aaa0, call=0x7fffffffb3f8, cconv_arguments=..., cconv_results=..., out_result=0x7fffffffb3e8) at /home/ravishankarm/Development/iree/iree/iree/vm/bytecode_dispatch.c:1424
#14 0x000000000044e8e1 in iree_vm_bytecode_module_begin_call (self=0x60aaa0, stack=0x7fffffffb4f0, call=0x7fffffffb3f8, out_result=0x7fffffffb3e8) at /home/ravishankarm/Development/iree/iree/iree/vm/bytecode_module.c:868
#15 0x00000000005537f0 in iree_vm_context_run_function (stack=0x7fffffffb4f0, module=0x60aaa0, function_name=...) at /home/ravishankarm/Development/iree/iree/iree/vm/context.c:58
#16 0x00000000005530d5 in iree_vm_context_register_modules (context=0x616ca0, modules=0x60a2c8, module_count=3) at /home/ravishankarm/Development/iree/iree/iree/vm/context.c:392
#17 0x0000000000552a5d in iree_vm_context_create_with_modules (instance=0x60a8a0, modules=0x60a2c8, module_count=3, allocator=..., out_context=0x60a2f0) at /home/ravishankarm/Development/iree/iree/iree/vm/context.c:240
#18 0x000000000040c29c in iree::(anonymous namespace)::CheckModuleTest::SetUp (this=0x60a2b0) at /home/ravishankarm/Development/iree/iree/iree/tools/iree-check-module-main.cc:62
#19 0x000000000053d834 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x60a2b0, method=&virtual testing::Test::SetUp(), location=0x579474 "SetUp()") at /home/ravishankarm/Development/iree/iree/third_party/googletest/googletest/src/gtest.cc:2607
#20 0x000000000052313b in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x60a2b0, method=&virtual testing::Test::SetUp(), location=0x579474 "SetUp()") at /home/ravishankarm/Development/iree/iree/third_party/googletest/googletest/src/gtest.cc:2643
#21 0x00000000004fdd9c in testing::Test::Run (this=0x60a2b0) at /home/ravishankarm/Development/iree/iree/third_party/googletest/googletest/src/gtest.cc:2677
#22 0x00000000004feb6c in testing::TestInfo::Run (this=0x616150) at /home/ravishankarm/Development/iree/iree/third_party/googletest/googletest/src/gtest.cc:2861
#23 0x00000000004ff3f5 in testing::TestSuite::Run (this=0x6163f0) at /home/ravishankarm/Development/iree/iree/third_party/googletest/googletest/src/gtest.cc:3015
#24 0x000000000050faaf in testing::internal::UnitTestImpl::RunAllTests (this=0x60a570) at /home/ravishankarm/Development/iree/iree/third_party/googletest/googletest/src/gtest.cc:5855
#25 0x00000000005404a4 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x60a570, method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x50f650 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x579d1c "auxiliary test code (environments or event listeners)") at /home/ravishankarm/Development/iree/iree/third_party/googletest/googletest/src/gtest.cc:2607
#26 0x00000000005259db in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x60a570, method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x50f650 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x579d1c "auxiliary test code (environments or event listeners)") at /home/ravishankarm/Development/iree/iree/third_party/googletest/googletest/src/gtest.cc:2643
#27 0x000000000050f606 in testing::UnitTest::Run (this=0x5f6d80 <testing::UnitTest::GetInstance()::instance>) at /home/ravishankarm/Development/iree/iree/third_party/googletest/googletest/src/gtest.cc:5438
#28 0x000000000040c7f1 in RUN_ALL_TESTS () at /home/ravishankarm/Development/iree/iree/third_party/googletest/googletest/include/gtest/gtest.h:2490
#29 0x000000000040b983 in iree::(anonymous namespace)::Run (module_file_path=<incomplete type>, out_exit_code=0x7fffffffdfa4) at /home/ravishankarm/Development/iree/iree/iree/tools/iree-check-module-main.cc:159
#30 0x000000000040af59 in main (argc=2, argv=0x7fffffffe268) at /home/ravishankarm/Development/iree/iree/iree/tools/iree-check-module-main.cc:190
```

Strangely, that test (`iree/e2e/test/xla_ops/broadcast_in_dim.mlir`) has two functions. Commenting out either one makes the test pass

**Comment by benvanik** [comment]
Cool - that may be a bug in the elf loader! Can I repro if I check this PR out and try that test, or are there other changes I'll need?

**Comment by MaheshRavishankar** [comment]
> Cool - that may be a bug in the elf loader! Can I repro if I check this PR out and try that test, or are there other changes I'll need?

You should be able to repro with just this PR and moving the test from the "exclude" in the `xla_ops/BUILD` file

**Review by benvanik — APPROVED** [review]

**Pull request merged**
