### PR TITLE
Replace TODO(GH-123) comments with TODO(#123) comments.

### PR DESCRIPTION
**Pull request by ScottTodd**
The ` #123 ` format is picked up by more editor extensions, like https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github:

github_issue_hover

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Closing paren is now whitelisted. Can you try redoing this PR to make them all `TODO(#1234)`?

**Comment by ScottTodd** [comment]
> Closing paren is now whitelisted. Can you try redoing this PR to make them all `TODO(#1234)`?

Yep! I'd like to test once a new version of the extension is published.

**Comment by ScottTodd** [comment]
> > Closing paren is now whitelisted. Can you try redoing this PR to make them all `TODO(#1234)`?
> 
> Yep! I'd like to test once a new version of the extension is published.

Rebased and updated. Haven't tested though, since the extension has not yet published a new version.

**Comment by ScottTodd** [comment]
Rebased again, proceeding without waiting to test the extension.

**Pull request closed without merging**
