### PR TITLE
Bazel to cmake strict mode

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
WIP. I'll break this into separate PRs once parts of its dep chain get merged.

These changes make it possible to run bazel_to_cmake across the entire iree/ directory (it will skip files it can't convert). Most of this was inventing new ways for it not to edit things it can't get completely right.

I also did some cleanup adding explicit arguments to the various rule functions. This makes the code simpler and more resilient.

Tested:
Ran bazel_to_cmake across the entire directory
56 tests pass before and after this change, but now we've got 154 tests instead of 145.

### CODE REVIEW

**Comment by marbre** [comment]
@GMNGeoffrey It would appreciate if you could skip reordering the deps until `iree-opt` and `iree-translate` got fixed. I know, my approach for keeping it identical to Bazel, isn't the favored one, see #538. However, it really makes life easier, going through the deps.

**Comment by GMNGeoffrey** [comment]
> @GMNGeoffrey It would appreciate if you could skip reordering the deps until `iree-opt` and `iree-translate` got fixed. I know, my approach for keeping it identical to Bazel, isn't the favored one, see #538. However, it really makes life easier, going through the deps.

Sounds good. I commented there, but I'll try to preserve ordering instead for now.

**Comment by marbre** [comment]
> Sounds good. I commented there, but I'll try to preserve ordering instead for now.

With #547 merged, `bazel_to_cmake()` will take care for you :D

**Comment by GMNGeoffrey** [comment]
This was submitted as #589, #590, #592, and #593

**Pull request closed without merging**
