### PR TITLE
Rework includes and directory names for samples.

### PR DESCRIPTION
**Pull request by ScottTodd**
Refactoring after https://github.com/google/iree/pull/8958 shuffled these files around, aiming to remove custom logic in samples that we want users to be able to fork easily.

Paths are reverted from `iree_[sample_name]` back to `[sample_name]`

Includes changed to match:

| | |
| -- | -- |
| C++ includes before | `#include "iree_[sample_name]/[header_name].h"` |
| C++ includes now | `#include "samples/[sample_name]/[header_name].h"` |
| Another option | `#include "header_name.h"` 

The third option would require adding
```
$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
```
to `target_include_directories()` (I already do that in the experimental web samples)

### CODE REVIEW

**Review by benvanik — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
I commented on #8958 about those include paths being weird, but I believe Stella did that for a reason. Did you investigate that reasoning and refute it? If so, please include that sort of thing in the PR description :-)

**Comment by ScottTodd** [comment]
> I commented on #8958 about those include paths being weird, but I believe Stella did that for a reason. Did you investigate that reasoning and refute it? If so, please include that sort of thing in the PR description :-)

Yep, that explanation was in the README:

> Note that for samples which include C/C++ code, the samples/ directory itself
is added as an include directory if depending on the `defs` library.
As such, samples that include headers should include "iree" in their name in
some fashion so that paths are unique.

As the table in the PR description demonstrates, fully qualifying include paths with `samples/` serves the same purpose but without the indirection through a `defs` library.

**Comment by GMNGeoffrey** [comment]
> > I commented on #8958 about those include paths being weird, but I believe Stella did that for a reason. Did you investigate that reasoning and refute it? If so, please include that sort of thing in the PR description :-)
> 
> Yep, that explanation was in the README:
> 
> > Note that for samples which include C/C++ code, the samples/ directory itself
> > is added as an include directory if depending on the `defs` library.
> > As such, samples that include headers should include "iree" in their name in
> > some fashion so that paths are unique.
> 
> As the table in the PR description demonstrates, fully qualifying include paths with `samples/` serves the same purpose but without the indirection through a `defs` library.

Well the "what" was in the README, but I don't think the "why" was

**Comment by benvanik** [comment]
cuz this is ugly and arbitrary:
image

**Comment by ScottTodd** [comment]
Verbose paths help avoid name conflicts in the repo, but these samples need to prioritize being easy to fork into other projects. Local include paths (`./some_header.h`) and fully qualified paths (`samples/some_header.h`) both satisfy that condition, without the risk of conflicting with files in the `iree/` namespace.

I've been tempted to take it a step further by removing Bazel support from these samples and dropping use of our CMake helper functions, like in https://github.com/google/iree/blob/main/samples/variables_and_state/CMakeLists.txt

* https://github.com/google/iree/blob/main/samples/static_library/CMakeLists.txt is halfway between using and not using helper functions
* https://github.com/google/iree/blob/main/samples/simple_embedding/CMakeLists.txt is still very far from "simple" :P

**Pull request merged**
