### PR TITLE
Rollup of HAL buffer API tweaks.

### PR DESCRIPTION
**Pull request by benvanik**

### CODE REVIEW

**Review by ScottTodd — APPROVED** [review]
`bazel_linux_x86-swiftshader_core` failure ([logs](https://source.cloud.google.com/results/invocations/c2d0d82e-b0fc-45a7-8085-ffd2176981fd/targets)) is a strange Kokoro error. LMK if it happens again and we can report it to that team.

**Comment by benvanik** [comment]
I just the tool failure and no logs - is that what you see? (I didn't change a BUILD file so I'm not sure it's caused by my PR e.g. making bazel parsing fail)

**Comment by ScottTodd** [comment]
> I just see the tool failure and no logs - is that what you see? (I didn't change a BUILD file so I'm not sure it's caused by my PR e.g. making bazel parsing fail)

internal logs:
```
java.io.IOException: Failed to delete pull label with reply
```
(then some java stacktrace stuff)

:P

**Comment by benvanik** [comment]
Sigh, kokoro. Will try a rerun.

**Pull request merged**
