### PR TITLE
Use tblgen.bzl from upstream

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
Previous efforts were stymied by the integrations/tensorflow WORKSPACE
and includes issues (because TF isn't using td_library). But we don't
have to worry about that now because we don't have any tablegen in
integrations/tensorflow anymore.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Depends on https://github.com/google/iree/pull/6449. Only the last commit is part of this PR

**Review by ScottTodd — APPROVED** [review]

**Comment by ScottTodd** [comment]
failing build:
https://source.cloud.google.com/results/invocations/c4fa97f6-6ba8-4af7-ad10-bb854b059620/targets/iree%2Fgcp_ubuntu%2Fcmake-bazel%2Flinux%2Fx86-swiftshader%2Fpresubmit/log
```
ERROR: /tmpfs/src/github/iree/integrations/tensorflow/iree_tf_compiler/BUILD:30:10: error loading package '@iree//iree/compiler/InputConversion/TOSA': cannot load '@llvm-project//mlir:tblgen.bzl': no such file and referenced by '//iree_tf_compiler:iree-tf-opt'
ERROR: Analysis of target '//iree_tf_compiler:opt-binaries' failed; build aborted: Analysis failed
```

**Comment by GMNGeoffrey** [comment]
Uh weird...

**Comment by GMNGeoffrey** [comment]
Oh this is because we're using TF's build files instead of the upstream ones. Ugh hang on. Let me just fix that then.

**Comment by GMNGeoffrey** [comment]
Ugh no that doesn't work either because TF references things in the build file that aren't upstream:

```
ERROR: /usr/local/google/home/gcmn/.cache/bazel/_bazel_gcmn/1018234ec5e9dfe498ad09b2cb840f90/external/org_tensorflow/tensorflow/compiler/mlir/BUILD:123:11: no such target '@llvm-project//mlir:friends': target 'friends' not declared in package 'mlir' defined by /usr/local/google/home/gcmn/.cache/bazel/_bazel_gcmn/1018234ec5e9dfe498ad09b2cb840f90/external/llvm-project/mlir/BUILD.bazel and referenced by '@org_tensorflow//tensorflow/compiler/mlir:init_mlir'
```

https://github.com/tensorflow/tensorflow/commit/fbe406d7319e6415cdff8b63bbcbd7bf74f223c5 might make this PR work as-is once we've integrated it

**Comment by ScottTodd** [comment]
> Ugh no that doesn't work either because TF references things in the build file that aren't upstream:
> 
> ```
> ERROR: /usr/local/google/home/gcmn/.cache/bazel/_bazel_gcmn/1018234ec5e9dfe498ad09b2cb840f90/external/org_tensorflow/tensorflow/compiler/mlir/BUILD:123:11: no such target '@llvm-project//mlir:friends': target 'friends' not declared in package 'mlir' defined by /usr/local/google/home/gcmn/.cache/bazel/_bazel_gcmn/1018234ec5e9dfe498ad09b2cb840f90/external/llvm-project/mlir/BUILD.bazel and referenced by '@org_tensorflow//tensorflow/compiler/mlir:init_mlir'
> ```
> 
> [tensorflow/tensorflow@fbe406d](https://github.com/tensorflow/tensorflow/commit/fbe406d7319e6415cdff8b63bbcbd7bf74f223c5) might make this PR work as-is once we've integrated it

Ok, I'll integrate TF and merge branches then we can try this again?

**Comment by GMNGeoffrey** [comment]
> Ok, I'll integrate TF and merge branches then we can try this again?

Yes please!

**Pull request merged**
