### PR TITLE
Remove dependency on llvm-bazel

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
Instead we use the Bazel build files now upstream in the LLVM
repository. There is a risk here because we can't go back and fix these
build files and continue to point at the same commit, so if the LLVM
integration into google3 uses a commit with broken build files, we won't
be able to update for a bit. I think the real solution to that may be to
create our own fork of LLVM where we can happily cherry-pick.

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Needs to wait till we integrate with a later LLVM

**Comment by GMNGeoffrey** [comment]
@hanhanW asking for your review specifically because you're build cop next week. I'll also be around to help out if things go sideways

**Review by ScottTodd — APPROVED** [review]
Any sequencing concerns with this? (open branch merges, presence of the submodule on the `google` branch, outstanding submodule update PRs, etc.)

**Review by hanhanW — APPROVED** [review]
thanks for the heads-up!

**Comment by GMNGeoffrey** [comment]
> Any sequencing concerns with this? (open branch merges, presence of the submodule on the `google` branch, outstanding submodule update PRs, etc.)

I don't think it should cause anything disastrous. Merging between the main and google branch will require resolving merge conflicts, the submodule update PRs will be against the google branch and will start using the updated scripting once this is merged there. So I think there are other things that could cause someone to revert this change, basically, but I don't think there's a time when that's not going to be true.

We'll want to do a main->google merge soon after so that the synchronize action will run the right script though.

**Comment by GMNGeoffrey** [comment]
I intend to merge this Monday morning (PT) and then I'll do some branch syncs to make sure everything's functioning properly

**Pull request merged**
