### PR TITLE
Integrate llvm-project at c531171d995728f55e5775d354a21dceed03edce

### PR DESCRIPTION
**Pull request by ThomasRaoux**
* llvm-project: c531171d995728f55e5775d354a21dceed03edce
* mlir-hlo: 285a97eaf56c7e1a736a95692b011aa6050445d4
* tensorflow: 74f10638c01d2c76a06a5be92a88ada04be0fea5

Extra changes:
* Update vector member getters names
* Disable padding patterns due to interface changes
* Fix iree_tr_compiler bazel dependency

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
I'd bias towards using Stella's scripts. It sets up name etc. in a way that is more consistent. Please update to form from previous integrates.

**Comment by ThomasRaoux** [comment]
> I'd bias towards using Stella's scripts. It sets up name etc. in a way that is more consistent. Please update to form from previous integrates.

If this is what is expected can we update the doc?

**Comment by ThomasRaoux** [comment]
> > I'd bias towards using Stella's scripts. It sets up name etc. in a way that is more consistent. Please update to form from previous integrates.
> 
> If this is what is expected can we update the doc?

I usually follow the doc and pick the solution 2 to update hlo and tensorflow. Using the script will pick a different commit. I'll match the template from other commits for now.

**Comment by MaheshRavishankar** [comment]
> > > I'd bias towards using Stella's scripts. It sets up name etc. in a way that is more consistent. Please update to form from previous integrates.
> > 
> > 
> > If this is what is expected can we update the doc?
> 
> I usually follow the doc and pick the solution 2 to update hlo and tensorflow. Using the script will pick a different commit. I'll match the template from other commits for now.

Which script? In the script I usually have to pick the commit....

**Comment by MaheshRavishankar** [comment]
> > > > I'd bias towards using Stella's scripts. It sets up name etc. in a way that is more consistent. Please update to form from previous integrates.
> > > 
> > > 
> > > If this is what is expected can we update the doc?
> > 
> > 
> > I usually follow the doc and pick the solution 2 to update hlo and tensorflow. Using the script will pick a different commit. I'll match the template from other commits for now.
> 
> Which script? In the script I usually have to pick the commit....

This is the script I use https://github.com/google/iree-samples/blob/main/scripts/integrate/bump_llvm.py

**Comment by ThomasRaoux** [comment]
> > > > > I'd bias towards using Stella's scripts. It sets up name etc. in a way that is more consistent. Please update to form from previous integrates.
> > > > 
> > > > 
> > > > If this is what is expected can we update the doc?
> > > 
> > > 
> > > I usually follow the doc and pick the solution 2 to update hlo and tensorflow. Using the script will pick a different commit. I'll match the template from other commits for now.
> > 
> > 
> > Which script? In the script I usually have to pick the commit....
> 
> This is the script I use https://github.com/google/iree-samples/blob/main/scripts/integrate/bump_llvm.py

Does this work when updating mhlo and tensorflow at the same time? It would be good to update the doc as I usually blindly copy paste from it

**Comment by MaheshRavishankar** [comment]
> > > > > > I'd bias towards using Stella's scripts. It sets up name etc. in a way that is more consistent. Please update to form from previous integrates.
> > > > > 
> > > > > 
> > > > > If this is what is expected can we update the doc?
> > > > 
> > > > 
> > > > I usually follow the doc and pick the solution 2 to update hlo and tensorflow. Using the script will pick a different commit. I'll match the template from other commits for now.
> > > 
> > > 
> > > Which script? In the script I usually have to pick the commit....
> > 
> > 
> > This is the script I use [https://github.com/google/iree-samples/blob/main/scripts/integrate/bump_llvm.py](https://github.com/google/iree-samples/blob/main/scripts/integrate/bump_llvm.py?rgh-link-date=2022-03-30T19%3A49%3A37Z)
> 
> Does this work when updating mhlo and tensorflow at the same time? It would be good to update the doc as I usually blindly copy paste from it

It only bumps LLVM and creates the PR. MHLO and Tensorflow steps are the same. Updated doc here https://github.com/google/iree/pull/8697

**Comment by ThomasRaoux** [comment]
> > > > > > > I'd bias towards using Stella's scripts. It sets up name etc. in a way that is more consistent. Please update to form from previous integrates.
> > > > > > 
> > > > > > 
> > > > > > If this is what is expected can we update the doc?
> > > > > 
> > > > > 
> > > > > I usually follow the doc and pick the solution 2 to update hlo and tensorflow. Using the script will pick a different commit. I'll match the template from other commits for now.
> > > > 
> > > > 
> > > > Which script? In the script I usually have to pick the commit....
> > > 
> > > 
> > > This is the script I use [https://github.com/google/iree-samples/blob/main/scripts/integrate/bump_llvm.py](https://github.com/google/iree-samples/blob/main/scripts/integrate/bump_llvm.py?rgh-link-date=2022-03-30T19%3A49%3A37Z)
> > 
> > 
> > Does this work when updating mhlo and tensorflow at the same time? It would be good to update the doc as I usually blindly copy paste from it
> 
> It only bumps LLVM and creates the PR. MHLO and Tensorflow steps are the same. Updated doc here #8697

Thanks for updating the doc, I tend to shutdown my brain and follow instructions when doing the upgrade

**Review by benvanik — APPROVED** [review]

**Pull request merged**
