### PR TITLE
Fix web samples and test building them on CI.

### PR DESCRIPTION
**Pull request by ScottTodd**
Assorted cleanup in service of getting these experimental samples tested as part of the (post-submit, non-blocking) https://buildkite.com/iree/iree-samples pipeline:

Summary of commits:

* Code fixes so the targets build again
* Refactor scripts to be CI-friendly (no hardcoded paths, no automatic web server that takes over the console)
* Expand linker tool discovery so the `lld` we build + install can be used with `-flavor wasm` instead of requiring `wasm-ld`
* Run build scripts as part of the samples pipeline

Sample CI run: https://buildkite.com/iree/iree-samples/builds/268

### CODE REVIEW

**Comment by benvanik** [comment]
The cleanup is good but these will never move out of experimental as-is and shouldn't be on any presubmit - no one should have to fix these beyond best-effort find/replace. If we had a bot that was just FYI and never showed red that'd be a good place for them but the point of experimental/ is to not impose support requirements for prototypes/experiments/unsupported configurations.

It'd be much better to start productionizing the wasm path than to spend more time trying to productionize a demo :)

**Comment by ScottTodd** [comment]
> The cleanup is good but these will never move out of experimental as-is and shouldn't be on any presubmit - no one should have to fix these beyond best-effort find/replace. If we had a bot that was just FYI and never showed red that'd be a good place for them but the point of experimental/ is to not impose support requirements for prototypes/experiments/unsupported configurations.
> 
> It'd be much better to start productionizing the wasm path than to spend more time trying to productionize a demo :)

Okay. How does the https://buildkite.com/iree/iree-samples pipeline ([configuration source](https://github.com/google/iree/blob/main/build_tools/buildkite/samples.yml)) sound? That one is postsubmit and best-effort already. I could either copy the `build-host-install` step or install the host tools from the latest `iree-dist-*-linux-x86_64.tar.xz` on https://github.com/google/iree/releases for that.

(I'm also okay with keeping these off of all CI builds, but if coverage is easy to slot in then an FYI is nice to get)

**Review by GMNGeoffrey — APPROVED** [review]
Please run this build on this PR to test that everything works

**Comment by ScottTodd** [comment]
> Please run this build on this PR to test that everything works

https://buildkite.com/iree/iree-samples/builds/268 is linked in the PR description (though that was before a rebase + force push, so the commits are a little different)

**Comment by GMNGeoffrey** [comment]
> > Please run this build on this PR to test that everything works
> 
> https://buildkite.com/iree/iree-samples/builds/268 is linked in the PR description (though that was before a rebase + force push, so the commits are a little different)

Ah sorry I missed that. Was looking in the list of checks

**Review by benvanik — APPROVED** [review]

**Pull request merged**
