### PR TITLE
Fix unused var for clang-15

### PR DESCRIPTION
**Pull request by powderluv**
TEST: Builds on Clang15 with this fix

### CODE REVIEW

**Comment by powderluv** [comment]
seems like an unrelated error

```
/tmpfs/src/github/iree/compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp:267:57: error: use of undeclared identifier 'i'
        LLVM_DEBUG(dbgs() << "ConstExprHoistPolicy(" << i << ", ");
                                                        ^
/tmpfs/src/github/iree/compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp:278:55: error: use of undeclared identifier 'i'
      LLVM_DEBUG(dbgs() << "ConstExprHoistPolicy(" << i << ", CONVERGED)\n");
                     ```

**Comment by stellaraccident** [comment]
Ah, looks like the loop var was used but only for debug builds. The right thing to do in this case is to put it back how it was and add a `(void)i` to the loop body.

**Comment by powderluv** [comment]
Damn pesky compilers .. we got to fool them to get around their warnings/errors 🗡️ 

Anyway ```
/home/anush/github/SHARK-Runtime/compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp:258:19: error: value of type 'void' is not contextually convertible to 'bool'               

  for (int i = 0; (void)i; ++i) {
                         ^~~~~~~

1 error generated.```

But ```for (int i = 0; i; ++i) {``` seems ok to fool it.

**Comment by stellaraccident** [comment]
Did you try putting the (void)i in the body of the loop? I have a feeling that is happening because the second clause of a for loop is evaluated as an expression, not a statement, and as written, that is an empty expression. Or something like that.

I generally dislike these aggressive warnings... But they do catch things and keep things tidy :/

**Comment by powderluv** [comment]
Ahh.. you mean the body of the loop :D seems to work now.

**Pull request merged**
