### PR TITLE
Avoid mutating `hal.constant.subspan` when converting to HAL

### PR DESCRIPTION
**Pull request by antiagainst**
Constants are collected together into a pool. They already have
their own buffer that is read only. When converting to HAL
we analyze `flow.ex.stream.fragment` ops and their regions to
allocate output/transient buffers. The buffer allocation there
considers aliasing. But we cannot create aliases from constant
subspans if they are mutated. We need to allocate new buffers
and copy over the data for mutated cases.

### CODE REVIEW

**Comment by antiagainst** [comment]
This was my previous attempt to address https://github.com/google/iree/issues/5989. I mentioned it during today's meeting so sending out. But I guess what Ben's suggest (https://github.com/google/iree/pull/6049#pullrequestreview-673245396) might be better. I'll look into doing that. :)

**Comment by benvanik** [comment]
> This was my previous attempt to address #5989. I mentioned it during today's meeting so sending out. But I guess what Ben's suggest ([#6049 (review)](https://github.com/google/iree/pull/6049#pullrequestreview-673245396)) might be better. I'll look into doing that. :)

👍 yeah this is a similar kind of copy-on-write (and one of the lurking corner cases I was referring to): we'd want to canonicalize a constant subspan + update -> constant subspan + clone + update - which may happen for free with the change in the flow level (as the constant + update -> constant + clone + update should then get lowered into constant subspan + clone + update, no need for any changes to hal)

**Comment by benvanik** [comment]
There's also performance benefits in doing it clone+in-place-update, as then the clone is DMA and the dispatch updating the subregion is just of the changed subregion, vs. if it's done untied such that the dispatch updating only a subregion needs to memcpy the entirety of the output buffer with just the subregion modified. Think 128x4096 getting a 1x4096 row updated: you'd want to dma the 128x4096 and then dispatch 1x4096, vs. dispatching 128x4096 with all the select logic.

**Comment by antiagainst** [comment]
#6174 superseded this.

**Pull request closed without merging**
